### ISSUE TITLE
Consider renaming `Evented` trait

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#1003]
The best option currently is `Source`.

Continuing the discussion from https://github.com/tokio-rs/mio/issues/905#issuecomment-491046264.

**Comment by Thomasdezeeuw** [comment]
Also want to move this into the `event` module? Then we have `event::Source` which seems like a nice name.

**Comment by carllerche** [comment]
@Thomasdezeeuw sounds good to me :+1:
