### ISSUE TITLE
Allow getting raw socket handle in Windows

### ISSUE THREAD

**Issue by gleon99** [tokio-rs/mio#1010]
Currently there's no way in Windows to get a raw socket handle from a `mio::net::TcpListener` or `mio::net::TcpStream` - i.e, like `IntoRawFd` in Unix.

Please add this functionality, as well as `FromRawFd` and `AsRawFd`, .

**Comment by Thomasdezeeuw** [comment]
@gleon99 a pull request would gladly be accepted.

**Comment by carllerche** [comment]
Dup of #859 (which is blocked on a new windows impl).
