### ISSUE TITLE
[Bug] Sometimes Poll::poll doesn't notify even if sockets are ready to read (using kqueue).

### ISSUE THREAD

**Issue by c-bata** [tokio-rs/mio#1011]
Hi! Thank you for developing this cool library.

## Bug details

I implemented a simple http server using mio for my understanding. The source code is below:

https://gist.github.com/c-bata/3540c6959cdad0f0644928887d32c13c

When I sends multiple requests to this http server using apache bench, some responses are blocked.

```
$ ab -h
Usage: ab [options] [http[s]://]hostname[:port]/path
Options are:
    -n requests     Number of requests to perform
    -c concurrency  Number of multiple requests to make at a time
    ...
$ ab -n 1000 -c 10 http://127.0.0.1:13265/
This is ApacheBench, Version 2.3 <$Revision: 1826891 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 991 requests completed
```

As the output shows, `concurrency - 1` requests are blocked. The reason why the rest of 9 requests are blocked is `poll.poll(&mut events, None)` doesn't return the value even if the sockets are ready to read.

## Environments

* os: mac os mojave 10.14.5
* rustc: rustc 1.37.0-nightly (2fe7b3383 2019-06-19)
* revision of mio: 47809ef

**Comment by Thomasdezeeuw** [comment]
When using edge triggers (only option on master branch) you need to call `accept` (on the `TcpListener`) until it returns a would block error. This is not a bug.

**Comment by c-bata** [comment]
I see. Thanks!
