### ISSUE TITLE
Discussion around `cvt`

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1015]
The `cvt` function (defined here: https://github.com/tokio-rs/mio/blob/aa84849c612a8887fab92581e8101369e0b2c4eb/src/sys/unix/mod.rs#L43-L66) is helper function to convert a system call return value into an `io::Result`.

I'm personally not a fan of it. It is just a single if statement and I think it's better to just inline this in the code.

At the very least it could do with a better name.

**Comment by carllerche** [comment]
I am not a fan of the `cvt` function as it is either, but IMO reducing duplication of code like this is good.

Instead, what about a macro? That would remove the requirement for the `IsMinusOne` trait:

```rust
macro_rules! try_sys {
    ($e:expr) => {{
        let res = $e;
        if res == -1 {
            return Err(io::Error::last_os_error());
        } else {
            Ok(res)
        }
    }};
}
```

**Comment by Thomasdezeeuw** [comment]
What if we remove the `return` and just return an `io::Result` from the macro. Then we use the result, e.g.:

```rust
try_sys!(libc::kqueue()).map(|kq| Selector { kq })
```

**Comment by carllerche** [comment]
Sure but then I would avoid “try” in the name as that tends to mean return early on error.

**Comment by Thomasdezeeuw** [comment]
`sys_call`? Maybe we add `libc::` in the macro, so it becomes `sys_call!(kqueue())`.

**Comment by carllerche** [comment]
`syscall!` would be fine, but i wouldn't implicitly add `libc::` as i think that would make reading it more confusing.
