### ISSUE TITLE
Use MaybeUninit from 1.36

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1017]
With 1.36 being stable (https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html) we can use `MaybeUninit`, this allows use to remove some undefined behaviour from Mio.

Related https://github.com/Thomasdezeeuw/gaea/issues/49, https://github.com/Thomasdezeeuw/gaea/pull/71.

**Comment by carllerche** [comment]
:+1: we can target that

**Comment by Thomasdezeeuw** [comment]
We're using this is the code, I don't think much more can be done.
