### ISSUE TITLE
Eliminate usage of unsafe code in `eventfd::Waker::wake`

### ISSUE THREAD

**Issue by cynecx** [tokio-rs/mio#1032]
https://github.com/tokio-rs/mio/blob/eadafc2bed0c8d8f10e527f8cf25fac606e1fdfc/src/sys/unix/waker.rs#L33

Can be replaced with:

```rust
let buf: [u8; 8] = 1u64.to_ne_bytes(); 
```

https://doc.rust-lang.org/std/primitive.u64.html#method.to_ne_bytes

EDIT:

Also this line could be simplified (no issue with unsafe code here):

https://github.com/tokio-rs/mio/blob/eadafc2bed0c8d8f10e527f8cf25fac606e1fdfc/src/sys/unix/waker.rs#L48

with

```rust
let buf: [u8; 8] = 0u64.to_ne_bytes(); 
```

**Comment by Thomasdezeeuw** [comment]
Fixed in #1033. Thanks for the review @cynecx, if you any more comments let us know.
