### ISSUE TITLE
Installing Rust takes 2 minutes longer on Windows then Linux on Azure

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1044]
While developing #1029 for Windows I had too wait for the CI quite a bit, in doing so I noticed that installing Rust took about 2.5 minutes long on Windows, while it only took 40 seconds on Linux.

**Comment by piscisaureus** [comment]
But that's not really a mio issue, or is it?

I'm quite sure this is caused by windows' terrible file system performance and rustup force feeding a bazillion html files from the rustdoc component.

**Comment by Thomasdezeeuw** [comment]
No but it slowing down the CI, I though it worth looking into. But maybe it should be moved to the Rustup or Azure issue tracker.

**Comment by Dushistov** [comment]
There are a lot of recent fixes in rustup + windows in recent versions of rustup, for example: rust-lang/rustup.rs#1850 .
