### ISSUE TITLE
Reduce TcpStream, TcpListener and UdpSocket API to the same as in libstd

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1045]
Currently Mio provides the following methods on `TcpStream` which the standard library doesn't (includes both setters and getters):

 - linger.
 - keepalive.
 - send_buffer_size.
 - recv_buffer_size.

In addition I suggest we remove `TcpStream::connect_stream` and `TcpStream::from_stream` to reduce the API further. `FromRawFd` and `FromRawSocket` can be used instead. Same goes for `TcpListener::from_std`, `TcpListener::accept_std` and `UdpSocket::from_socket`.

This also a potential blocker for #1029, as we currently use net2's implementation to provide most of the methods.

**Comment by carllerche** [comment]
@Thomasdezeeuw I'm :+1: on this, at least initially. We can always consider adding them back later w/o depending on net2.

**Comment by chewi** [comment]
Any idea when these might return? I have a strong need for setting the send buffer size. I looked at how socket2 does it and I feel a little dirty doing an unsafe syscall to `setsockopt`. I know that's how it would happen under the hood anyway but this is the first I've ever had to use unsafe myself!

**Comment by Thomasdezeeuw** [comment]
@chewi its still a bit of an open debate to what API Mio should support. In this issue, and various other discussions, we decided to limit ourselves to the same API std lib provides. A long term solution would be to add these (and other socket related functions) to std lib and to Mio. A short term solution would be indeed to use a crate like socket2 to handle this.
