### ISSUE TITLE
Determine how to do deal with WSAStartup on Windows

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1046]
We first saw the issue in #1029, where the following error appeared: `Os { code: 10093, kind: Other, message: "Either the application has not called WSAStartup, or WSAStartup failed." }`.

We can't initialise it ourselves as standard library has an assertion to check if the return value is ok: https://github.com/rust-lang/rust/blob/00859e3e653973120006aaf3227823062dde1ba7/src/libstd/sys/windows/net.rs#L38.

**Comment by Thomasdezeeuw** [comment]
We could do the same as in the standard library add an `init` function that somehow triggers the standard library's init function. For the tests in #1029 I added a call to `TcpListener::bind` that is dropped immediately: https://github.com/tokio-rs/mio/blob/dae8291aed0fa0c5aa7b449c630712cb2c441da7/tests/util/mod.rs#L137

However that is not really a pretty solution.

**Comment by carllerche** [comment]
How exactly did you trigger it? What fn did you call that returned the error?

**Comment by carllerche** [comment]
I see you are calling socket directly. Would it be possible to create all sockets by going through `std` types?

**Comment by Thomasdezeeuw** [comment]
Maybe, but then we would be then we would miss out on the optimisation to set `NONBLOCK` and `CLOEXEC` in the call to `socket`, see https://github.com/tokio-rs/mio/blob/dae8291aed0fa0c5aa7b449c630712cb2c441da7/src/sys/unix/mod.rs#L76

When we create a socket via the standard library we need to set non blocking after, incurring another system call.

**Comment by carllerche** [comment]
@Thomasdezeeuw I only mean do this on windows. Do those optimizations apply to windows? I know `CLOEXEC` wouldn't (since there is no fork). I'm not sure about the other one.

**Comment by Thomasdezeeuw** [comment]
For `TcpStream::connect` we need to set the socket to non-blocking mode before connecting otherwise the connect system call would block.

**Comment by carllerche** [comment]
@Thomasdezeeuw This is how `net2` does it: https://github.com/rust-lang-nursery/net2-rs/blob/master/src/sys/windows/mod.rs#L55-L64

Probably the best way...

**Comment by andrewtj** [comment]
If an `init()` like function is going to be added, can it be made public and perhaps also be a no-op on other platforms? I ask as I'm currently doing a similar throw away bind behind a `Once` in one of my crates.

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw This is how `net2` does it: https://github.com/rust-lang-nursery/net2-rs/blob/master/src/sys/windows/mod.rs#L55-L64
> 
> Probably the best way...

I did roughly the same thing in #1029 , see https://github.com/tokio-rs/mio/pull/1029/commits/8c33265c4c9674d92e494868016e466066b8ac88. I'll move the init function to the Windows implementation rather then the tests then.

> If an `init()` like function is going to be added, can it be made public and perhaps also be a no-op on other platforms? I ask as I'm currently doing a similar throw away bind behind a `Once` in one of my crates.

Wasn't going to make it public, but maybe we could do something like that.

I was also thinking to maybe move this into `Poll::new()` and document that any and all types (other then `Poll`) can only be created after a `Poll` instance is created.

**Comment by carllerche** [comment]
I probably wouldn't make the `init()` fn public.

**Comment by Thomasdezeeuw** [comment]
This was fixed in #1029.
