### ISSUE TITLE
windows: support custom completion port integrations

### ISSUE THREAD

**Issue by piscisaureus** [tokio-rs/mio#1047]
The new "wepoll" strategy is great for sockets but it makes it impossible to use the thread's I/O completion port for other purposes.
I would suggest to add a low-level "plugin" system so that other crates can share the completion port for different purposes.

This could be used for supporting named pipes and files, which can use overlapped I/O but their APIs work differently; more exotic examples are [ReadDirectoryChangesW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw) (file change notifications), [GetAddrInfoExW](https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfoexw) (async DNS name lookup), and [Job Objects](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-_jobobject_associate_completion_port) (notifications about child processes).

Job objects in particular are exotic in that windows will send messages to the completion port where `lpOverlapped` does not actually point to a `struct OVERLAPPED`, but rather contains an indication of the event that happened.

So I would propose to to "switch" based on the `lpCompletionKey` value. The most simple solution would be to store a function pointer in it which receives the raw completion information, e.g. `fn handle_completion(&OVERLAPPED_ENTRY)`.

To illustrate what I mean, here's a crude prototype: https://github.com/piscisaureus/mio/commit/ac40cd71c31a5014592ba232523a4607f07f371a

Notice how the `Selector` is no longer knows anything about `Wake` events.
They work simply because the `lpCompletionKey` contains an appropriate [function pointer](https://github.com/piscisaureus/mio/commit/ac40cd71c31a5014592ba232523a4607f07f371a#diff-bde7ec4aecb3fa131e34b63a2c7cc173R33)

**Comment by Thomasdezeeuw** [comment]
Related #526.

**Comment by Thomasdezeeuw** [comment]
I think this is related to a `SourceSocket` idea as discussed in https://github.com/tokio-rs/mio/issues/880#issuecomment-522720856.

**Comment by Thomasdezeeuw** [comment]
Punting to v1.0.

**Comment by carllerche** [comment]
@piscisaureus I have a question re: this proposal.

My understanding is that, when an OVERLAPPED operation is submitted to the OS, the OS needs "ownership" of the pointer. Ownership is returned back to the caller when the operation is completed and the overlapped is received during a "poll".

This implies that the selector needs to know about "in-flight" operations. This needs to happen so that when the `Poll` handle is dropped, it knows to wait until "in-flight" operations complete. 

It gets a bit more complicated with "read" like operations that may not complete... in those cases, `Poll` needs to know about all inflight operations, signal to them to start shutting down, then wait to receive the OVERLAPS before dropping.

Do you have thoughts on how to model this?

**Comment by dtacalau** [comment]
@Thomasdezeeuw please assign this issue to me, will start working on it.

**Comment by carllerche** [comment]
@dtacalau before writing code we should have a solid proposal in place. I think bert’s sketch is a good starting point but we want to figure out the answers to my previous comment as well as a nice rust API to expose.

**Comment by piscisaureus** [comment]
@carllerche 

>My understanding is that, when an OVERLAPPED operation is submitted to the OS, the OS needs "ownership" of the pointer. Ownership is returned back to the caller when the operation is completed and the overlapped is received during a "poll".
> Do you have thoughts on how to model this?

Make sure the Overlapped is wrapped (either directly or indirectly) wrapped in an Arc.

When an async I/O operation is successfully started (and you know the kernel now implicitly owns the OVERLAPPED) you artificially increase the Arc's reference count by cloning and forgetting the Arc.

When the operation completes and you receive a OVERLAPPED* from GetQueuedCompletionStatus, do some pointer math if necessary to get back at the wrapper struct, and then transmute/cast that back to an Arc, thereby effectively reversing the std::mem::forget::<Arc>() we did after starting the operation.

I think the most elegant way was in this (rejected) patch:

* https://github.com/tokio-rs/mio/pull/1154/commits/88407fbe4d309732d620230bb5998f12761318f4#diff-8e89b097d3e3119d177930239584d29eR162
* https://github.com/tokio-rs/mio/pull/1154/commits/88407fbe4d309732d620230bb5998f12761318f4#diff-8e89b097d3e3119d177930239584d29eR181-R189
* https://github.com/tokio-rs/mio/pull/1154/commits/88407fbe4d309732d620230bb5998f12761318f4#diff-8e89b097d3e3119d177930239584d29eR569

**Comment by Thomasdezeeuw** [comment]
@piscisaureus that patch, with modifications, made it into the code base: https://github.com/tokio-rs/mio/blob/3ebce3e276f58126c25bdf9b606fe4676c0013c1/src/sys/windows/selector.rs#L288-L301. I think we're doing it correctly now, the way you've explained it.

**Comment by carllerche** [comment]
Instead of making an API to hook into IOCP, would it be plausible to provide bindings to all the IOCP compatible types? The various types could be guarded w/ feature flags.

**Comment by Thomasdezeeuw** [comment]
Not blocking a v1.0 release.

**Comment by Thomasdezeeuw** [comment]
We have/had a partially working solution in https://github.com/tokio-rs/mio/pull/1345, but there is not enough interest to make this work. Because of this I'm closing this.
