### ISSUE TITLE
Expand testing of LIO

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1054]
Currently the use LIO isn't tested at all in Mio. This is a tracking issue to expand the testing LIO in Mio. To start the following should be tested:

- [ ] If the options (`Interests`) are passed correctly to kqueue.
- [ ] Any events are generated and check if we correctly detect the flag (in `Event::is_lio`).

Continuation of #1036 and #1048.

**Comment by asomers** [comment]
I think the easiest way to write these tests would be to start with the code in mio-aio and strip it down.  But mio-aio was written for mio 0.6.  Has anybody yet written a mio 0.6 - 0.7 migration guide?  That would help me.

**Comment by Thomasdezeeuw** [comment]
I don't anyone has written a guide like that, would be very useful.
