### ISSUE TITLE
Suspect Windows UDP operations

### ISSUE THREAD

**Issue by Ralith** [tokio-rs/mio#1062]
The Windows UDP I/O operations that deal with explicit `SocketAddr`s seem to be missing the WouldBlock handling that their addressless analogs have, and which are presumably necessary for readiness notification to work: https://github.com/tokio-rs/mio/blob/master/src/sys/windows/udp.rs#L76-L86

Additionally, it's odd that `connect` has that handling, as UDP connectedness is a purely local convenience function that performs no actual I/O whatsoever, and hence is probably incapable of blocking.

**Comment by Thomasdezeeuw** [comment]
@PerfectLaugh can you look at this?

**Comment by PerfectLaugh** [comment]
I have to wait for the #1055 land on first since I made changes in udp.rs

**Comment by Thomasdezeeuw** [comment]
Closed by #1066.
