### ISSUE TITLE
Change event::Source to take &mut (instead of &self)

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1064]
This would allow future implementations to forgo any locking/synchronisation if it requires mutable access to any of its internals. Any types that don't need this, for example most types currently exported, can also implement the trait for `&Self` (e.g. `impl event::Source for &TcpStream`) to allow concurrent access. We do something similar with the `io::Read` and `io::Write` traits for `TcpStream`.

`Registry::(re,de)register` would also take `&mut S` (`S: event::Source`).

/cc @carllerche @asomers

**Comment by carllerche** [comment]
We can go this route, but that would mean we aren’t merging Poll and Registry?

**Comment by carllerche** [comment]
Basically, if we keep the Poll / Registry split, this is a good next step. If not, we probably want to keep &self and say Source impls should be sync

**Comment by Thomasdezeeuw** [comment]
Now that `Poll` and `Registry` no longer require an `Arc` I'm fine with keeping them split apart. How does Tokio use (or would use) the new `Registry`? Really I'm fine with either option at this point.

**Comment by carllerche** [comment]
Ah, Tokio would want to store a `Registry` handle in an `Arc`, so I guess that would mean `Registry` can't take `&mut self`.

**Comment by asomers** [comment]
This would be helpful for mio-aio, which needs to modify the `Evented` during `register` and `deregister`.

**Comment by carllerche** [comment]
The downside would be it would make tokio's `PollEvented` helper more complicated. Right now, it takes `T: Source`. Given that `PollEvented` requires `Sync`, i'm not 100% sure how it would be updated yet.

**Comment by carllerche** [comment]
It would probably require adding a new trait (not necessarily in mio): `SyncSource`

**Comment by carllerche** [comment]
I actually don't think ^^ is bad. I probably should probably not export mio from tokio anyway and make it an implementation detail

**Comment by Thomasdezeeuw** [comment]
@carllerche maybe something like this would work; https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=20a13845d951953a9bf8eb90f76e251b.

**Comment by carllerche** [comment]
@Thomasdezeeuw but what does PollEvented<T> use as a bound for T?

I think it would require GAT... which could be simulated with where for but that is ugly

**Comment by Thomasdezeeuw** [comment]
@carllerche You can add `&S: Source` bound, see https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=784b310e4e292daeb8f4e2271184b0ff.

**Comment by carllerche** [comment]
Hmm, i will have to experiment more, because IIRC, that pattern breaks down at some point....

**Comment by Thomasdezeeuw** [comment]
@kleimkuhler I believe you ported Tokio to Mio 0.7, what do you think about the change?

**Comment by kleimkuhler** [comment]
Tokio's use of Mio doesn't seem to affected by this from what I can tell. My fork of Mio has a [branch](https://github.com/kleimkuhler/mio/tree/kleimkuhler/issue-1064) that makes this change, and my fork of Tokio has a [commit](https://github.com/kleimkuhler/tokio/commit/6929b5aeeafd262b4dc125f70404299819c08e39) that uses this change. The latest commit is the one change required.

The changes are on top of the Mio update branch, so all the changes that happened already (I think mainly putting `Registry` behind an `Arc` and keeping `Poll` separate) set this up to be pretty trivial. @carllerche was correct in the assumption that `Registry` would be behind an `Arc`, so there may be something more about the additional `SyncSource` trait being required, but it doesn't seem necessary right now.

**Comment by Thomasdezeeuw** [comment]
@carllerche do you have time to consider this? As @kleimkuhler mentioned Tokio doesn't seem to be affected.

**Comment by carllerche** [comment]
@kleimkuhler how did it impact `PollEvented`?

**Comment by carllerche** [comment]
I looked... I forgot we made registration eager, which simplifies things a lot.

This change would not impact Tokio it seems like, so I'm fine w/ whatever.
