### ISSUE TITLE
Investigate TcpStream smoke test failures

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1078]
Pr #1070 is going to add (or added, depending on when you read this) two smoke tests for  `TcpStream` `tcp_stream_ipv4` and `tcp_stream_ipv6`, which only fails on Windows. Figure out why.

/cc @PerfectLaugh

**Comment by dtacalau** [comment]
@Thomasdezeeuw could you please assign this issue to me. I've started working on it.

**Comment by dtacalau** [comment]
Tests fail because of issue described here #1131, we need to reregister the interests after TcpStream::read which emptied the sock bufffer.
