### ISSUE TITLE
Investigate TcpStream nodelay test failures

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1079]
Pr #1070 is going to add (or added, depending on when you read this) a tests for  `TcpStream::(set)_nodelay` `nodelay`, which only fails on Windows. Figure out why.

/cc @PerfectLaugh

**Comment by JuSiZeLa** [comment]
The test is failing when the `set_nodelay` function is called on a socket which is not connected yet. All calls to `setsockopt` while the socket is not connected yet are going to fail.

**Comment by Thomasdezeeuw** [comment]
Fixed in #1105.
