### ISSUE TITLE
Investigate UdpSocket test failures

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1080]
See #1070 tests that are ignored on Windows.

**Comment by dtacalau** [comment]
@Thomasdezeeuw could you please assign this issue to me. I've started working on it.

**Comment by dtacalau** [comment]
Tests fail because of issue described here #1131, we need to reregister the interests after a read which emptied the sock bufffer.

**Comment by dtacalau** [comment]
Fixed by @1167. @Thomasdezeeuw  this can be closed.
