### ISSUE TITLE
poll: winit-0.20.0-alpha3: Combining event loops?

### ISSUE THREAD

**Issue by cheako** [tokio-rs/mio#1082]
Winit has a particular way it's implementing an event loop.  Any examples of using the NEW 0.20.0 event loop with mio?  Any examples that run mio in a thread of it's own?

**Comment by Thomasdezeeuw** [comment]
I haven't used winit before, but taking a quick look at the docs it might work if the create thread that polls Mio and sends the (relevant) events to the Winit event loop using [`EventLoopProxy::send_event`](https://docs.rs/winit/0.20.0-alpha3/winit/event_loop/struct.EventLoopProxy.html#method.send_event).

I don't know if the `EventLoop` type of Winit is backed by a file descriptor on Unix, if it is you could try and register that with Mio using [`EventedFd`](https://docs.rs/mio/0.6.19/mio/unix/struct.EventedFd.html) poll Mio.

**Comment by Thomasdezeeuw** [comment]
Closing this as it seems there is nothing to do.
