### ISSUE TITLE
TcpStream always blocks on Windows but not on Linux

### ISSUE THREAD

**Issue by ZakisM** [tokio-rs/mio#1093]
Tested on both Windows 10/Windows 7:

[Playground Code](https://gist.github.com/rust-play/0dd3c6c1067a64f6f83ca309bb94595f)

Windows output after 5 attempts:

CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): spurious event, ignoring
CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): spurious event, ignoring
CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): spurious event, ignoring
CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): spurious event, ignoring
CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): spurious event, ignoring

Linux output after 5 attempts:

CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): read 100 bytes: [GET / HTTP/1.1
Host: localhost:1234
User-Agent: insomnia/6.6.2
Accept: */*
Content-Length: 0

]
CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): read 100 bytes: [GET / HTTP/1.1
Host: localhost:1234
User-Agent: insomnia/6.6.2
Accept: */*
Content-Length: 0

]
CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): read 100 bytes: [GET / HTTP/1.1
Host: localhost:1234
User-Agent: insomnia/6.6.2
Accept: */*
Content-Length: 0

]
CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): read 100 bytes: [GET / HTTP/1.1
Host: localhost:1234
User-Agent: insomnia/6.6.2
Accept: */*
Content-Length: 0

]
CLIENT (receiver): event=Event { kind: Ready {Readable}, token: Token(0) }
CLIENT (receiver): read 100 bytes: [GET / HTTP/1.1
Host: localhost:1234
User-Agent: insomnia/6.6.2
Accept: */*
Content-Length: 0

]

**Comment by carllerche** [comment]
cc @PerfectLaugh

**Comment by dtacalau** [comment]
This issue has the same cause as #1126. I've just checked this with PR#1127 and does not reproduce, Windows output looks fine.

The test program used to reproduce the issue, updated to work on latest master. 
[main.zip](https://github.com/tokio-rs/mio/files/3870151/main.zip)

Output when testing the server with curl:
```
CLIENT (receiver): event=Event { token: Token(0), readable: true, writable: false, error: false, read_closed: false, write_closed: false, priority: false, aio: false, lio: false }
CLIENT (receiver): read 78 bytes: [GET / HTTP/1.1
Host: localhost:9999
User-Agent: curl/7.65.3
Accept: */*

]
```

**Comment by dtacalau** [comment]
@Thomasdezeeuw please assing this issue to me, thanks!

**Comment by Thomasdezeeuw** [comment]
This should be fixed in #1127, @ZakisM can you confirm?

**Comment by ZakisM** [comment]
Yep, working now. Thanks!

**Comment by Thomasdezeeuw** [comment]
Great.
