### ISSUE TITLE
Move UDS types to unix module

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1114]
Currently the UDS types (`UnixDatagram`, `UnixListener`, `UnixStream`) currently live in the net module, but they are Unix only. Shouldn't these live in the unix module (following what std lib does)? Or perhaps in `mio::unix::net`.

If Windows (or more platforms) ever get support for them we can always moves them, leaving alias in the unix module.

/cc @kleimkuhler

**Comment by DoumanAsh** [comment]
>If Windows (or more platforms) ever get support for them we can always moves them, leaving alias in the unix module.

JFYI some newer versions of Win10 supports it

**Comment by Thomasdezeeuw** [comment]
> JFYI some newer versions of Win10 supports it

Good to know, but Mio doesn't (yet) support them.

**Comment by carllerche** [comment]
I believe that keeping platform specific types in separate modules & trait extensions has been considered a ["mistake"][1]. Instead, types should just be where they make natural sense and use feature flags to enable / disable.

So i would recommend to follow this guidance.

[1]: https://aturon.github.io/tech/2018/02/06/portability-vision/

**Comment by Thomasdezeeuw** [comment]
@carllerche the blog post makes a lot of good points, I'm ok with leaving it the net module. Do you want to the same for `SourceFd` (and possible future Windows counterpart)? I'm not sure where they would move to though.

Also should more documentation be added that they're Unix only, I know the name suggests it but still. The API in the standard library have a clear blue box, e.g. see https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html, but I don't know if that is available for user code yet.

**Comment by arsing** [comment]
(UDS support on Windows previously discussed in https://github.com/tokio-rs/mio/issues/880 )

**Comment by Thomasdezeeuw** [comment]
Not doing this, leaving the UDS types in the net module.
