### ISSUE TITLE
Reconsider `transparent` on `Event`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#1122]
I'm mostly opening this issue as I'm not sure what the benefit of having `transparent` on `Event` is. It may be that I am blind, but I thought I would open the issue instead of forgetting to ask :)

**Comment by Thomasdezeeuw** [comment]
I think I added this because at some point we did `&Event as *const Event as *const libc::kevent`, which needed the transparent attribute. But I don't think we need it any more.
