### ISSUE TITLE
Edge-triggered behaviour is broken for Windows poll

### ISSUE THREAD

**Issue by dtacalau** [tokio-rs/mio#1131]
Mio tests expect Windows poll to be ET, but it's not, this  is the cause of many test failures on Windows. I want to have a place to discuss ways to fix this away from other issues which may cause specific tests to fail.

So far we have the following data:
1. a TcpListener::accept won't trigger READABLE event, issue #1126 
2. a TcpStream::write done after a TcpStream::read which emptied the sock buffer, won't trigger READABLE event, issue #1078
3. UDP sockets are also affected by no.2, issue #1082 

All failures above are fixed if I add reregister(READABLE) before the actual poll call.

Previous discussions on reregistering on successful call here 
https://github.com/tokio-rs/mio/pull/1112/commits/3acd892d27cd76b37f5f4660a0e0cf7f56bef2c1#r340302964 and here https://github.com/tokio-rs/mio/pull/1127#issuecomment-550386326

I think the reregistering should be handled per each specific call, so, for each call affected by this issue we need to detect the condition when the next call would block and do reregister:
1. accept -> do reregister on succesful accept
```
TcpListener::accept 
    pub fn accept(&self) -> io::Result<(TcpStream, SocketAddr)> {
        try_io!(self, accept)
        if (OK) reregister(READABLE)
```
2. read -> do peek after each successful read to see if next read would block
```
TcpStream::read 
    fn read(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        try_io!(self, read, buf)
        if (peek() = wouldblock) reregister(READABLE) 

    }
```
3. write ??? not sure how to detect next write would block?

@Thomasdezeeuw let me know what you think, I could come up with a patch, but would like to be on the same page with this before coding it :).

**Comment by Thomasdezeeuw** [comment]
I think I mentioned this already on one of the issues; I think we way to fix this is to reregister after an I/O operation if:
* We hit a would-block error (already happens).
* We exhausted the I/O operations, e.g. in case of a read: `bytes_read <= buf.len()`.

**Comment by Thomasdezeeuw** [comment]
@dtacalau what do you think? I might same some time to try this later tonight.

**Comment by dtacalau** [comment]
> I think I mentioned this already on one of the issues; I think we way to fix this is to reregister after an I/O operation if:
> 
> * We hit a would-block error (already happens).
> * We exhausted the I/O operations, e.g. in case of a read: `bytes_read <= buf.len()`.

@Thomasdezeeuw yes you did mention it, I also had 3 failing tests affected by it, wanted to have it all in one place. So, taking them one by one:
- OK with hit a would-block error;
- OK with checking condition in case of a read: ```bytes_read <= buf.len().``` I didn't get it initially, that's why I was suggesting an additional peek.
- What about write? would ```bytes_written <= buf.len()``` work?
- I think we also need to reregister on succesfull TcpListener::accept();

What do you think about accept and write?

If it's OK with you, I'd rather work on it, seems also related to the try_clone issue, and it seems to me would benefit both issues.

**Comment by Thomasdezeeuw** [comment]
>     * What about write? would `bytes_written <= buf.len()` work?

I think/hope so, but I haven't tried.

>     * I think we also need to reregister on succesfull TcpListener::accept();

That would emulate level-triggers, but that isn't necessarily a bad thing. Let's hold off on this change, I'll do some experimentation as see what I can get to work.

**Comment by dtacalau** [comment]
@Thomasdezeeuw this is fixed per #1137 and #1127.

**Comment by Thomasdezeeuw** [comment]
Did we do `UdpSocket`?

**Comment by dtacalau** [comment]
> Did we do `UdpSocket`?

@Thomasdezeeuw udp not done, should be a simple change and test. Can I take care of UDP or do you want to do it?

**Comment by Thomasdezeeuw** [comment]
You can change it if you want.

**Comment by dtacalau** [comment]
> You can change it if you want.

@Thomasdezeeuw ok, I will implement the necessary changes and test them.

**Comment by dtacalau** [comment]
@carllerche @Thomasdezeeuw Which one of the tests below reflect best the way mio is intended to be used, first, second or both? The first test, ET_interests_reregister_by_wouldblock_call, rely on having an extra read which would return WouldBlock, then reregister the socket to reset the interests. The second test,  ET_interests_reregister_by_successful_call, doesn't use an extra read call, so needs to have reregister on successful call to pass. 

Looks like having reregister done on wouldblock is enough to emulate ET, if you have an extra read that would block.

I think the same discussion is valid for TCP. 

```
#[test]
fn ET_interests_reregister_by_wouldblock_call() {
    let (mut poll, mut events) = init_with_poll();

    let socket1 = UdpSocket::bind(any_local_address()).unwrap();
    let socket2 = UdpSocket::bind(any_local_address()).unwrap();
    
    let address2 = socket2.local_addr().unwrap();
    
    poll.registry()
        .register(&socket2, ID2, Interests::READABLE.add(Interests::WRITABLE))
        .expect("unable to register UDP socket");
    
    expect_events(
        &mut poll,
        &mut events,
        vec![
            ExpectEvent::new(ID2, Interests::WRITABLE),
        ],
    );

    {
        socket1.connect(address2).unwrap();

        let mut buf = [0; 20];
        checked_write!(socket1.send(DATA1));
        expect_events(
            &mut poll,
            &mut events,
            vec![ExpectEvent::new(ID2, Interests::READABLE)],
        );

        expect_read!(socket2.recv(&mut buf), DATA1);

        assert_would_block(socket2.recv(&mut buf));  <-----NOTE this would return wouldblock and do a reregister 
        checked_write!(socket1.send(DATA1));
        expect_events(
            &mut poll,
            &mut events,
            vec![ExpectEvent::new(ID2, Interests::READABLE)],
        );

        let mut buf = [0; 20];
        expect_read!(socket2.recv(&mut buf), DATA1);
    }
}
```

```
#[test]
fn ET_interests_reregister_by_successful_call() {
    let (mut poll, mut events) = init_with_poll();

    let socket1 = UdpSocket::bind(any_local_address()).unwrap();
    let socket2 = UdpSocket::bind(any_local_address()).unwrap();
    
    let address2 = socket2.local_addr().unwrap();
    
    poll.registry()
        .register(&socket2, ID2, Interests::READABLE.add(Interests::WRITABLE))
        .expect("unable to register UDP socket");
    
    expect_events(
        &mut poll,
        &mut events,
        vec![
            ExpectEvent::new(ID2, Interests::WRITABLE),
        ],
    );

    {
        socket1.connect(address2).unwrap();

        let mut buf = [0; 20];
        checked_write!(socket1.send(DATA1));
        expect_events(
            &mut poll,
            &mut events,
            vec![ExpectEvent::new(ID2, Interests::READABLE)],
        );

        expect_read!(socket2.recv(&mut buf), DATA1);   <-----NOTE there's no extra recv call below, no wouldblock, this recv needs to do a reregister 

        checked_write!(socket1.send(DATA1));
        expect_events(
            &mut poll,
            &mut events,
            vec![ExpectEvent::new(ID2, Interests::READABLE)],
        );

        let mut buf = [0; 20];
        expect_read!(socket2.recv(&mut buf), DATA1);
    }
}
```

**Comment by Thomasdezeeuw** [comment]
@dtacalau your examples are a little big, I assume the only change is dropping the `assert_would_block` call pointed out in the first example.

I think the first example is correct edge-trigger behaviour, that is reregistering once the readiness is drained (i.e. it returns would block). For `TcpStream`s the draining of readiness is also done with partial read/writes, i.e. a `read` not filling the entire buffer. For `UdpSocket`s I don't there is a way to check on read whether or not all packets are read in the queue, so the user should `recv` until they hit a would block error to receive more events.

**Comment by dtacalau** [comment]
> @dtacalau your examples are a little big, I assume the only change is dropping the 
> `assert_would_block` call pointed out in the first example.
 
@Thomasdezeeuw there are two differences between the examples:
1. 1st test has the extra `assert_would_block(recv)` call, so reregister is called on wouldblock
```
    pub fn recv(&self, buf: &mut [u8]) -> io::Result<usize> {
        try_io!(self, recv, buf)
    }
```

2. 2nd test also has UdpSocket modified to always reregister on successful call
```
    pub fn recv(&self, buf: &mut [u8]) -> io::Result<usize> {
        try_io!(self.recv(buf), |_| true)
    }
```

If the first example is the correct ET behaviour then we don't have to change anything for UDP to support ET because they already have reregister on wouldblock.

**Comment by dtacalau** [comment]
@Thomasdezeeuw In a discussion we had couple of days ago @carllerche summarized the mio ET guarantees: ``` The guarantee is that, after you get a WouldBlock, you will receive a readiness notification, so, you always have to perform the operation you care about, receive would block, then wait for the readiness event.```

What Carl said is also consistent with the first example. It also means we have to revert the changes done for TCP to reregister on  partial read/writes. The changes done did make the TCP stream tests pass, but, the TCP tests are not consistent with the MIO ET assumptions above.

So, even for TCP, we don't need to  reregister on partial of read/write, we need an extra read/write done before expect_events so that would trigger wouldblock and a new reregister.

Makes sense? If it does I can take care of fixing the tests and reverting the changes for TCP and UDP.

**Comment by carllerche** [comment]
It is not **incorrect** to reregister on partial reads / writes, just unnecessary to meet Mio's guarantees. Spurious notifications are permitted. That said, my guess is that it is better to re-register less, so i would wait until WouldBlock.

**Comment by dtacalau** [comment]
@carllerche maybe not incorrect but allowing both kinds of reregister, partial read/writes and WouldBlock creates confusion and may have unexepected consequences. 

In TCP case, if you reregister on partial read/writes, then reregister on WouldBlock would be extra uneeded op affecting performance. 

You may also have people reporting bugs because they expect events in the wrong place
Have a look at the two tests from my comment above https://github.com/tokio-rs/mio/issues/1131#issuecomment-559073004. This was the case for the UDP/TCP tests failures which led us to implemeting the partial read/write reregister.

**Comment by dtacalau** [comment]
https://github.com/tokio-rs/mio/pull/1175 for reverting reregistering on partial read/write for TCPStream

**Comment by Thomasdezeeuw** [comment]
Talking from a Unix perspective: edge triggers require the readiness to be drained. This means, again on Unix, to (for example) `read` until all bytes available are read. If no more bytes are available it will return a would block error. So you don't need to read until it hits a would block error, reading until it returns `< buf.len()` bytes is good enough.

But because this doesn't always works perfectly cross-platform, Mio always suggested to read until a would block error. So I don't intend on reverting the partial read/write for `TcpStream`, since they behaviour more closely matches Unix. But it's not guaranteed by Mio.

**Comment by dtacalau** [comment]
> But because this doesn't always works perfectly cross-platform, Mio always suggested to read until > a would block error. So I don't intend on reverting the partial read/write for `TcpStream`, since they > behaviour more closely matches Unix. But it's not guaranteed by Mio.

@Thomasdezeeuw Here's my reasoning for proposing the revert. People will see the mio guarantee ``` you get a WouldBlock, you will receive a readiness notification``` and write their apps accordingly. Taking read for example, you'll always have
read returns < buf.len() before WouldBlock. This means, an app using mio which tries to follow mio guarantee we'll have reregister called twice, one time for read return < buf.len(), and another time for read returing WouldBlock.

If we keep the partial read/write reregistering, how do we prevent the situation described above? Wouldn't be a problem having reregister done twice? Also it's not consistent with what we're doing for UDPSocket which relies on WouldBlock.

**Comment by dtacalau** [comment]
@Thomasdezeeuw what's your opinion on https://github.com/tokio-rs/mio/issues/1131#issuecomment-559543879 ?

**Comment by Thomasdezeeuw** [comment]
I agree with the double re-registering. We should merge #1175.

**Comment by Thomasdezeeuw** [comment]
Now that #1175 is merged I think this is resolved.
