### ISSUE TITLE
Usage of Intra Rustdoc Links

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1136]
In https://github.com/tokio-rs/mio/pull/1132 I tried using Intra Rustdoc links and found out that it's currently a nightly only feature. In the future we want to use the feature, but for now we need to ensure that the docs build correctly on docs.rs before v0.7 is released.

Currently a mix of old (regular) links and intra doc links are used.

Intra doc link allow use to link to type, e.g. ```[`Token`]: Token``` would link \`Token\` to the `Token` struct. This also checks if all links are valid when creating the docs.

Tracking issue: https://github.com/rust-lang/rust/issues/43466.

**Comment by Thomasdezeeuw** [comment]
Pr #1224 removed all intra rustdoc links for the 0.7-alpha1 release. I'm changing this to the v1 milestone, hopefully by that time we can use intra rustdocs links on stable.

**Comment by hawkw** [comment]
>  In the future we want to use the feature, but for now we need to ensure that the docs build correctly on docs.rs

FWIW, docs.rs builds crates on nightly by default.

**Comment by Thomasdezeeuw** [comment]
> FWIW, docs.rs builds crates on nightly by default.

Didn't know that, then we can switch back for the v0.7 release.

**Comment by hawkw** [comment]
Yeah, this is also why we are able to use the `doc_cfg` nightly feature on docs.rs.

**Comment by Thomasdezeeuw** [comment]
This is now available on stable Rust.
