### ISSUE TITLE
Investige peek failure on Windows

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1148]
Surfaced in https://github.com/tokio-rs/mio/pull/1137. Only log available:

```log
test peek ... test peek has been running for over 60 seconds
```

**Comment by Thomasdezeeuw** [comment]
@dtacalau do you have time to look into this?

**Comment by dtacalau** [comment]
@Thomasdezeeuw , of cpurse, please assign this issue to me.

**Comment by dtacalau** [comment]
@Thomasdezeeuw can't reproduce this issue on my machine anymore, peek test is always successful. I don't know what has changed. I even rebooted my machine couple of times and retested but w/o success.

Here's how I've tried to reproduce it:
- fetch your branch Thomasdezeeuw/win-tcpstream, enable peek test, run test -> does not reproduce;
- cherry-pick the commit from your branch to latest master -> does not reproduce;
- cherry-pick the commit to an older master where it reproduced two days ago -> does not reproduce;

Any idea what else I can try? Maybe get access to CI machine and debug it there?

**Comment by dtacalau** [comment]
Interesting read https://support.microsoft.com/en-us/help/192599/info-avoid-data-peeking-in-winsock

**Comment by dtacalau** [comment]
@Thomasdezeeuw, since I cant reproduce this localy, next stepwould be for me to add couple of println!, run the test again on CI, and see where it blocks. Could we change the settings and have the CI run tests with " --nocapture     don't capture stdout/stderr of each task, allow printing directly"?

**Comment by Thomasdezeeuw** [comment]
I think you can add `-- --nocapture` to the end of https://github.com/tokio-rs/mio/blob/ff1b9f27ee53f9b86aff4ba11f513b54913bfbe6/ci/azure-test-stable.yml#L29, then it will work on the CI.

**Comment by dtacalau** [comment]
@Thomasdezeeuw ok, will try that, thanks!

**Comment by dtacalau** [comment]
@Thomasdezeeuw 
Doesn't seem to reproduce on CI anymore, have a look at PR #1156. I've tried with "--nocapture" enabled and without it, in both cases peek test works fine. 

Could you trigger another CI build/test on your branch, to see what happens?

**Comment by Thomasdezeeuw** [comment]
Haven't been able to reproduce this, seems like a fluke. Closing.
