### ISSUE TITLE
Update documentation for `TcpStream::connect_stream`

### ISSUE THREAD

**Issue by khionu** [tokio-rs/mio#1157]
[Currently, the docs](https://docs.rs/mio/0.6.19/mio/net/struct.TcpStream.html#method.connect_stream) reflect older API.

**Comment by Thomasdezeeuw** [comment]
@khionu would you like to contribute a change?

**Comment by khionu** [comment]
If I understood the semantics of the difference between the docs and how the code behaves now, I would, but I'd have to guess. I'm just barely learning mio for the first time.

**Comment by Thomasdezeeuw** [comment]
In 0.7 this method is removed so I move it the the 0.6 milestone.

**Comment by Thomasdezeeuw** [comment]
Closing this due to age.
