### ISSUE TITLE
Add a way to wake up a poll manually OR wake up poll when interests changed in the registry

### ISSUE THREAD

**Issue by stevenroose** [tokio-rs/mio#1158]
Consider the situation where you have a TcpStream and a queue of messages to be written. You start with a Poll where you're only interested in READABLE events, because there is nothing to be written. Now, once you have a message to send, you want to write it on the stream. Imagine that you want a single thread, the one using the Poll, to do both the reading and writing.

Right after adding a message to the queue, you can reregister the tcpstream with the registry from another source to be interested in both READABLE and WRITABLE events. However, (AFAIK) this change will only take effect once the poll expired and the thread polls again.

It would be great to either be able to manually wake up the poll (f.e. when the thread is supposed to shut down), or for the poll to be woken up when one of the registrations change.

**Comment by Thomasdezeeuw** [comment]
Do you mean the `Waker` type?

**Comment by stevenroose** [comment]
Ah cool! Exactly what I needed! I tried implementing `Source` myself at some point, but it relies on epoll signals so it's not possible. Thanks!

**Comment by Thomasdezeeuw** [comment]
@stevenroose `AsRawFd` is implemented for `Poll` (https://github.com/tokio-rs/mio/blob/7a073b62e5a4609ba491e63a4b25d0f1ef65d3ce/src/poll.rs#L382-L387). So you can get access to the underlying file descriptor of `epoll`.
