### ISSUE TITLE
DOC BUG + no way to inspect the number of events returned by Poll

### ISSUE THREAD

**Issue by stevenroose** [tokio-rs/mio#1159]
The doc on `Poll::poll` says:
```
`poll` returns the number of readiness events that have been pushed into
`events` 
```
This is no longer the case as `Poll::poll` returns a `Result<()>` now.

Also, `Events` doesn't have a `len` or `size` inspector, so it's impossible to know the number of events without counting the number of items iterated.

**Comment by Thomasdezeeuw** [comment]
You're right the doc needs to be updated. Code here: https://github.com/tokio-rs/mio/blob/ac0515cc9519f228d39bb0d9055955faf7f75f34/src/poll.rs#L290-L295

**Comment by Thomasdezeeuw** [comment]
As for actually getting the number of events; it was decided against adding `ExactSizeIterator` in #1023.

**Comment by stevenroose** [comment]
@Thomasdezeeuw How about an `is_empty`? That at least allows callers to suspect if the poll ended because of a timeout instead of because of an event.

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw How about an `is_empty`? That at least allows callers to suspect if the poll ended because of a timeout instead of because of an event.

Seems reasonable: https://github.com/tokio-rs/mio/blob/7a073b62e5a4609ba491e63a4b25d0f1ef65d3ce/src/event/events.rs#L108-L120 :)

**Comment by Thomasdezeeuw** [comment]
@stevenroose is the `Event::is_empty` good enough for you? Can this issue be closed?

**Comment by Thomasdezeeuw** [comment]
Closing as resolved, @stevenroose if this is not the case please let me know.

**Comment by stevenroose** [comment]
Sorry, I missed the e-mail. This is indeed perfect for me, thanks.
