### ISSUE TITLE
Performance when polling stdin (especially macOS)

### ISSUE THREAD

**Issue by zrzka** [tokio-rs/mio#1171]
In the `crossterm` crate, we have completely rewritten input event processing and switched to the `mio` (0.6) for polling. We're experiencing some performance issues when polling STDIN in raw mode.

`crossterm` can be used as the `cursive` crate backend. We have to implement couple of `Backend` trait methods, but the problematic one is `poll_event`:

```rust
    /// Polls the backend for any input.
    ///
    /// Should return immediately.
    fn poll_event(&mut self) -> Option<Event>;
```

`Event` here is not `mio`'s `Event`, it's something like `Event::Key(code, modifiers)`, `Event::Mouse(...)`, etc. We poll with zero timeout to check if there's anything to read to follow the _Should return immediately_ requirement.

This works nicely when someone is just typing. When you paste anything big, the performance isn't very good and is platform dependent (this is expected), but the number of "nothing to read" is quite high. See below.

## Environment

* macOS 10.15.1 / Ubuntu 18.04.3 LTS
* Rust 1.39.0
* mio 0.6.20 / upcoming mio-0.7 (master branch)

## How to reproduce

* Clone https://github.com/zrzka/crossterm-mio-mcve
* `cd crossterm-mio-mcve`
* `cargo build --release`
* `cat ./test.txt | pbcopy` on macOS
  * or `cat test.txt | xclip -i -selection clipboard` on Linux
* `cargo run --release`
* `Cmd V` to paste `test.txt` file content in the terminal

`master` branch works with `mio` 0.6.20. There's also [`mio-0.7`](https://github.com/zrzka/crossterm-mio-mcve/tree/mio-0.7) branch to test it with the upcoming 0.7. (no difference)

## Linux output

```sh
zrzka@ubuntu:~/Projects/crossterm-rs/crossterm-mio$ cargo run --release
    Finished release [optimized] target(s) in 1.09s
     Running `target/release/crossterm-mio`
Paste something big, if ! is found, it quits...
Poll call: 125274 STDIN event count: 10870 Bytes read: 10836506 Time: 4.564543533s
zrzka@ubuntu:~/Projects/crossterm-rs/crossterm-mio$
```

### Copy & paste

```sh
➜  crossterm-mio git:(master) cargo run --release
    Finished release [optimized] target(s) in 0.03s
     Running `target/release/crossterm-mio`
Paste something big, if ! is found, it quits...
Poll call: 9467361 STDIN event count: 14111 Bytes read: 10836506 Time: 156.857614386s
```

### socat

```sh
➜  crossterm-mio git:(master) socat -s -b4096 -u OPEN:./test.txt,ignoreeof EXEC:'cargo run --release',pty,setsid,ctty
    Finished release [optimized] target(s) in 0.15s
     Running `target/release/crossterm-mio`
Paste something big, if ! is found, it quits...
Poll call: 14002 STDIN event count: 13207 Bytes read: 10836506 Time: 1.790947581s
➜  crossterm-mio git:(master)
```

## Comparison

| Platform | Poll call<sup>1</sup> | Misses<sup>2<sup> | STDIN events | Time |
| :-- | --: | --: | --: | --: |
| Linux & paste | `125_274` | `114_404 (91%)` | `10_870` | `4.56s` |
| macOS & paste | `9_467_361` | `9_453_250 (99%)` | `14_111` | `156.85s` |
| macOS & `socat` | `14_002` | `795 (06%)`  | `13_207` | `1.79s` |

<sup>1</sup> - total number of `poll` calls
<sup>2</sup> - number of `poll` calls saying "nothing to read"

What bothers me is the quite high ratio of misses when something big is pasted (> 90%) and the processing time on macOS (156s) vs Linux (5s).

## Possible workarounds

We have two options now:

* Spawn a thread, use blocking read and send `Event` via channel and use `try_recv()` on the `cursive` side. Not something very nice, because when you quit the app, there's a possibility that another `Event` is consumed (it shouldn't be) and we'd like to avoid another thread.
* Use small timeout (like `1ms`) in the `poll` call. This violates _Should return immediately_ `cursive` requirement and it's almost impossible to define proper multi platform timeout to lower number of "misses" for every computer configuration, OS, ...
  * Also the timeout must not be very high, because when you start moving your mouse with pressed button, the number of processed events goes up and user can experience it as slow reactions

Here's the comparison what happens when we call `poll` with non zero timeout:

| Timeout | macOS "misses" | Linux "misses" |
| --: | --: | --: |
| 0ms | 99% | 91% |
| 1ms | 89% | 0.5% |
| 2ms | 80% | x |
| 3ms | 73% | x |
| 4ms | 66% | x |
| 10ms | 34% | x |
| 30ms | 0% | x |

x - didn't measure it, the number is too small that it doesn't make sense

## Questions

* Is this high number of "misses" (nothing to read) normal/expected behaviour when I paste something big in the terminal?
* Is expected that macOS is slower in order of magnitude when compared to the Linux for example?

I started debugging/profiling this performance issue yesterday and ended up here so far. Will continue to check what's going on on the system level. It can be just STDIN issue on macOS and there's nothing we can do about it. But don't know yet, just collected these notes so far and shared here, because it can ring a bell for someone ...

P.S. I'm not saying that it's the `mio` crate issue, I think that the STDIN is just too slow. I'm just wondering why the numbers are so different, if there's anything we can do to "synchronize" behaviour on different platforms, ...

**Comment by Thomasdezeeuw** [comment]
I don't have too much time to look into this week. I did want to leave a note saying that macOS' stdin/stdout has more buffering then Linux. If I remember correctly it only flushes when reaching a new line (`\n`), but this might only be for stdout.

Since the lines in `test.txt` are quite long maybe that is the cause of the performance issue?

**Comment by zrzka** [comment]
I tried to fold the `test.txt` with `fold -w 40 test.txt > test2.txt` and there's no difference.

Unfolded:

```
Poll call: 9467361 STDIN event count: 14111 Bytes read: 10836506 Time: 156.857614386s
```

Folded (40 chars/row):

```
Poll call: 10118942 STDIN event count: 14449 Bytes read: 11096678 Time: 159.176586078s
```

Also tried to play with `c_cc[VMIN]` & `c_cc[VTIME]` values and no difference.

**Comment by Thomasdezeeuw** [comment]
Would it be possible to use edge triggers (`PollOpt::edge()`)? Maybe that might reduce the number of "misses". It would require stdin to be read until it hits a would block error, I don't know if that is possible with your trait design.

**Comment by zrzka** [comment]
Tried `edge` and there's no difference. One important fact I missed - it's in the RAW mode (`libc::cfmakeraw`). The documentation says that it's a byte-to-byte processing. `libc::read` reads `1022`/`7xx` (`xx` don't remember exact number, depends on the platform). It's clearly not byte-to-byte processing and it probably means something else.

It looks like that there's some kind of buffer somewhere for the RAW mode and `mio` says nothing to read too often, because the buffer is being filled and the underlying system reports nothing to read as well until the buffer is filled? Just guessing here as I didn't have time to trace the system yet.

**Comment by Thomasdezeeuw** [comment]
@zrzka any update on this? I see crossterm switched over to Mio v0.7.

**Comment by Thomasdezeeuw** [comment]
I don't know if Mio can do much here. It's really up to macOS to fix the performance issues.
