### ISSUE TITLE
Investigate and document UDP recv/peek(_from) behavior on *nix when using a smaller buffer.

### ISSUE THREAD

**Issue by dtacalau** [tokio-rs/mio#1174]
On Windows, if the data is larger than the buffer specified, the buffer is filled with the first part of the data, and recv/peek(_from) returns the error WSAEMSGSIZE(10040). The excess data is lost. 

What does *nix do?

Ref PR https://github.com/tokio-rs/mio/pull/1167/files#diff-c022871452a328dc8c9cd10130eb1572R233

**Comment by andrewtj** [comment]
In case you haven't seen it rust-lang/rust#55794 concerns the different behaviour of Windows and *nix. For my $0.02, it'd be better to make both platforms behave the same, probably by returning an error on truncation.

**Comment by Thomasdezeeuw** [comment]
Pr #1167 adds documentation to explain the difference in behaviour. And once https://github.com/rust-lang/rust/issues/55794 is resolved we'll follow that approach. So I'm punting this to v1.

**Comment by Thomasdezeeuw** [comment]
This would be solved if we switch to socket2 (tracked in #1381) which has a struct `RecvFlags` to aid in this.

**Comment by Thomasdezeeuw** [comment]
This might depend on https://github.com/rust-lang/socket2/issues/188.
