### ISSUE TITLE
Document interaction with RawSocket (do not read / write directly)

### ISSUE THREAD

**Issue by dtacalau** [tokio-rs/mio#1186]
We need to tell users what they are allowed to do when getting the handle of a TcpListener/TcpStream/UdpSocket through as_raw_handle/as_raw_socket on Windows.

Target: v1.0-release

**Comment by Thomasdezeeuw** [comment]
The same holds true for Unix, e.g. on Solaris we also need to re-register (see https://github.com/tokio-rs/mio/issues/1152#issuecomment-559115621).
