### ISSUE TITLE
Add a SourceFd (EventedFd) equivalent for Windows

### ISSUE THREAD

**Issue by dtacalau** [tokio-rs/mio#1187]
Target v1.0-release

**Comment by Thomasdezeeuw** [comment]
This is also tracked in https://github.com/tokio-rs/mio/issues/880.

**Comment by Thomasdezeeuw** [comment]
And I have/had a pr in https://github.com/tokio-rs/mio/pull/1183.

**Comment by dtacalau** [comment]
> This is also tracked in #880.

@Thomasdezeeuw will keep this one too as it is more clear, #880 discussion is too long alreadt.

**Comment by Thomasdezeeuw** [comment]
I don't think this is possible based on the current implementation.
