### ISSUE TITLE
mio should not panic when afd poll return error

### ISSUE THREAD

**Issue by dtacalau** [tokio-rs/mio#1191]
Currently when Afd.poll `NtDeviceIoControlFile` returns any error code other than `ERROR_IO_PENDING` and `ERROR_INVALID_HANDLE` mio just panics. I think it would be better to handle all error codes and pass the decision on how to handle the error to the mio user. 

For instance, let's say a user polls a TcpListener, when Afd.poll return any error code then the two codes above, do not panic, but save the error code in the listener SockState, also do not re-add the SockState to the update queue. TcpListener should provide the mio user a method to retrieve the last error. When getting the error user could choose to deregister the socket, or take other actions.

**Comment by Thomasdezeeuw** [comment]
Could you point to the panic?

**Comment by dtacalau** [comment]
> Could you point to the panic?

@Thomasdezeeuw https://github.com/tokio-rs/mio/blob/0a55a121f0a2646376e062a2ecbbdf3f03902598/src/sys/windows/selector.rs#L565

**Comment by Thomasdezeeuw** [comment]
We should go through all the `unwrap` in the Windows implementation make sure the all make sense and see if we can handle them more gracefully.

**Comment by dtacalau** [comment]
@Thomasdezeeuw good idea, I've opened #1198 to not forget about this, though I'd push this check after the custom polling implementation.

**Comment by dtacalau** [comment]
@Thomasdezeeuw please assign this to me, thanks!

**Comment by carllerche** [comment]
@piscisaureus Do you know what the error cases are?

**Comment by carllerche** [comment]
According to @piscisaureus, there are no error cases that can be handled. We should include a panic w/ an error message and worry about it when we have a bug report.

**Comment by Thomasdezeeuw** [comment]
@piscisaureus @carllerche  is it like `close`, where even though you can't handle the error, you shouldn't retry the operation because you don't know if the file descriptor is closed or not?

**Comment by Thomasdezeeuw** [comment]
Punting this to v0.7 (not alpha 1).

**Comment by Thomasdezeeuw** [comment]
Fixed by #1215.
