### ISSUE TITLE
Yank version with "0.*" deps

### ISSUE THREAD

**Issue by kornelski** [tokio-rs/mio#1197]
An old version of `mio` has dependencies specified with `"0.*"` version requirement (`nix = "0.*"`).

Crates with such vague dependency versions became unusable, because `0.*` allows picking too-new semver-incompatible dependencies, and may break with Cargo's `minimal-versions` feature.

I suggest yanking it:

```bash
cargo yank --vers 0.1.0
```

**Comment by Thomasdezeeuw** [comment]
This should be fixed in v0.6 and v0.7, so I'm closing this.
