### ISSUE TITLE
[Question] How to split TcpStream for parallel Send/Recv wrappers?

### ISSUE THREAD

**Issue by khionu** [tokio-rs/mio#1199]
I've switched to Master for my work now, and I can't see a way that this is possible anymore. A stream can't have two object handles, yet you need mutable access to read OR write. I'd have to use unsafe to avoid a Mutex, and that would rely on internals being safe to use it this way. My crate could use an abstraction that has the ownership of the TcpStream inside my wrapper of Poll, but that would be specialized behaviour that I don't need for other Evented objects.

**Comment by Thomasdezeeuw** [comment]
With send/recv to do mean `io::Read` and `io::Write`? Because those trait are implemented for `&TcpStream`, see https://github.com/tokio-rs/mio/blob/6d5550a8c1dc30ffe81ce04d3f2b599cf7e36fe1/src/net/tcp/stream.rs#L203-L211. So you can just use `Arc<TcpStream>` and safely read from one and write to the other.

**Comment by khionu** [comment]
My point is that I cannot have **parallel** Read/Write, something TCP allows. The functions themselves take a mutable reference, they cannot be ran at the same time on separate threads, Rust's ownership model won't allow it, without `unsafe`.

**Comment by Thomasdezeeuw** [comment]
@khionu here is a working version using `net::TcpStream`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fcf94fa1b69014723fafae715cf90254. It should work the same for Mio.

**Comment by khionu** [comment]
Ahh.... I see my problem. I missed the semantic that Write is implemented for `&TcpStream`, not just `TcpStream`.
