### ISSUE TITLE
on macos reregister and deregister return ok if the event source has not  been previously registered

### ISSUE THREAD

**Issue by dtacalau** [tokio-rs/mio#1202]
According to reregister docs:
```
    /// The event source must have previously been registered with this instance
    /// of `Poll` otherwise the call to `reregister` will return with an error.
```

I noticed this issue when testing #1201. Macos does not follow doc constraints for reregister and deregister. The following tests fail only on macos:

running 14 tests
test is_send_and_sync ... ok
test drop_cancels_interest_and_shuts_down ... ok
test poll_erroneous_registration ... ok
test poll_registration ... ok
test register_deregister_multiple_poll_instances ... ok
test register_reregister_token_usage ... ok
test registry_behind_arc ... ok
test poll_closes_fd ... ok
test reregister_without_register ... FAILED
test add_then_drop ... ok
test reregister_overrides_interest ... ok
test zero_duration_polls_events ... ok
test deregister_without_register ... FAILED
test run_once_with_nothing ... ok

failures:

---- reregister_without_register stdout ----
thread 'reregister_without_register' panicked at 'called `Result::unwrap_err()` on an `Ok` value: ()', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- deregister_without_register stdout ----
thread 'deregister_without_register' panicked at 'called `Result::unwrap_err()` on an `Ok` value: ()', src/libcore/result.rs:1165:5

failures:
    deregister_without_register
    reregister_without_register

test result: FAILED. 12 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test poll'

**Comment by Thomasdezeeuw** [comment]
`kqueue(2)` is nice this way, but Mio (well our Windows implementation mostly) follows this more strictly. So when building cross-platform software the documentation is correct, but on `kqueue` platforms its just more lenient. I don't consider this a problem really.

**Comment by dtacalau** [comment]
>  I don't consider this a problem really.

@Thomasdezeeuw The problem is this platform dependant behavior is not documented in reregister/deregister doc. I'm fine with just documenting this. WDYT?

**Comment by Thomasdezeeuw** [comment]
There are many undocumented platform differences, I don't think we can documentation all. I think we should focus on documentation the way Mio can be used in a (more or less) cross-platforms manner. That is why the documentation currently is written the way it is.

**Comment by dtacalau** [comment]
> There are many undocumented platform differences, I don't think we can documentation all. 

@Thomasdezeeuw agree, you can't doc everything. But, we can doc whatever differences we find, especially in cases like this one, when mio does not behave as it is documented. 

I'll take care of these two issues.

**Comment by Thomasdezeeuw** [comment]
I don't know. I feel like it would only confuse the reader if we add docs about edge cases we don't officially support. I think we should stick to "this works in Mio, other uses are not support". If we document every difference in all the platforms the documentation will have too much information that is not really useful when using Mio, imo. @carllerche what do you think?

**Comment by carllerche** [comment]
We can update the docs to state that the behavior is undefined if `register` is not called first.

**Comment by dtacalau** [comment]
> We can update the docs to state that the behavior is undefined if `register` is not called first.

@carllerche, @Thomasdezeeuw  ok with saying undefined in doc.  I'd still keep the tests for such edge cases on platforms where they make sense. For instance deregister and reregister w/o a prev register must return error on Windows, otherwise it is a bug. 

Another reason, edge cases are good sources of bugs, if we break something, an edge case test should break first.
