### ISSUE TITLE
(re)register should not allow re-using the same token for different event sources

### ISSUE THREAD

**Issue by dtacalau** [tokio-rs/mio#1204]
This was noticed this issue when testing #1201.  The following test should fail when trying to register listener2 using the same token, ID1, because the token has already been used when registering listener1. 

If using the same token for different event sources, you won't be able to tell for which event source you have received the events later on.

```
#[test]
fn register_reregister_token_usage() {
    let poll = Poll::new().expect("unable to create Poll instance");

    let mut listener1 = TcpListener::bind(any_local_address()).unwrap();
    let mut listener2 = TcpListener::bind(any_local_address()).unwrap();

    poll.registry()
        .register(&mut listener1, ID1, Interest::READABLE)
        .expect("unable to register listener");

    poll.registry()
        .register(&mut listener2, ID1, Interest::READABLE)
        .expect("unable to register listener");
```

**Comment by Thomasdezeeuw** [comment]
> This was noticed this issue when testing #1201. The following test should fail when trying to register listener2 using the same token, ID1, because the token has already been used when registering listener1.

Why shouldn't Mio allow this? I use this to map two I/O types to the same future.

> If using the same token for different event sources, you won't be able to tell for which event source you have received the events later on.

This is really the user problem, not Mio's.

I don't want to add any overhead to Mio for this. It is up to the user to pick a useful `Token`, if that includes using the same `Token` for different I/O source we should allow it.

**Comment by dtacalau** [comment]
@Thomasdezeeuw Not really a problem, to me it seemed logic to use different tokens for different sources. But if it's a design choice to allow them, I don't have a problem. We just need to document it, to be clear on it.

As for benefits, here a situation when it would be beneficial to not allow same tokens:
`Let's say a user uses two different sources and registers them both with the same token. The first source is a stable implementation and works fine, while the second source is newer, less stable, maybe buggy for the user setup (with user setup the second source does not always trigger events when it should be) The user won't realise second source issues because it will always get events coming from the first source.`

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw Not really a problem, to me it seemed logic to use different tokens for different sources. But if it's a design choice to allow them, I don't have a problem. We just need to document it, to be clear on it.

This depends on what we do in https://github.com/tokio-rs/mio/issues/788. Currently `Token` is effectively opaque to Mio.

> As for benefits, here a situation when it would be beneficial to not allow same tokens:
> `Let's say a user uses two different sources and registers them both with the same token. The first source is a stable implementation and works fine, while the second source is newer, less stable, maybe buggy for the user setup (with user setup the second source does not always trigger events when it should be) The user won't realise second source issues because it will always get events coming from the first source.`

This is really a problem created by the user and imo not for Mio to solve.

**Comment by kleimkuhler** [comment]
Agree with @Thomasdezeeuw on this but thanks for opening the discussion! I think this can be closed.
