### ISSUE TITLE
Test feature flag combinations in CI

### ISSUE THREAD

**Issue by kleimkuhler** [tokio-rs/mio#1214]
## Motivation

Once #1192 merges, Mio will have several feature flags that can be used in different combinations of each other. CI should test that the combinations are correct. Currently, it would just test `--all-features`.

## Solutions

1. I've been using [cargo-hack](https://github.com/taiki-e/cargo-hack)'s `--feature-powerset`. **Cons**: It's a little expensive to run right now because it mixes in `guide` doubling the number of combinations that needs to be tested. CI could download cargo hack and run it in place of `cargo check` steps.

2. Explicitly test the combinations we care about. **Cons**: A combination could be missed, and it would need to be updated as features are added (probably not that often..)

**Comment by Thomasdezeeuw** [comment]
Little script to run the current combos locally:

```bash
#!/bin/bash

set -eu

declare -a feature_matrix=(
	"" # None.
	os-poll
	os-poll,os-util
	os-poll,os-util,tcp
	os-poll,os-util,tcp,udp
	os-poll,os-util,tcp,udp,uds
	os-util
	os-util,tcp
	os-util,tcp,udp
	os-util,tcp,udp,uds
	tcp
	tcp,udp
	tcp,udp,uds
	udp
	udp,uds
	uds
	guide
)

for features in "${feature_matrix[@]}"; do
	cargo check --features "$features"
done
```
