### ISSUE TITLE
What features to enable by default

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1216]
Now that #1192 is merged Mio mostly panics by default for new users. This is not the most pleasant user experience. So we have to decide what we want to do, I see two possible choices:

* Put the burden of adding the correct features on the end users.
* Put the burden of disabling default features on library maintainers.

/cc @kleimkuhler @carllerche

**Comment by carllerche** [comment]
Tokio opted to disable by default and provides a “full” feature. Requiring lib authors to opt out has not proven to work well. 

IMO mio is lower level than tokio, so it doesn’t really need a “full” feature. 

In theory, there should be no panics, only compile fail.

**Comment by kleimkuhler** [comment]
I think putting the burden of adding the correct features on the end users is okay for Mio. I think the current features are straightforward for deciding what to include and exclude.

I could see a `full` flag (possibly as default) being used incorrectly (providing unused functionality) more often than as a convenience.

**Comment by Thomasdezeeuw** [comment]
I'm OK with not enabling any features by default.

Then this can be closed.
