### ISSUE TITLE
regression test issue_1205 hangs on all Linux CI

### ISSUE THREAD

**Issue by dtacalau** [tokio-rs/mio#1226]
https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=4073&view=logs&j=95c0de06-86ba-5b83-6acc-e8fdf9d57564&t=804b0c6d-d844-5f90-18fc-e53e483bd33c

![Screenshot_1](https://user-images.githubusercontent.com/2316254/70918515-d1915f00-2027-11ea-87af-bc8c64d68216.jpg)

**Comment by Thomasdezeeuw** [comment]
So the only log is that its running for longer then 60 seconds?

**Comment by dtacalau** [comment]
> So the only log is that its running for longer then 60 seconds?

@Thomasdezeeuw Yes, and the fact that it hanged on all Linux CIs during the same run.

**Comment by Thomasdezeeuw** [comment]
See https://github.com/tokio-rs/mio/pull/1231#discussion_r359766938, my change was invalid.
