### ISSUE TITLE
TcpStream bind before connect

### ISSUE THREAD

**Issue by zonyitoo** [tokio-rs/mio#1257]
Ref: https://github.com/tokio-rs/tokio/issues/1543

There is no way to call `bind()` before `connect()` when creating `TcpStream`. This is a very common method to tell operating system to connect the target address with a specific local address (mostly for using a specific network interface).

Proposal, adding a static method for `TcpStream`:

```rust
fn bind_connect(bind_addr: &SocketAddr, target_addr: &SocketAddr) -> io::Result<TcpStream> {
    // ...
}
```

Other candicate names:

1. `connect_with`
2. `connect_from`
3. `connect_by`

I could send a PR for this, if it is Ok.

**Comment by Thomasdezeeuw** [comment]
It comes up every once in a while that a non-libstd method is needed on one of the net types. For now I think we should not add them ad-hoc and create more “whole” solution, one that would satisfy (almost) all of these requests. Such a solution is being discussed in #1213. So I don’t think a pr to add such a method would be accepted now.

To accomplish this now you can use the net2 or socket crate to create a TcpStream yourself and then call FromRaw(Fd, Socket) or TcpStream::from_std.

**Comment by zonyitoo** [comment]
> To accomplish this now you can use the net2 or socket crate to create a TcpStream yourself and then call FromRaw(Fd, Socket) or TcpStream::from_std.

This is what I am doing now. 

But `net2` haven't update for 2 years... I have found `socket2` as replacement.

**Comment by Thomasdezeeuw** [comment]
I don't know exactly what is going on with `net2`, `socket2` seems its replacement. I also see I linked to the wrong issue, its #1211.

**Comment by polachok** [comment]
It seems like net2 [is deprecated](https://github.com/rust-lang-nursery/net2-rs/issues/91)

**Comment by zonyitoo** [comment]
Since tokio have provided `TcpSocket`, which actually solves my problem. Closing this issue.
