### ISSUE TITLE
mio 0.7 schedule

### ISSUE THREAD

**Issue by Keruspe** [tokio-rs/mio#1275]
Hi,

What is the plan regarding mio 0.7?
Do you have any time frame in mind?
Will there be more preview releases? (It seems there have been important changes since alpha 1)

This issue is not intended as a "please rush this, we need this yesrerday" rant, I'm just trying to get a better global view of were we stand in the way from 0.6 to 0.7 to try and anticipate this release in other projects without rushing on something that isn't quite ready yet.

**Comment by Thomasdezeeuw** [comment]
I don't think we had any API changes, mostly internal refactors that should be fine with regards to stability.

@carllerche what do you think? Another alpha release or just release 0.7?

**Comment by Thomasdezeeuw** [comment]
@Keruspe v0.7 is almost here: #1279.

**Comment by Thomasdezeeuw** [comment]
Version v0.7 has been released.
