### ISSUE TITLE
v0.7 is broken on Windows?

### ISSUE THREAD

**Issue by cg31** [tokio-rs/mio#1284]
It seems the tcp_server example can only accept one client.

Reproduce steps:

1 compile and run the tcp_server example:
https://github.com/tokio-rs/mio/blob/master/examples/tcp_server.rs

2 compile the connect example in tokio:
https://github.com/tokio-rs/tokio/blob/master/examples/connect.rs

3 run connect.exe twice

result: only the connecttion from first connect.exe is accecpted.

If the tcp_server is ported back to v0.6.0, there is no such problem.

**Comment by Thomasdezeeuw** [comment]
That because the example isn't port to v0.7, it needs a loop around `accept` here: https://github.com/tokio-rs/mio/blob/fefbd790be734ce2313c3dc51878973956bc325d/examples/tcp_server.rs#L49-L59. I'll send a pr to fix it.

**Comment by cg31** [comment]
@Thomasdezeeuw, I forgot to mention...

I used the the example from master branch. And master branch mio is the same as v0.7.0.

**Comment by gdf8gdn8** [comment]
On MacOS and Linux the example works.

**Comment by Thomasdezeeuw** [comment]
@gdf8gdn8 likely because macOS and Linux create multiple events, while Windows might coalesce them. #1285 should fix the issue, can you try that branch @cg31?

**Comment by gdf8gdn8** [comment]
@Thomasdezeeuw it's working.

**Comment by cg31** [comment]
It works indeed!

**Comment by Thomasdezeeuw** [comment]
Fixed in #1285.
