### ISSUE TITLE
How to deal with TCP packet splitting and sticking when I use Mio ？

### ISSUE THREAD

**Issue by guoxiang666** [tokio-rs/mio#1288]
How to deal with TCP packet splitting and sticking when I use Mio ？
Wating for your answer, thanks!

**Comment by Thomasdezeeuw** [comment]
We don't really provide an API that deals with individual packets. Using the `io::Read` trait you can read all bytes currently queued for a connection, the OS will handle the packets for us.

**Comment by yuguorui** [comment]
You may need an userspace TCP/IP stack to decode/assemble splited packets, such as [smoltcp](https://github.com/m-labs/smoltcp.git).

2333😀

**Comment by guoxiang666** [comment]
> We don't really provide an API that deals with individual packets. Using the `io::Read` trait you can read all bytes currently queued for a connection, the OS will handle the packets for us.

Thanks
