### ISSUE TITLE
Implementing timers via Waker?

### ISSUE THREAD

**Issue by jgallagher** [tokio-rs/mio#1289]
Apologies if this should've been attached to #907 instead; the post-close discussion there is exactly the same as what this issue refers to, but isn't quite the same as the stated goal of #907 (removing `Registration` and `SetReadiness`) - this feels like more of a followup API question.

I was trying to update a crate of mine today from mio 0.6 to 0.7, and that went relatively smoothly for my direct use of mio (thanks for all the good docs!). However, I use the timer from mio-extras, which is still built on 0.6. I opened an issue there (dimbleby/mio-extras#7) asking about support for mio 0.7, but then looked at it more closely and it appears correctly implementing a timer via `Waker` may be difficult because of this bit from the `Waker` docs:

> Only a single Waker should active per Poll, if multiple threads need access to the Waker it can be shared via for example an Arc. What happens if multiple Wakers are registered with the same Poll is undefined.

The natural way to port `mio-extra`'s Timer is, I think, to have `Timer::register` construct a `Waker` to use with the associated `Registry`. But how should it respect the above requirement? It looks like the old `Registration` did not have this same requirement, since multiple `Registration` handles on the same `Poll` would end up sharing the same underlying queue.

Will a `Waker`-based timer need to "re-export" the above requirement via its documentation and (possibly) expose its waker in an `Arc` for clients to reuse in other ways? Should it require callers to provide a `Waker` instead of building one at registration time? Is there another option (or am I misunderstanding the above requirement in some way)?

Thanks!

**Comment by Thomasdezeeuw** [comment]
I personally wouldn't use `Waker` for timers at all. I would keep the timers separate from Mio and instead see it as an additional source of events. When you would call `Poll::poll` check the next deadlines of the timers and use that as a timeout to call `Poll::poll`.

Something like the following:

```rust
let mut poll = Poll::new()?;
let mut events = Events::new();
let mut timers = Timer::new();

// When polling.

let timeout = if let Some(next_deadline) = timers.next_deadline() {
    let now = Instant::now();
    if now > next_deadline {
        // Deadline already passed.
        Some(Duration::from_millis(0))
    } else {
        Some(next_deadline.duration_since(now))
    }
} else {
    None
};

poll.poll(&mut events, timeout)?;
// Process `timers` events.
```

**Comment by kaimast** [comment]
@Thomasdezeeuw you still need a waker here to wake up the poll after a new timer is registered...

**Comment by Thomasdezeeuw** [comment]
@kaimast yes, if you allow concurrent registering timers and polling then you would need to use a `Waker`.
