### ISSUE TITLE
Non-AFD fallback?

### ISSUE THREAD

**Issue by goffrie** [tokio-rs/mio#1314]
Would it be in scope for mio to have a [fallback like libuv does](https://github.com/libuv/libuv/blob/16910d23a34b8b8c313d24824fd85383aa8a8d40/src/win/poll.c#L561) for non-MSAFD sockets on Windows?

(I ask because we are trying to deploy some software that uses mio 0.7 and a very significant number of users are hitting errors in registration, presumably due to this, so we're going to need a fallback at some layer no matter what. Mio 0.6 actually does work for these users, but it has other issues.)

**Comment by Thomasdezeeuw** [comment]
I don't use Windows... so I don't really have an opinion on this.

/cc @carllerche @kleimkuhler @piscisaureus

**Comment by piscisaureus** [comment]
I think extracting the bsp socket with SIO_BASE_HANDLE should be enough. It works without issue in wepoll. 

Maybe there's a bug in the current mio implementation where accidentally the layered socket is used instead of the base handle.

**Comment by piscisaureus** [comment]
>  a very significant number of users are hitting errors in registration, presumably due to this

I find that hard to believe. I have barely ever seen a legitimate LSP in the wild, it seems unlikely that "a very large number" of users use them all of a sudden.

But to be sure, have them share the output of `netsh winsock show catalog`.

**Comment by piscisaureus** [comment]
@goffrie from your patch it looks like you are dealing with `get_base_socket()` failures. 

It should not fail unless you're on windows XP or older. I suspect there's a subtle bug in the WSAIoctl call.

Were you testing with a 32 bit version of windows by any chance? Maybe [this](https://github.com/tokio-rs/mio/blob/a4f1151a85eca6c5a8c8d7a99c19111edccfb2f3/src/sys/windows/selector.rs#L637) `size_of::<RawSocket>() as u32` should be `size_of::<usize>() as u32`.

**Comment by goffrie** [comment]
I was testing on 32-bit Windows 7. Things work fine on that OS and break
with monitoring software installed.

Note that the size of RawSocket is the same as usize (it's defined as u32
on 32bit, and u64 on 64bit.)

**Comment by goffrie** [comment]
Here is the output of `netsh winsock show catalog`: https://gist.github.com/goffrie/bf213c7fa7906b4ef3ddfcc309119919

> dealing with get_base_socket() failures.

I agree that this doesn't actually make that much sense. Still, it's where I see errors coming from. I see that libuv ignores errors here entirely, and it uses an explicit provider whitelist.

Also I see that you actually wrote the libuv impl :smile:

**Comment by piscisaureus** [comment]
Libuv needed to support XP at the time, that's the whole reason the fallback is there. And there are some bugs in the whitelisting logic (it's too strict) that never got fixed.

I'm serious when I say SIO_BASE_HANDLE is enough - it really should not fail. To double check, maybe run the wepoll tests on your windows VM. I test it on CI with 2 different LSPs and it works fine. Microsoft docs (https://docs.microsoft.com/en-us/windows/win32/winsock/winsock-ioctls) say the same. So find thay bug in get_base_socket() and forget about that very painful fallback mode which will be nearly impossible to get right.

**Comment by goffrie** [comment]
Well.. I can only say that it does fail :P I also tried using the implementation here https://github.com/python-trio/trio/blob/master/trio/_core/_io_windows.py#L183 and it also gives the same error, which is 

```
OSError: [WinError 10014] The system detected an invalid pointer address in attempting to use a pointer argument in a call
```

Interestingly, getting SIO_BSP_HANDLE_SELECT does work, though.

**Comment by goffrie** [comment]
> To double check, maybe run the wepoll tests on your windows VM.

Ran them and they all fail (except test-reflock and test-tree which I assume are not testing the actual socket stuff), EPOLL_CTL_ADD fails.

**Comment by piscisaureus** [comment]
@goffrie 

Tried it myself, and I can confirm that SIO_BASE_HANDLE fails with EFAULT.
That's obviously a bug on qustodio's end, they shouldn't be intercepting the IOCTL at all.
However, when I use SIO_BSP_HANDLE I do get a different socket back, and everything works like clockwork. 

Maybe we add a fallback to `get_base_socket()` to try that when `SIO_BASE_HANDLE()` fails?

**Comment by piscisaureus** [comment]
SIO_BSP_HANDLE_POLL also works.
SIO_BSP_HANDLE_SELECT indeed does not (it returns the input socket).

**Comment by piscisaureus** [comment]
cc @qustodio @irikuo https://github.com/tokio-rs/mio/issues/1314#issuecomment-625812392

**Comment by piscisaureus** [comment]
Also cc @navasdavid @kokart -- https://github.com/tokio-rs/mio/issues/1314#issuecomment-625812392

**Comment by goffrie** [comment]
Unfortunately qustodio is far from the only software we detected that
causes the error in get_base_socket :/

If we can get the AFD stuff working in more cases though, that still sounds
good.

**Comment by piscisaureus** [comment]
> Unfortunately qustodio is far from the only software we detected that causes the error in get_base_socket :/

So what are the other ones?

**Comment by piscisaureus** [comment]
I did some detailed debugging of qproxy64.dll (the DLL that implements the qustodio LSP).

They actually explicitly handle SIO_BASE_HANDLE, and they seem to *intentionally* break it.
The handler was helpful enough to call some sort of log function with the message "WSPIoctl: Disabling SIO_BASE_HANDLE".

So long story short: qustodio wants to break the network stack; we should let them. I'm just sorry for the unwitting customers who buy their crap.

![image](https://user-images.githubusercontent.com/218257/81455977-26797180-9191-11ea-9d5a-0a265ab41768.png)

**Comment by goffrie** [comment]
Well... that's interesting! Thank you for the investigation :)

Given that, I think I don't think there's anything to do in mio then, but for us we're probably still going to have to have the workaround for the time being :(

**Comment by piscisaureus** [comment]
@goffrie 

> Given that, I think I don't think there's anything to do in mio then, but for us we're probably still going to have to have the workaround for the time being :(

I'm cool with adding a workaround that falls back to SIO_BSP_HANDLE_POLL if SIO_BASE_HANDLE fails, because it'd be small and contained. If qustodio catches up and starts breaking that too, the onus will be on them to explain why they break dropbox instead of the other way around. 

The #1315 workaround has a too high maintainance cost + bug risk IMO.

Another option would be to explicitly sidestep LSPs when creating sockets. This is pretty trivial, and I believe "modern" aka UWP apps do this by default anyway. Although I would not make that the default in mio, it could be added as an option, or your software could do it by itself.

**Comment by carllerche** [comment]
I think we probably can leave the issue open until we have a solution / work around.

**Comment by goffrie** [comment]
> Another option would be to explicitly sidestep LSPs when creating sockets. This is pretty trivial, and I believe "modern" aka UWP apps do this by default anyway. Although I would not make that the default in mio, it could be added as an option, or your software could do it by itself.

This sounds like a good option to me. How would one do that?

**Comment by piscisaureus** [comment]
> This sounds like a good option to me. How would one do that?

https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsasocketw

You need to explicitly set the `lpProtocolInfo` field to one that matches the MSAFD provider.

To find the appropriate lpProtocolInfo struct, use [WSAEnumProtocols](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsaenumprotocolsw). You've seen the code, it's how the libuv whitelist works.

**Comment by spaque** [comment]
JFYI some info from Qustodio's side. This issue comes from a third-party LSP driver (the infamous Komodia) that we are in the process of deprecating (at the moment it's being used in Windows 7 and below).

As @piscisaureus found out, it is indeed blocking use of SIO_BASE_HANDLE with [the intention of disabling LSP bypass](https://www.komodia.com/newwiki/index.php?title=Komodia%27s_Redirector_bug_fixes#Version_2.2.2.6).

I know for a fact Komodia is no longer maintained by its author, so the workaround should be ok.

**Comment by piscisaureus** [comment]
@spaque Thanks for the clarification.
