### ISSUE TITLE
TcpStream::connect returns error with EAGAIN on mac 

### ISSUE THREAD

**Issue by zekun000** [tokio-rs/mio#1320]
Hi,

I have seen `Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }` when use TcpStream::connect on my mac, it looks like because we don't check errno 35(which is EAGAIN) here https://github.com/tokio-rs/mio/blob/master/src/sys/unix/tcp.rs#L15

**Comment by Thomasdezeeuw** [comment]
This means that the `TcpStream` isn't connected yet. You need [register](https://docs.rs/mio/0.7.0/mio/struct.Registry.html#method.register) the stream first and wait/[`poll`](https://docs.rs/mio/0.7.0/mio/struct.Poll.html#method.poll) for a [writable event](https://docs.rs/mio/0.7.0/mio/event/struct.Event.html#method.is_writable) before you can use it. Also the [getting started guide](https://docs.rs/mio/0.7.0/mio/guide/index.html).

**Comment by zekun000** [comment]
@Thomasdezeeuw I'm not using mio directly but use it via `tokio::net::tcp::TcpStream::connect`
https://github.com/tokio-rs/tokio/blob/master/tokio/src/net/tcp/stream.rs#L119
Should I open an issue there instead?

also wonder why EINPROGRESS is treated differently than EAGAIN? they seem both indicating the connection is not up yet

**Comment by Thomasdezeeuw** [comment]
@zekun000 according to the `connect` manual on macOS it shouldn't return `EAGAIN` or `EWOULDBLOCK`, only `EINPROGRESS` that is why is treated differently. I don't know about how Tokio uses the stream in the following lines (https://github.com/tokio-rs/tokio/blob/f48065910eca238d7ed644807f85c921deb12ec3/tokio/src/net/tcp/stream.rs#L128-L132) could that be the problem?

**Comment by zekun000** [comment]
@Thomasdezeeuw if `mio::net::TcpStream::connect(&addr)?;` in line 119 failed with error (which is EAGAIN in my case) there's no chance it gets to line 128-132.

I'll file an issue with tokio too, although I think we shouldn't bail out with `EWOULDBLOCK` or `EAGAIN` since it has the same effect as `EINPROGRESS`

**Comment by Thomasdezeeuw** [comment]
@zekun000 has this been resolved?
