### ISSUE TITLE
Replace net2 with socket2

### ISSUE THREAD

**Issue by petreeftime** [tokio-rs/mio#1324]
net2 is marked as deprecated and the suggestion is to use the socket2 crate instead. `cargo audit` in particular will complain about net2 dependency.

**Comment by petreeftime** [comment]
It seems this is duplicated.

**Comment by Thomasdezeeuw** [comment]
See #1319, #1322.

**Comment by smklein** [comment]
If I submit a PR that replaces net2 with socket2 (it's compiling; passing all tests), will that be looked at?

(I understand the "if it ain't broke, don't fix it" mentality, but I'm just checking if there is opposition to this change)

**Comment by smklein** [comment]
https://github.com/tokio-rs/mio/pull/1325
