### ISSUE TITLE
crates.io has 0.6 readme for the 0.7.0 version

### ISSUE THREAD

**Issue by asafigan** [tokio-rs/mio#1327]
This is a little off. Is there a way to update this?
https://crates.io/crates/mio
<img width="644" alt="image" src="https://user-images.githubusercontent.com/18042227/82904612-b577df00-9f30-11ea-87f5-4f7c1f90ed2b.png">

**Comment by Thomasdezeeuw** [comment]
This has been fixed a while ago.
