### ISSUE TITLE
Solaris 11.4 does support SOCK_CLOEXEC and SOCK_NONBLOCK

### ISSUE THREAD

**Issue by EddaAkikusa** [tokio-rs/mio#1328]
https://github.com/tokio-rs/mio/blob/68805cbeb7797e0d2653e861e009cc10c05bd4f9/src/sys/unix/net.rs#L56
According to their document https://docs.oracle.com/cd/E88353_01/html/E37843/socket-3c.html
but still not sure about previous versions.

**Comment by Thomasdezeeuw** [comment]
@Frozen-Tofu want to open a pr moving solaris from https://github.com/tokio-rs/mio/blob/68805cbeb7797e0d2653e861e009cc10c05bd4f9/src/sys/unix/net.rs#L56 to https://github.com/tokio-rs/mio/blob/68805cbeb7797e0d2653e861e009cc10c05bd4f9/src/sys/unix/net.rs#L26-L34?

**Comment by Frozen-Tofu** [comment]
Yes, but I've to check whether Solaris 10, previous Solaris 11 and Illumos have implemented those flags.



发自我的iPhone


------------------ Original ------------------

**Comment by Thomasdezeeuw** [comment]
Illumos now has a different target: #1295.

**Comment by Thomasdezeeuw** [comment]
We don't support Solaris (see https://github.com/tokio-rs/mio/issues/1152), illumos should work.
