### ISSUE TITLE
0.7 Interest remove

### ISSUE THREAD

**Issue by martijnberger** [tokio-rs/mio#1331]
in 0.6.x Ready has a remove function that states it is:

equivalent to *self = *self & !other. 

I am unable to find a correct way to achieve the same with 0.7

**Comment by Thomasdezeeuw** [comment]
This is indeed missing on purpose as `Interest` is no longer allow to be empty in 0.7, i.e. what would `Interest::READABLE.remove(Interest::READABLE)` be? Maybe a remove function that returns an `Option` could work though.

**Comment by martijnberger** [comment]
the other way is to rebuild a new one with all the is_xxx() functions and that does not feel very efficient.
