### ISSUE TITLE
SourceFd fails to deliver WRITABLE when connected to character devices on Linux

### ISSUE THREAD

**Issue by buzmeg** [tokio-rs/mio#1337]
On a Beaglebone Black (Linux beaglebone 4.19.94-ti-r42 #1buster SMP PREEMPT Tue Mar 31 19:38:29 UTC 2020 armv7l GNU/Linux), when I attempt to use a character device file descriptor, a WRITABLE even gets delivered a single time and then never again.

I suspect that this applies to more than just character device file descriptors since SourceFd doesn't have any examples or tests that I can find.

I can drop down to libc::pollfd directly and things work as expected.

Thanks.

**Comment by Thomasdezeeuw** [comment]
Mio uses edge triggers, which means you'll only get a single write event if the source is ready to write. If you write until you hit a [`WouldBlock`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.WouldBlock) error, you should get additional events once you can write (without blocking) again.

**Comment by buzmeg** [comment]
Closing as I no longer use *any* of the Rust async frameworks with character devices.  It's more reliable and easier to debug the operating system calls directly.
