### ISSUE TITLE
Multi threaded event loop

### ISSUE THREAD

**Issue by ajgopala** [tokio-rs/mio#1341]
The non goals section states that Mio does not support it and user will need to manage it themselves.

I am on Linux and this will use epoll. I think that epoll requires use of one shot to be able to wait on the same epoll fd from two threads. Does mio expose the epoll configuration? If not how can I have two event loops processing events?

**Comment by Thomasdezeeuw** [comment]
> I think that epoll requires use of one shot to be able to wait on the same epoll fd from two threads.

I'm unsure what you mean with this statement. Do you mean two wait on an file descriptor that is created with `epoll_create(2)`, or do you mean to wait on any fd (well a socket for epoll) from two `Poll` instances currently?

For the first: `Poll` implement `AsRawFd`/`IntoRawFd` so you can use to that to wait for `Event`s using another `Poll` instance, using a `SourceFd`. If I recall correctly it will generate readable events once the `epoll` fd is ready with events.

If you want to watch a (socket) fd using two `Poll` instances that should work correctly. Do note that *all* `Poll` instances will receive an event, currently Mio can't set `EPOLLEXCLUSIVE` (see its description in the [`epoll_ctl`](https://man7.org/linux/man-pages/man2/epoll_ctl.2.html) manual). For that to work you'll need to use `libc` directly (or suggest we add another flag to `Interest`).

I personally register listener sockets (`TcpListener`) with multiple `Poll` instances without any issues.

**Comment by ajgopala** [comment]
Does mio set the EPOLLONESHOT?

I meant that epoll requires one shot If you want to be able to safely work with two threads waiting on same epoll Fd. For example, Without one shot, if two threads wait on same epoll fd and both will get notified on some readiness event and both will potentially try to read simultaneously as well from that socket. Now we have a race condition because each thread maybe reading partial data. With one shot, the thread will need to re arm the epoll fd and so only one thread will be able to read.

**Comment by Thomasdezeeuw** [comment]
> Does mio set the EPOLLONESHOT?

No one-shot support was removed because it caused issue on some platform (Windows iirc), and its functionality wasn't consistent across platforms.

> I meant that epoll requires one shot If you want to be able to safely work with two threads waiting on same epoll Fd. For example, Without one shot, if two threads wait on same epoll fd and both will get notified on some readiness event and both will potentially try to read simultaneously as well from that socket. Now we have a race condition because each thread maybe reading partial data. With one shot, the thread will need to re arm the epoll fd and so only one thread will be able to read.

This is true but only for stream based socket, i.e. `TcpStream`. For `UdpSocket` (reads entire packet) and `TcpListener` this shouldn't be a problem as the OS will handle synchronisation. For stream based socket you'll have to some kind of synchronisation yourself to ensure you don't get partial reads.

**Comment by Thomasdezeeuw** [comment]
Bringing back one-shot trigger is being discussed in issue #1049.
