### ISSUE TITLE
WASI support

### ISSUE THREAD

**Issue by mankinskin** [tokio-rs/mio#1346]
In an effort to make tokio compatible with `wasm32-wasi` (https://github.com/tokio-rs/tokio/issues/1597), it might make sense to make this crate WASI compatible aswell.

**Comment by Thomasdezeeuw** [comment]
I have an old tree: https://github.com/Thomasdezeeuw/mio/tree/wasm32-wasi, but its not functional and I don't have time to work on this.

**Comment by Thomasdezeeuw** [comment]
@mankinskin https://github.com/tokio-rs/mio/pull/1395.

**Comment by mankinskin** [comment]
@Thomasdezeeuw I have no experience in this codebase whatsoever so unfortunately I can't really help with this on the spot..

**Comment by Thomasdezeeuw** [comment]
Closing this due to lack of interest.

**Comment by hamza1311** [comment]
Can you clarify what you mean by lack of interest? As far as I can tell, this issue is blocked by missing WASI API (implementation: https://github.com/WebAssembly/WASI/pull/312)

Mio can't implement socket connections until it is supported by the platform. I don't know of anything else that Mio can implement which is supported by WASI today

**Comment by Thomasdezeeuw** [comment]
> Can you clarify what you mean by lack of interest? As far as I can tell, this issue is blocked by missing WASI API (implementation: [WebAssembly/WASI#312](https://github.com/WebAssembly/WASI/pull/312))
> 
> Mio can't implement socket connections until it is supported by the platform. I don't know of anything else that Mio can implement which is supported by WASI today

It's true that Mio couldn't support socket creation, but as far as I can tell it is possible to pass a socket "from the outside" to wasm and use it from there. For example [`sock_recv`](https://docs.rs/wasi/0.10.2+wasi-snapshot-preview1/wasi/wasi_snapshot_preview1/fn.sock_recv.html) has been part of the WASI API for a while. Mio can also already (sort of) implement `Poll` using [`poll_oneof`](https://docs.rs/wasi/0.10.2+wasi-snapshot-preview1/wasi/wasi_snapshot_preview1/fn.poll_oneoff.html). So an experimental implementation of parts of Mio is possible.

Re: lack of interest. This issue has seen very little activity and I know of no development effort to port Mio (except of my own, linked previously).

**Comment by xpepermint** [comment]
Is this permanently closed?

**Comment by Thomasdezeeuw** [comment]
@xpepermint no this issue just hasn't seen any real activity so that's why I closed it. We're still open to supporting WASM/WASI.

**Comment by Thomasdezeeuw** [comment]
Prs would be welcome. We do have to ensure that we don't break support for preview 1 though.
