### ISSUE TITLE
Cannot register new event handlers while poll is waiting for events

### ISSUE THREAD

**Issue by jwiegley** [tokio-rs/mio#1347]
While `mio::Poll::poll` is blocked waiting for events, shouldn't it be possible to use `epoll_ctl` to subscribe or unsubscribe new handlers while it is waiting? I think this should possible looking at the C code, but the way Rust makes mutable references exclusive, I cannot call `.register()` while waiting in `.poll()`. Is this correct? Is there any way around this discrepancy if it exists?

**Comment by Thomasdezeeuw** [comment]
@jwiegley for that we have the [`Registry`](https://docs.rs/mio/0.7.0/mio/struct.Registry.html), created by calling [`Poll::registry`](https://docs.rs/mio/0.7.0/mio/struct.Poll.html#method.registry).

**Comment by Thomasdezeeuw** [comment]
You might need to call [`Registry::try_clone`](https://docs.rs/mio/0.7.0/mio/struct.Registry.html#method.try_clone).

**Comment by jwiegley** [comment]
I will dig into it, thanks for the fast reply @Thomasdezeeuw.

**Comment by jwiegley** [comment]
I can confirm that this works as expected, thank you again.
