### ISSUE TITLE
Proposal: move Mio-pipe into Mio

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1354]
The Mio-pipe crate provides a simple wrapper around a Unix pipe. It's currently ~300 lines of code, but I think that can be reduced if it's lives inside the Mio repo, mainly by using [`IoSource`](https://github.com/tokio-rs/mio/blob/784d6ffeab9df9ee2f47e3cec787577c740088c5/src/io_source.rs).

One current disadvantage is that it doesn't have Windows support. But @carllerche has been working on that in https://github.com/tokio-rs/mio/pull/1351.

Source: https://github.com/Thomasdezeeuw/mio-pipe
Docs: https://docs.rs/mio-pipe/0.1.1/mio_pipe

**Comment by carllerche** [comment]
Sounds good to me. I might call the fn `pipe()` instead of `new_pipe()`, but that is minor. It can live in `mio::unix`?
