### ISSUE TITLE
Reduce the number of features

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1363]
Curerntly Mio has 6 features, pr  #1356 will add another making it 7. In my opinion that is too many, all the possible combinations currently add up to 65. So I propose to reduce the number of features in the following ways.

 * `os-poll`, enables `Poll` and `Registry`, etc. Keep as is.
 * `os-util`, enables `SourceFd` and related types. Suggestion ename it to be `os-specific` (feel free to bikeshed this name) and include all OS/platform (i.e. Unix/Windows) specific types such as `SourceFd`, `unix::pipe` and `NamedPipe`.
 * `pipe` (added by #1356), enables `unix::pipe`. Suggestion merge with `os-specific`.
 * `tcp`, enables TCP types. Suggestion create a new `net` feature will all network related types.
 * `udp`, enables UDP types. Suggestion merge with `net`.
 * `uds`, enables UDS types. Suggestion merge with `net`.
 * `extra-docs`, adds some extra docs. Suggestion remove the feature (keeping the docs).

/cc @carllerche who suggestion the features.

**Comment by carllerche** [comment]
That all sounds good to me :+1:

The main question is if `uds` belongs in `net` or `os-...`.

Another option could be `os-ext` instead of `os-specific` :shrug:

**Comment by Thomasdezeeuw** [comment]
👍 on `os-ext`. I guess `uds` belongs in `os-ext` not `net`.

**Comment by carllerche** [comment]
In Tokio, we bundled uds under `net`. I could go either way.
