### ISSUE TITLE
cargo-audit: `net2` crate has been deprecated; use `socket2` instead

### ISSUE THREAD

**Issue by Maxgy** [tokio-rs/mio#1366]
I looked at some other issues discussing this detail, but they were several months stale. Apparently `net2` is no longer actively maintained and `socket2` is an alternative project.

**Comment by Darksonn** [comment]
See #1326, #1319, #1322 and #1324.

**Comment by Thomasdezeeuw** [comment]
As maintainer of socket2, I'm suggestion to not use socket2 yet, it's simply not ready for production use. For example see https://github.com/alexcrichton/socket2-rs/commit/7bf31f95af1905880e73a169b0eb3894597e6f0f or https://github.com/alexcrichton/socket2-rs/commit/b3badc7d3d599746a3632666876f1a253476c3c7.
