### ISSUE TITLE
RUSTSEC-2020-0016: net2: `net2` crate has been deprecated; use `socket2` instead

### ISSUE THREAD

**Issue by SteveBattista** [tokio-rs/mio#1367]
https://rustsec.org/advisories/RUSTSEC-2020-0016.html states this. 

I found this with cargo audit
https://github.com/RustSec/cargo-audit

It looks like it is in your test rig:
tests/tcp.rs
 Line 6 : use net2::TcpStreamExt;
 Line 476 let client = net2::TcpBuilder::new_v4().unwrap().to_tcp_stream().unwrap();

**Comment by taiki-e** [comment]
See #1326, #1319, #1322, #1324, and #1366.
