### ISSUE TITLE
mio::sys::unix::net::socket_addr assumes the layout of std::net::SocketAddrV{4,6} matches libc::sockaddr

### ISSUE THREAD

**Issue by Nemo157** [tokio-rs/mio#1386]
@faern noted this in https://internals.rust-lang.org/t/why-are-socketaddrv4-socketaddrv6-based-on-low-level-sockaddr-in-6/13321

https://github.com/tokio-rs/mio/blob/27fbd5f04bb5f52a4d1c358cf0c04c6074a3d46b/src/sys/unix/net.rs#L78-L85

As far as I can tell there are no guarantees from `std` about the layout of `SocketAddrV{4,6}`, and this code could silently compile and cause UB elsewhere if the representation changes (e.g. if padding is added early on in the struct, resulting in C code reading uninitialized bytes).

**Comment by Thomasdezeeuw** [comment]
This is true, but as far as I known there (currently) is no other way to do this. I'm open to suggestions.

I think socket2 has a similar problem: https://github.com/rust-lang/socket2-rs/blob/b0f77842b3357dd571bb86b30b354bc55215f693/src/sockaddr.rs#L95-L115

**Comment by Thomasdezeeuw** [comment]
Maybe we can add an assertion `size_of_val(addr) == size_of(sockaddr_in)`, it doesn't solve the problem but at least it won't compile (and cause UB).

**Comment by Nemo157** [comment]
It'll help slightly, but doesn't guarantee no UB.

Fixing socket2 seems easier since it only ever copies values around, something like https://gist.github.com/Nemo157/00787cd835f73bbf90b12cbf71122844 should work. Fixing mio would take more rearranging since it's not possible to go `&SocketAddr -> *const sockaddr` soundly.

**Comment by Thomasdezeeuw** [comment]
Related: https://github.com/rust-lang/socket2-rs/issues/119.
