### ISSUE TITLE
Yank all `0.7` versions older than `0.7.6`

### ISSUE THREAD

**Issue by faern** [tokio-rs/mio#1412]
Due to #1388. If the standard library ever do change the memory layout of `SocketAddr`, usage of this crate of versions before `0.7.6` will have undefined behaviour and lead to segfaults. And even if the standard library never do change the layout of those types, those older versions of this crate still makes assumptions they should not.

This is exactly what yanking is for. Marking a release as "should not be used". I think all versions of `mio` from `0.7.0` through `0.7.5` should be yanked from crates.io.

Related issues on other crates having the same problem: https://github.com/deprecrated/net2-rs/issues/107, https://github.com/rust-lang/socket2-rs/issues/139

**Comment by Thomasdezeeuw** [comment]
Yanked all v0.7.x versions expect v0.7.6: https://crates.io/crates/mio/versions. I'm leaving v0.6.x as the dependencies are at fault there.
