### ISSUE TITLE
Implement UdpSocket::set_reuseaddr

### ISSUE THREAD

**Issue by dvtomas** [tokio-rs/mio#1426]
This would come handy in some specific cases. It allows several processes to listen to multicast packets at the same time, as documented e.g. [here](http://www.kohala.com/start/mcast.api.txt) (search for `SO_REUSEADDR`).

**Comment by Thomasdezeeuw** [comment]
Same answer as for #1424, if you can wait it can come quite easily in v0.8 when we use socket2, meanwhile you can use something like [`SockRef`](https://docs.rs/socket2/0.4.0-alpha.1/socket2/struct.SockRef.html). Or if you can't wait I would accept a pr.

**Comment by Thomasdezeeuw** [comment]
We're going to following the API in std lib, so we're not adding this method. You can use `socket2::SockRef` instead.
