### ISSUE TITLE
libc version causes MacOS compilation failure

### ISSUE THREAD

**Issue by cdmistman** [tokio-rs/mio#1433]
When trying to build on MacOS, cargo fails with the following error seen [here](https://github.com/alantech/alan/runs/1652201136#step:4:417) (failed to find `TCP_KEEPINTVL` and `TCP_KEEPCNT` in crate `libc`). Fails both the CI checks and on a local machine. After doing some investigation, it seems that [this PR](https://github.com/rust-lang/libc/pull/1776) introduced the variables to the `libc` crate starting with `0.2.71`, whereas `mio` currently requires exactly `0.2.69` on all Unix builds (including MacOS).

Patching our full build with `mio:0.7.7` but with `libc:0.2.71` (not `0.2.72`) allows the local build to pass, so it seems that the only requirement for builds to pass is to upgrade the `libc` version

Edit:
- tested on GitHub Actions using `macos-latest` (10.15)
- tested locally on Catalina (10.15.7 19H114)

**Comment by Thomasdezeeuw** [comment]
PR for v0.7.x: #1437.

**Comment by Thomasdezeeuw** [comment]
Closed by #1437.
