### ISSUE TITLE
Request new method `peer_addr` for `UdpSocket`

### ISSUE THREAD

**Issue by carlosb1** [tokio-rs/mio#1435]
It would be to expose the function `peer_addr` in the `UdpSocket` for this another [issue](https://github.com/tokio-rs/tokio/issues/3312) here my [proposal](https://github.com/carlosb1/mio/tree/1435-add-peer-addr)

**Comment by Thomasdezeeuw** [comment]
We can do this in v0.8.

**Comment by Thomasdezeeuw** [comment]
Done in #1436 (for v0.8).
