### ISSUE TITLE
-Z minimal-versions compilation fails on 0.7.6, libc 0.2.69

### ISSUE THREAD

**Issue by koivunej** [tokio-rs/mio#1439]
Hi there,

After doing some unrelated to mio dependency upgrades on a crate, I added a CI check for doing a `cargo +nightly update -Z minimal-versions`. This passes on githubs `ubuntu-latest` but not on `macos-latest`: [build error](https://github.com/NLnetLabs/domain/pull/86/checks?check_run_id=1695886712#step:8:244):

```
Error:     --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.7.6/src/sys/unix/tcp.rs:334:15
     |
334  |         libc::TCP_KEEPINTVL,
     |               ^^^^^^^^^^^^^ help: a constant with a similar name exists: `TCP_KEEPALIVE`
     | 
    ::: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.69/src/unix/bsd/apple/mod.rs:2259:1
     |
2259 | pub const TCP_KEEPALIVE: ::c_int = 0x10;
     | ---------------------------------------- similarly named constant `TCP_KEEPALIVE` defined here
```

(With more of these cut, but this shows the used versions.)

I don't have a mac myself, but it sounds like the 0.2.69 is too low. I think the `TCP_KEEPINTVL` was added in https://github.com/rust-lang/libc/commit/967dffee510042e3dcab179d5ce6d91bd36d1d55 which seems to appear first in v0.2.71.

**Comment by koivunej** [comment]
Thanks to @niklaslong it'd seem that the build fails with libc 0.2.69, but after `cargo update -p libc --precise 0.2.71` it works.

**Comment by Thomasdezeeuw** [comment]
This should be fixed in 0.7.7 and master as those require libc 0.2.82.

**Comment by koivunej** [comment]
Ah great, didn't check. Is the plan to yank 0.7.6 as well? I understand that to be the only way `tokio = "1"` dependency to pass minimal-versions build on macos, unless this could be specified as target specific requirement.. Lets see...

**Comment by Darksonn** [comment]
Tokio could increment the min version of mio to fix that.

**Comment by koivunej** [comment]
Trying to work around locally with target specific dependency https://github.com/NLnetLabs/domain/pull/86/commits/db0df6b7a12561b5e6db03f0e033ccf67d2a3f1f

**Comment by koivunej** [comment]
The above target specific optional dependency trick works probably for now.
