### ISSUE TITLE
Enabling TCP keep alive on accepted connections

### ISSUE THREAD

**Issue by jkarneges** [tokio-rs/mio#1443]
Hi,

With mio 0.7, it's unclear how to enable TCP keep alive on accepted connections. It looks like the proper way to configure keep alives is with the `TcpSocket` builder API, but `TcpListener::accept()` returns `TcpStream` and I don't see a way to go from `TcpStream` -> `TcpSocket`.

Thanks for any help!

**Comment by Thomasdezeeuw** [comment]
The `TcpSocket` was initially intended as builder for `TcpStream`/`TcpListener`. Going from `TcpStream` to `TcpSocket` (and back again I presume) isn't well supported, but it's possible by using the `FromRawFd`/`IntoRawFd` implementations on Unix and `FromRawSocket`/`IntoRawSocket` on Windows.

**Comment by jkarneges** [comment]
Thanks. Are there any gotchas with this approach, such as mio socket metadata being lost?

**Comment by Thomasdezeeuw** [comment]
Yes, but it shouldn't be a problem as long as it's the first thing you do after `accept`. Mio keeps some metadata around in debug mode mainly to check the registered state of the event source, see https://github.com/tokio-rs/mio/blob/04050dbd87d7b79c33168c6a972a8bb35cf510f8/src/io_source.rs#L62-L67.

If you can't change the socket right after `accept`ing it, you might want to consider using something like socket2's [`SockRef`](https://docs.rs/socket2/0.4.0-alpha.3/socket2/struct.SockRef.html). Also note that Mio v0.8 won't have `TcpSocket` any more and socket2 will become the preferred way to access advanced socket options (tracked in https://github.com/tokio-rs/mio/issues/1381).

**Comment by jkarneges** [comment]
Great! This make sense. Thank you.
