### ISSUE TITLE
Backport commits to 0.7.x branch

### ISSUE THREAD

**Issue by wngr** [tokio-rs/mio#1462]
Hello,

I have hit a critical issue for our use case using tokio > 1.0, which is based on mio 0.7.6: Using the accept4 syscall on Android x86 fails, either by being blocked through seccomp on more recent Android versions, but failing with _Err 38: Function not implemented_ on Android 6 on real devices.

I wonder whether it would be possible to backport 40159fa and 4c4e919 and release a new version with that, .. and get it integrated into tokio.

Not sure what the tokio's project stance is on such matters.

**Comment by Thomasdezeeuw** [comment]
I've opened #1463, with that we can release v0.7.9 and after a `cargo update` everything should be working.

**Comment by Thomasdezeeuw** [comment]
I would also like to backport #1461, after that we can create a new release.

**Comment by wngr** [comment]
Great, thanks!

**Comment by Thomasdezeeuw** [comment]
Just released v0.7.9.
