### ISSUE TITLE
Backward compatibility for systems that doesn't support accept4

### ISSUE THREAD

**Issue by zonyitoo** [tokio-rs/mio#1465]
When running on some old systems, like an old Android, they doesn't have the `accept4` syscall. When running programs on these platforms, we will get an error: `Function not implemented (os error 38)`.

It would be better to automatically fallback to `accept` when `accept4` returns this errno `ENOSYS`.

**Comment by Thomasdezeeuw** [comment]
What Android version are you running. Because `accept4(2)` was added to Linux in 2.6.28. According to https://android.stackexchange.com/questions/51651/which-android-runs-which-linux-kernel Android 1.6 is based on 2.6.29. Which means this wouldn't work on Android 1.5, that way too old to support.

**Comment by jshearer** [comment]
So it's not just restricted to `x86` android then. I encountered this same issue, and fixed it for my use case: https://github.com/tokio-rs/mio/pull/1446. Maybe the conditional just needs to be expanded to match all of android, or somehow detect at runtime whether the syscall is supported? (though that would introduce some overhead...)

**Comment by zonyitoo** [comment]
I was running on an Android Emulator (which is a x86 Android I believe).

> Maybe the conditional just needs to be expanded to match all of android, or somehow detect at runtime whether the syscall is supported?

Yup. See my PR.

**Comment by jshearer** [comment]
> but what if a .apk built with ARM toolchain and then ran on a x86 Android?
Is this with the new android 11 emulation layer?

**Comment by zonyitoo** [comment]
I have no idea. I found this on a Emulator called [MuMu](http://mumu.163.com/).

Kernel version: `4.0.9-android-x86+luoweiqiao@a11-gz02-test.i.nease.net #1 Thu Jan 21 21:03:25 HKT 2021`
Android version: 6.0.1

Actually most of the x86 Emulators can run ARM apks.

**Comment by jshearer** [comment]
> Actually most of the x86 Emulators can run ARM apks.

I did not know that! Neat

**Comment by Thomasdezeeuw** [comment]
I currently see this as more of a problem of the emulator than Mio. The Linux kernel has `accept4(2)` since version 2.6.28, so if the emulator reports 4.0.9 it should it. Furthermore Android 5.0 (API version 21), released in 2014, should also have `accept4(2)` according to https://github.com/android/ndk/issues/1372. So this leads me to believe it's a problem with the emulator(s), not actual Android.

Also @zonyitoo I'm not going to accept #1466 in its current form as it has needless overhead for non-Android/emulator platforms.

**Comment by zonyitoo** [comment]
Hmm, alright. It is reasonable.

**Comment by Thomasdezeeuw** [comment]
This was fixed mostly by #1446 for emulator. I don't there is anything actionable here.
