### ISSUE TITLE
Waker issue

### ISSUE THREAD

**Issue by singaraiona** [tokio-rs/mio#1470]
It seems that Waker doesn't track wakes count (Linux)

```rust
extern crate mio;

use std::sync::Arc;
use std::thread;
use std::time::Duration;

use mio::{Events, Poll, Token, Waker};

const WAKE_TOKEN: Token = Token(10);

const WAKE_ROUNDS: usize = 5;

fn main() {
    let mut poll = Poll::new().unwrap();
    let mut events = Events::with_capacity(1024);

    let waker = Arc::new(Waker::new(poll.registry(), WAKE_TOKEN).unwrap());

    let waker1 = waker.clone();

    let handle = thread::spawn(move || {
        thread::sleep(Duration::from_millis(500));

        for _ in 0..WAKE_ROUNDS {
            waker1.wake().expect("unable to wake");
            thread::sleep(Duration::from_millis(50));
        }
    });

    let mut cnt = 0;

    loop {
        poll.poll(&mut events, None).unwrap();

        for e in events.iter() {
            cnt += 1;
            println!("wake: {:?}, cnt: {}", e, cnt);
        }

        if cnt == WAKE_ROUNDS {
            break;
        }

        thread::sleep(Duration::from_millis(100));
    }

    let _ = handle.join();
}
```

Output: 

```
wake: Event { token: Token(10), readable: true, writable: false, error: false, read_closed: false, write_closed: false, priority: false, aio: false, lio: false }, cnt: 1
wake: Event { token: Token(10), readable: true, writable: false, error: false, read_closed: false, write_closed: false, priority: false, aio: false, lio: false }, cnt: 2
wake: Event { token: Token(10), readable: true, writable: false, error: false, read_closed: false, write_closed: false, priority: false, aio: false, lio: false }, cnt: 3
```

As I understand, Waker use eventfd under Linux that has a counter, unfortunately, a number of events doesn't match with wakes() calls.

**Comment by Thomasdezeeuw** [comment]
The `Waker` doesn't count wakes, it has one goal: wake a thread currently calling `Poll::poll`. The fact is uses `eventfd` is an implementation detail. On other platforms, e.g. FreeBSD, it uses `EVFILT_USER` which doesn't count (the number of wakes) so we can't provide such functionality in a cross-platform way.

I'm not sure why you need the count but you could do one of two things to get it:
1) Use `eventfd` directly, limiting yourself to Linux/Android.
2) Create a wrapper type for `mio::Waker` with an `AtomicUsize` which is increased each call to `wake`.

As an aside, why would you think think `Waker` would count the number of wake calls?

**Comment by singaraiona** [comment]
There are number of userspace queues in my case uses Waker. If events are coming frequently - I'm unable to determine how many times to poll these queues. Even if I have own events atomic counter - there are no guaratnties that new events doesn't come before poll() called.

**Comment by Thomasdezeeuw** [comment]
Can you attempt to remove an item from the user space queues? Then you can call `Poll::poll` and if you get a single `Waker` event attempt to remove an item from the user space queues until their empty (for now). Something like the following:

```rust
poll.poll(&mut events)?;
let mut check_user_space = false;
for event in events {
    match event.token() {
        WAKER_TOKEN => { check_user_space_queues = true; },
        _ => {}, 
    }
}

if check_user_space_queues {
    for queue in user_space_queues {
            if let Some(item) = queue.try_remove() {
                process(item);
            }
    }
}
```

**Comment by singaraiona** [comment]
Yeah, It looks pretty close to my code. But if  new events arrives between ```for queue in user_space_queues {``` cycle and ```poll.poll(&mut events)?;``` - poll will not wake.

**Comment by Thomasdezeeuw** [comment]
> Yeah, It looks pretty close to my code. But if new events arrives between `for queue in user_space_queues {` cycle and `poll.poll(&mut events)?;` - poll will not wake.

This is not true.

If you call `Waker::wake` while the registered `Poll` instance is not polling it will still get the event the next time it calls `Poll::poll`. Using my previous example it would mean that `poll.poll` would return (almost) immediately with an event with `WAKER_TOKEN`.

**Comment by singaraiona** [comment]
Will check again, maybe my fault.

**Comment by singaraiona** [comment]
Yeah, You right. It is enough to have own events counter for that. Sorry for disturbing.
