### ISSUE TITLE
Question: How can I handle in a cross-platform way that a TCP connection has failed?

### ISSUE THREAD

**Issue by lemunozm** [tokio-rs/mio#1486]
Hi!

To check if a Tcp connection has been connected or not, I follow the next schema:

1. TcpStream::connect(..)
2. Register to readable and writable interests
3. wake from the poll
    - if I wake as writable, the connection was successful => connected
    - if I wake as readable with 0 bytes read, it was a problem in the connection => not connected

This seems to works fine in Linux. But in MacOS, if I connect to an unreachable address I get also a writable poll event (which until I know it means a connection successful)

Is there something I'm misunderstanding? Do I need to make some extra checks to be "more" cross-platform when my socket wakes after a `connect` action?

Thanks a lot for your help!

**Comment by Thomasdezeeuw** [comment]
@lemunozm as you found out it's a pretty difficult thing to do correctly. Please take a look at https://github.com/Thomasdezeeuw/heph/blob/12cb4dc3e828c63c18c1ba7a21bcfc39db3bf468/src/net/tcp/stream.rs#L560-L622, specifically https://github.com/Thomasdezeeuw/heph/blob/12cb4dc3e828c63c18c1ba7a21bcfc39db3bf468/src/net/tcp/stream.rs#L606-L609. That should be a fully working implementation to check if a `TcpStream` is connected.

**Comment by lemunozm** [comment]
Thanks for this great source of information!

**Comment by lemunozm** [comment]
Hi @Thomasdezeeuw, I tested your solution, and works perfectly in Linux and Mac. 

However in Windows seems like if the connection fails, the poll wakes up neither from writable nor read interests and I'm not able to give a` ConnectionRefused` to the user. Have you experienced the same issue?

Thanks!

**Comment by Thomasdezeeuw** [comment]
@lemunozm, great. I think this can be closed then?
