### ISSUE TITLE
Is there a way to add multiple timeout to mio::Poll?

### ISSUE THREAD

**Issue by tubzby** [tokio-rs/mio#1492]
Say if I have a UDP server waiting for packets, on each client or connection, after some time I want to keep a timer say 60 seconds on each connection, when a timeout event occurs, the server will send packets to detect if the peer is alive or not, if yes, schedule next timer.

The poll method only requires a timeout duration parameter,  it seems that I can't have multiple timers, is that correct?
If so, are there any other work grounds?

By the way, I know the c library libev can deal with this, it support multiple timers and each timer have an extra data field which we can use as a context linked to the specific event.

**Comment by Darksonn** [comment]
I'm pretty sure that Tokio handles this by just computing which timer has the smallest duration and using that.

**Comment by Thomasdezeeuw** [comment]
Yeah, like @Darksonn said, it's best to handle timers in user-space. Unlike libev witch contains "everything" to setup an event loop, Mio focuses on provided non-blocking I/O. You could use something like Linux's [`timerfd`](https://man7.org/linux/man-pages/man2/timerfd_create.2.html), but I do think user-space timers are more performant (less system calls).

If you're looking for a concrete example you can indeed look at Tokio, or Heph (polling: https://github.com/Thomasdezeeuw/heph/blob/807537773119831778ae7c57c7e917db5271cff0/src/rt/local/mod.rs#L437-L510, determining next deadline https://github.com/Thomasdezeeuw/heph/blob/807537773119831778ae7c57c7e917db5271cff0/src/rt/local/timers.rs#L117-L144).

**Comment by tubzby** [comment]
Thank you for your help!

In fact, the main problem with my scenario is that, when a timeout event occurs, I need to know which connection is causing the timeout so I can send a keepalive message to the peer.

I'm thinking to keep a reference of the connection of the latest timer, but I don't like the idea.

**Comment by przygienda** [comment]
@ least on older mio (0.6, 0.7) you can easily register multiple timers on
the builder with different tokens. I never ran it @ massive scale, staying
@ max. maybe 200 timers or so.

**Comment by tubzby** [comment]
@przygienda Thank you, I will give it a try.

**Comment by Thomasdezeeuw** [comment]
@tubzby you can start with a simple `BinaryHeap<(Instant, Token)>` (with a `Mutex` if needed) for your timer implementation, it should cover most needs and scales relatively well. Once it stops scaling you can look into something called a "Timing Wheel" which is the data structure I (and I believe Tokio) uses for keeping track of timers.
