### ISSUE TITLE
Why metal IO library compiles to slow code?

### ISSUE THREAD

**Issue by Frago9876543210** [tokio-rs/mio#1504]
```
$ cargo build --release --example=udp_server --features="os-poll net"
```
Now you can download some tool such as [IDA Freeware](https://hex-rays.com/ida-free/#download) and open `./target/release/examples/udp_server`

At least the first problem I found is this not-inlined libc functions. Instead of just calling recvfrom we having ton of calls
```
mio::net::udp::UdpSocket::recv_from
std::net::udp::UdpSocket::recv_from
std::sys::unix::net::Socket::recv_from_with_flags
recvfrom + panic checks
```

```
$ rustc -V --verbose
rustc 1.55.0-nightly (a435b49e8 2021-06-28)
binary: rustc
commit-hash: a435b49e86d16e98dcc6595dd471f95e823f41aa
commit-date: 2021-06-28
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

**Comment by Thomasdezeeuw** [comment]
I'm a little unsure what this issue is actually about... can you elaborate?

As for the inlining try link time optimisations (LTO) it will allow for more aggressive inlining across crate bounds such as Mio -> Libc.

**Comment by Thomasdezeeuw** [comment]
Since there are no further comments I'm closing this.
