### ISSUE TITLE
no method named `registry` found for enum `std::result::Result<mio::Poll, std::io::Error>` in the current scope

### ISSUE THREAD

**Issue by litieqq** [tokio-rs/mio#1508]
I have encountered the below  problem when I build the my own project using mio(version: 0.7), what's the reason and how to solve it?
additonal,
1.my computer is MacBook Pro;
2.my mio dependency is like this: 'mio = {version="0.7",features=["os-poll","net"]}'

error[E0599]: no method named `registry` found for enum `std::result::Result<mio::Poll, std::io::Error>` in the current scope
  --> src/main.rs:22:10
   |
22 |     poll.registry()
   |          ^^^^^^^^ method not found in `std::result::Result<mio::Poll, std::io::Error>`

error[E0599]: no method named `registry` found for enum `std::result::Result<mio::Poll, std::io::Error>` in the current scope
  --> src/main.rs:28:10
   |
28 |     poll.registry()
   |          ^^^^^^^^ method not found in `std::result::Result<mio::Poll, std::io::Error>`

error[E0599]: no method named `poll` found for enum `std::result::Result<mio::Poll, std::io::Error>` in the current scope
  --> src/main.rs:34:14
   |
34 |         poll.poll(&mut events, None)?;
   |              ^^^^ method not found in `std::result::Result<mio::Poll, std::io::Error>`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `redis-R`

**Comment by Thomasdezeeuw** [comment]
You need to handle the [`Result`](https://doc.rust-lang.org/std/result/enum.Result.html) returned by `Poll::new`. Consider reading the Rust book, especially the chapter about errors: https://doc.rust-lang.org/stable/book/ch09-02-recoverable-errors-with-result.html

**Comment by litieqq** [comment]
Thanks, It's the problem
