### ISSUE TITLE
Support SOCK_SEQPACKET 

### ISSUE THREAD

**Issue by windniw** [tokio-rs/mio#1511]
Hey

  Does mio support bind with `SOCK_SEQPACKET`?  I found that UnixLitener bind with `SOCK_STREAM` and UnixDatagram bind with `SOCK_DGRAM`, but how to bind with `SOCK_SEQPACKET`

**Comment by Thomasdezeeuw** [comment]
I'm afraid Mio doesn't currently supports it. You can use the socket2 crate and then convert into a Mio type.

**Comment by Thomasdezeeuw** [comment]
Closing this as Mio isn't going to support this at this time.

**Comment by paulnice** [comment]
@Thomasdezeeuw Do you have any reason why?

**Comment by Thomasdezeeuw** [comment]
> @Thomasdezeeuw Do you have any reason why?

Mio only supports the same API as std lib. Supporting all kinds of sockets in Mio would mean the scope of the crate would be way too big.

**Comment by paulnice** [comment]
> > @Thomasdezeeuw Do you have any reason why?
> 
> Mio only supports the same API as std lib. Supporting all kinds of sockets in Mio would mean the scope of the crate would be way too big.

Got it! Thank you very much for the prompt response

**Comment by Noah-Kennedy** [comment]
Even still, given the usefulness of seqpacket I'm inclined to think that we should add this to Mio and Tokio.

**Comment by Thomasdezeeuw** [comment]
> Even still, given the usefulness of seqpacket I'm inclined to think that we should add this to Mio and Tokio.

It can be added to Tokio fairly easily I think, using `mio::AsyncFd` and `socket2::Socket2`.

However for Mio we're sticking with matching the std lib API. It's one of those cases where if we allow one thing, you're opening up the floodgates for many more.
