### ISSUE TITLE
Add a method for getting the size of the next datagram to UdpSocket

### ISSUE THREAD

**Issue by thajohns** [tokio-rs/mio#1512]
This could prevent wasteful allocation when trying to receive a datagram.

This is surprisingly difficult to do portably, but here are some methods for doing this on various flavors of UNIX:
- the `FIONREAD` ioctl, which works on Linux (but note that on other UNIX variants this can return a value larger than the next packet)
- the `MSG_TRUNC` flag to `recv()` and friends, which causes them to return the size of the datagram instead of the amount of data read. Not sure if this is portable.
- the `SO_NREAD` sockopt, which doesn't seem to exist on Linux, but supposedly exists on OSX and some BSDs

I'm not sure how to accomplish this on Windows.

**Comment by thajohns** [comment]
The way that I had conceived of it was that the user of the API could choose to ask what the size of the next datagram is before calling `recv()`, so the old way of doing it would still work.

**Comment by Thomasdezeeuw** [comment]
@thajohns if you want to avoid over-allocation you can preallocate a large area, e.g. a `mmap`ped-area, take a 64k (1 << 16) slice from that to read into and then reduce the slice the amount of bytes read and reuse the bytes after it for the next read. (do consider alignment when you do!)

But I don't think Mio can offer much more here so I'm closing this.
