### ISSUE TITLE
Proper handling of ErrorKind::NotConnected

### ISSUE THREAD

**Issue by dvtomas** [tokio-rs/mio#1523]
Windows, mio 0.7.13

When I try to `read()` from a `TcpStream` opened to an address that can't be connected to (e.g, on my box `telnet 10.20.30.70 5010` reports *Connecting...* for a loong time), the `read` returns `ErrorKind::NotConnected`. When trying to `read` again, it returns the same error again. However, it might eventually connect (it might just take some time for the connection to be established), so this is not a fatal error, just a state of the connection. 

So, what is the proper handling of `NotConnected`? Two options come to my mind:

 1. `read()` repeatedly until the connection is established or fails with a hard error. Spin-locking `read()`s consumes CPU, so it looks like a terrible idea. 
 2. `poll()`. But, the mio documentation states that *Once a readiness event is received, the corresponding operation must be performed repeatedly until it returns WouldBlock. Unless this is done, there is no guarantee that another readiness event will be delivered, even if further data is received for the event source.*. So, I get it that I should **only** `poll()` when I get an explicit `ErrorKind::WouldBlock`, otherwise it is dangerous because I may not be delivered a crucial readiness event.

Btw, on Linux, I do not get `NotConnected` in such case at all.

**Comment by Darksonn** [comment]
I'm not that familiar with windows, but this sounds very weird. Surely the connect call would not return until the connection is actually established...

**Comment by dvtomas** [comment]
I connect like this (ignore the `BinaryTransportError`, that's project-specific)

```rust
let socket = TcpSocket::new_v4().map_err(|cause|
    BinaryTransportError::Io { description: "Tcp: Create socket failed".to_owned(), cause }
)?;
socket.set_reuseaddr(true).map_err(|cause|
    BinaryTransportError::Io { description: "Tcp: setting SO_REUSEADDR(true) failed".to_owned(), cause }
)?;
// Probably a good idea, see e.g. here for details: https://stackoverflow.com/a/14388707/3220468
let linger = Some(Duration::from_secs(5));
socket.set_linger(linger).map_err(|cause|
    BinaryTransportError::Io { description: format!("Tcp: set_linger({:?})", linger), cause }
)?;
socket.set_recv_buffer_size(1024 * 1024).map_err(|cause|
    BinaryTransportError::Io { description: "Tcp: set_recv_buffer_size".to_owned(), cause }
)?;

if cfg!(windows) {
    // These docs: https://docs.rs/mio/0.6.16/mio/net/struct.TcpStream.html#method.connect_stream
    // are for an older version of MIO, but the fact that
    // "Note that on Windows you must bind a socket before it can be connected, so if a custom TcpBuilder
    // is used it should be bound (perhaps to INADDR_ANY) before this method is called."
    // probably still holds.
    let any_addr = SocketAddrV4::new(Ipv4Addr::new(0, 0, 0, 0), 0);
    socket.bind(any_addr.into()).map_err(|cause|
        BinaryTransportError::Io { description: "Tcp: bind failed".to_owned(), cause }
    )?;
};

let stream = socket.connect(config.host.into()).map_err(|cause|
    BinaryTransportError::Io { description: format!("Tcp: connect({})", &config.host), cause }
)?;

```

Is there something I shouldn't be doing?

**Comment by dvtomas** [comment]
Anyway, `connect()` in MIO should be IMHO non-blocking as well, so if I understand correctly, I don't see a reason why it should wait until the connection is actually established.

**Comment by Darksonn** [comment]
Right, I see now. The way `connect` is implemented in Tokio is that first the socket is connected, then it waits for the socket to become ready in the write direction. You should probably insert a similar wait for it to become write ready before you try to use it.

**Comment by dvtomas** [comment]
Ok, I was not `poll`ing before the first `read` at all. I was relying on the fact, that I should `poll` after I `read` a `WouldBlock`, but the problem was that I was getting a `NotConnected` instead and I was trying to treat that as a recoverable error.

So I guess the correct approach is to `poll` first (it seems to wait until the connection is established with both READABLE and WRITABLE interests, that's good). This `poll` will wait until the connection is actually established (or times out). Then I should treat a `NotConnected` error as a hard error, not try to recover.

One more question: I'm switching between reads and writes by `reregister`ing the interest, then performing the respective operation (`read`/`write`), and `poll()` in case I get a `WouldBlock`. Is this correct usage, or should I *always* do a `poll()` after `reregister`? It seems to work fine without a `poll()` after `reregister`, and I'm afraid that the extra `poll()` might make me miss readiness events, but I haven't found explicits docs on that.

**Comment by Thomasdezeeuw** [comment]
> Ok, I was not `poll`ing before the first `read` at all. I was relying on the fact, that I should `poll` after I `read` a `WouldBlock`, but the problem was that I was getting a `NotConnected` instead and I was trying to treat that as a recoverable error.

`TcpStream::connect` is a bit special in this regard. For most types you can attempt to perform I/O, e.g. read, and get a `WouldBlock` error. However this is not true for an unconnected `TcpStream` (i.e. what is returned by `TcpStream::connect`), for it to function you must first wait for an event. After that you need to check if it's connected properly before using it. For example see https://github.com/Thomasdezeeuw/heph/blob/0c4f1ab3eaf08bea1d65776528bfd6114c9f8374/src/net/tcp/stream.rs#L560-L622, it's Unix only code but it should work on Windows as well.

> So I guess the correct approach is to `poll` first (it seems to wait until the connection is established with both READABLE and WRITABLE interests, that's good). This `poll` will wait until the connection is actually established (or times out). Then I should treat a `NotConnected` error as a hard error, not try to recover.

I think (doing this from memory) only `READABLE` is required for connecting. You indeed need to wait for an event, but also need to check `TcpStream::peer_addr` to ensure the socket is connected, again see https://github.com/Thomasdezeeuw/heph/blob/0c4f1ab3eaf08bea1d65776528bfd6114c9f8374/src/net/tcp/stream.rs#L560-L622.

> One more question: I'm switching between reads and writes by `reregister`ing the interest, then performing the respective operation (`read`/`write`), and `poll()` in case I get a `WouldBlock`. Is this correct usage, or should I _always_ do a `poll()` after `reregister`? It seems to work fine without a `poll()` after `reregister`, and I'm afraid that the extra `poll()` might make me miss readiness events, but I haven't found explicits docs on that.

Because Mio currently only supports edge-triggers I would recommend attempting to do the I/O operation and only if it failed wait for an event (but mind my previous comment as `TcpStream::connect` differs in this aspect). This way you don't need to de/re-register at all, simply register with the interests you want use (in this case read and write). So, that would be: 
1. Call `TcpStream::connect`
2. Register stream with both read and write.
3. Wait for an event.
4. Check `TcpStream::peer_addr`, depending on the value go to 3 or 5.
5. Now the stream can be used.

I/O loop would look like the following:
1. Attempt I/O, e.g. write. Depending on the returned error, `WouldBlock` go to 2, Ok/err go to 3.
2. Wait for event, go to 1.
3. Done

**Comment by dvtomas** [comment]
Thank you for the details. I think this should be thoroughly documented in the official MIO documentation, it seems to be almost impossible to use it properly without this knowledge.

Just to double check I understand your comment and the referenced source correctly: I need to 

1. `TcpStream::connect`
2. `poll`
3. check `peer_addr`
4. if it returns `NotConnected`, go to 2. If OK, go to 5.
5. Connection is established, I can Read/Write

? That is, I need to loop 2-4 because the wait-for-connection-established `poll` at 2 may kind of spuriously return even though the connection is not established yet? 

And another question: You write that `TcpStream` is special in that it needs to be `poll`ed before  actually reading/writing to it for the first time. Is it OK to also `poll` other `Source`s (e. g. `UdpStream`) before actually reading or writing to them first? Or is it dangerous, because for other `Source`s it might happen that such a `poll` could unwantedly block because it was not invoked as a result of an operation returning a `WouldBlock`?

**Comment by dvtomas** [comment]
@Thomasdezeeuw Can you confirm/answer my last questions, please, if you have the time?

**Comment by Thomasdezeeuw** [comment]
> ? That is, I need to loop 2-4 because the wait-for-connection-established `poll` at 2 may kind of spuriously return even though the connection is not established yet?

Indeed spurious events are possible. But note that in step 4 a valid (connection) error can also be returned, also also check `SO_ERROR` (`take_error`) for those.

> And another question: You write that `TcpStream` is special in that it needs to be `poll`ed before actually reading/writing to it for the first time. Is it OK to also `poll` other `Source`s (e. g. `UdpStream`) before actually reading or writing to them first? Or is it dangerous, because for other `Source`s it might happen that such a `poll` could unwantedly block because it was not invoked as a result of an operation returning a `WouldBlock`?

Only unconnected `TcpStream`s (those created via `TcpStream::connect`, not via e.g. `TcpListener::accept`) are special in this way. `UdpSocket` (`UdpStream` doesn't exists) doesn't have the concept of a connection: it just sends packet to the address, but not checking if they ever arrive. This means the socket is never connected.

**Comment by Darksonn** [comment]
Hmm. Tokio doesn't check `peer_addr`, though it does call `take_error`.

**Comment by dvtomas** [comment]
Ok, I'll implement it according to your suggestions and the heph example. Thank you for your patience. Still, I'm astonished that such a crucial thing is not even mentioned in the Mio docs.

**Comment by Thomasdezeeuw** [comment]
> Ok, I'll implement it according to your suggestions and the heph example. Thank you for your patience. Still, I'm astonished that such a crucial thing is not even mentioned in the Mio docs.

Yeah, it might not always seem like it but Mio is a very low level library, you really need OS specific knowledge to use it correctly. But you're right we should document this stuff better.
