### ISSUE TITLE
Why not use micros duration granularity with .poll()?

### ISSUE THREAD

**Issue by serzhiio** [tokio-rs/mio#1541]

**Comment by Thomasdezeeuw** [comment]
We do use microsecond precision if it's supported by the OS, but e.g. [`epoll`](https://man7.org/linux/man-pages/man2/epoll_wait.2.html) only allows us to specify the timeout in milliseconds.

**Comment by serzhiio** [comment]
Is it possible to use `epoll_pwait2()`?

**Comment by Thomasdezeeuw** [comment]
No that was added in 5.11, we support older kernels.
