### ISSUE TITLE
make do_io() public to allow customized I/O operations

### ISSUE THREAD

**Issue by masa-koz** [tokio-rs/mio#1550]
I'm trying to use WSARecvMsg() on mio::net::UDPSocket. And I find that I should call WSARecvMsg() in do_io() like UDPSocket#recv(). But I cannot do because do_io() is not public.

So, I think that do_io() should be callable by the user of mio::net::UDPSocket.
Is this ok?

Currently, I'm working in https://github.com/masa-koz/mio/blob/6dd2162e526cc74bdca183b7c1ec46565aecad83/src/net/udp.rs#L329

**Comment by masa-koz** [comment]
I'm trying to use WSARecvMsg to retrieve some ancillary datas such as pkt_info. So I would like to use recvmsg itself like https://docs.rs/nix/0.23.1/nix/sys/socket/fn.recvmsg.html

**Comment by Thomasdezeeuw** [comment]
On Unix you could just use the call since `do_io` doesn't do anything, see https://github.com/tokio-rs/mio/blob/e8aed7baea88e844a7402a29ec8675ddc341edd9/src/sys/unix/mod.rs#L46-L54. However on Windows our internals don't allow for that I'm afraid, see https://github.com/tokio-rs/mio/blob/e8aed7baea88e844a7402a29ec8675ddc341edd9/src/sys/windows/mod.rs#L77-L92.

**Comment by masa-koz** [comment]
Can you add do_rawio (or do_rawapi) which calls do_io internally? do_io is still private, so you can change the detail without breaking api.

If this is also unacceptable, I will rewrite my code using miow.

**Comment by Thomasdezeeuw** [comment]
@masa-koz we've agreed that this addition would be acceptable.

It should be added to the following types:
 * `net::TcpStream`
 * `net::UnixStream`
 * `net::UdpSocket`
 * `net::UnixDatagram`
 * `unix::pipe::Sender`
 * `unix::pipe::Receiver`

I think the something like the following should work.

```rust
impl TcpStream {
    /// Execute an I/O operation ensuring that the socket receives more events
    /// if it hits a [`WouldBlock`] error.
    ///
    /// # Notes
    ///
    /// This method is required to be called for **all** I/O operations to
    /// ensure the user will receive events once the socket is ready again after
    /// returning a [`WouldBlock`] error.
    ///
    /// [`WouldBlock`]: io::ErrorKind::WouldBlock
    ///
    /// # Examples
    ///
    /// ```
    /// # use std::error::Error;
    /// #
    /// # fn main() -> Result<(), Box<dyn Error>> {
    /// use std::io;
    /// use std::os::unix::io::AsRawFd;
    /// use mio::net::TcpStream;
    ///
    /// let address = "127.0.0.1:8080".parse().unwrap();
    /// let stream = TcpStream::connect(address)?;
    ///
    /// // Wait until the steram is readable...
    ///
    /// // Read from the stream using a direct libc call, of course the
    /// // `io::Read` implementation would be easier to use.
    /// let mut buf = [0; 512];
    /// let n = stream.try_io(|| {
    ///     let buf_ptr = &mut buf as *mut _ as *mut _;
    ///     let res = unsafe { libc::recv(stream.as_raw_fd(), buf_ptr, buf.len(), 0) };
    ///     if res != -1 {
    ///         Ok(res as usize)
    ///     } else {
    ///         Err(io::Error::last_os_error())
    ///     }
    /// })?;
    /// eprintln!("read {} bytes", n);
    /// # Ok(())
    /// }
    /// ```
    pub fn try_io<F, T>(&self, f: F) -> io::Result<T>
    where
        F: FnOnce() -> io::Result<T>,
    {
        self.inner.do_io(|_| f())
    }
}
```

**Comment by masa-koz** [comment]
It sounds great. Can I create a PR?

**Comment by Thomasdezeeuw** [comment]
> It sounds great. Can I create a PR?

@masa-koz yes
