### ISSUE TITLE
RDMA support

### ISSUE THREAD

**Issue by kczimm** [tokio-rs/mio#1559]
Is there any desire to add RDMA support to this crate? I know @jonhoo has a [crate](https://github.com/jonhoo/rust-ibverbs) binding the ibverbs API. Crate support for RDMA could be a significant factor in the adoption of Rust in my organization. If there is a belief that mio could be a good place for RMDA to enter Rust's networking ecosystem, I would consider helping with the work.

**Comment by Thomasdezeeuw** [comment]
Although I think supporting RDMA is pretty cool, I'm not convinced Mio is the right place for. @kczimm what makes you say it's a good fit for Mio?

**Comment by kczimm** [comment]
Thanks for the quick response. Sorry for the confusion. I don't know if RDMA is a good fit for mio or not. It was mentioned in a [Tokio issue](https://github.com/tokio-rs/tokio/issues/3637#issuecomment-804378278) that mio may be a place for RDMA. I naively agreed based solely on knowing that mio contains asynchronous networking primitives.

It would be nice to have RDMA transports be available in a popular networking crate alongside other standard transport implementations (i.e. TCP, UDP, etc.). I am trying to discover if that is possible and realistic in the future or if RDMA will just be something that gets treated as special in how it is incorporated into a development project.

**Comment by asomers** [comment]
I don't know enough about how IB works.  If it works with kqueue or epoll, then it can work with mio.  It may not even need any special support from within mio itself, but could be added as a separate crate.  OTOH, if you're talking about the usermode polling paradigm, then that would be very hard to shoehorn into mio/tokio.  You may need to rewrite the tokio reactor to do polling.

**Comment by kczimm** [comment]
I am still learning the details of RDMA and the verbs API, but from [RDMAMojo](https://www.rdmamojo.com/2012/08/11/ibv_get_async_event/) I'm reading this as it works with epoll. Not that it matters, but I'm specifically interested in RDMA for [RoCE](https://en.wikipedia.org/wiki/RDMA_over_Converged_Ethernet) rather than IB or iWarp.

> OTOH, if you're talking about the usermode polling paradigm, then that would be very hard to shoehorn into mio/tokio. You may need to rewrite the tokio reactor to do polling.

Sorry for my ignorance, but can you elaborate on this?

**Comment by asomers** [comment]
I'm referring to RDMA polling, the fastest mode of access, which completely bypasses the kernel.  So instead of epoll, userland must poll the IB adapter for new data.  I think that mode is popular among HPC people.

**Comment by Thomasdezeeuw** [comment]
@kczimm unless you still think Mio is the right place for this I'm going to close this issue.
