### ISSUE TITLE
Update to 2021 edition and MSRV 1.61

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1562]
MSRV to support https://github.com/tokio-rs/mio/issues/1527, and 2021 because we can at that point.

**Comment by gustav3d** [comment]
What is blocking this ?.

**Comment by Thomasdezeeuw** [comment]
Mainly Tokio TLS, which still supports rustc 1.46.

**Comment by Thomasdezeeuw** [comment]
Done in https://github.com/tokio-rs/mio/pull/1733.
