### ISSUE TITLE
unresolved symbol when build as crt static libary

### ISSUE THREAD

**Issue by bigdogs** [tokio-rs/mio#1568]
Hi, 

I build my rust project as static library, but it show these `mio` errors when I trying to use the library in my visual studio project. 

```
3>   Creating library ..\debug\Service.lib and object ..\debug\Service.exp
3>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
3>seraph.lib(mio-553dd9c5e45c7a63.mio.645aa5dc-cgu.15.rcgu.o) : error LNK2019: unresolved external symbol __imp__NtDeviceIoControlFile@40 referenced in function __ZN3mio3sys7windows3afd3Afd4poll17h82fccef1fddabacdE
3>seraph.lib(mio-553dd9c5e45c7a63.mio.645aa5dc-cgu.15.rcgu.o) : error LNK2019: unresolved external symbol __imp__RtlNtStatusToDosError@4 referenced in function __ZN3mio3sys7windows3afd3Afd4poll17h82fccef1fddabacdE
3>seraph.lib(mio-553dd9c5e45c7a63.mio.645aa5dc-cgu.15.rcgu.o) : error LNK2019: unresolved external symbol __imp__NtCancelIoFileEx@12 referenced in function __ZN3mio3sys7windows3afd3Afd6cancel17hdaec97f683286d66E
3>seraph.lib(mio-553dd9c5e45c7a63.mio.645aa5dc-cgu.15.rcgu.o) : error LNK2019: unresolved external symbol __imp__NtCreateFile@44 referenced in function __ZN3mio3sys7windows3afd3Afd3new17ha60453cebc0c819bE
```

**Comment by bigdogs** [comment]
Hi, @Thomasdezeeuw 

Problem still exists after upgrading mio to latest mater branch,  it seems mio use the internal api .
https://docs.microsoft.com/en-us/windows/win32/devnotes/calling-internal-apis

But I'm still have no idea how to fix it

**Comment by Thomasdezeeuw** [comment]
> Problem still exists after upgrading mio to latest mater branch, it seems mio use the internal api . https://docs.microsoft.com/en-us/windows/win32/devnotes/calling-internal-apis

I think that's true yes.

@Noah-Kennedy, @kennykerr do either of you have time to look into this?

**Comment by Noah-Kennedy** [comment]
+1 to @kennykerr's question

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/164501800-8e7eed5b-b40e-408a-b31c-71e593c720ff.png)

Ensure you are bringing in `ntdll.lib`, where this function is defined. You can do this in Visual Studio via the Project menu > Project properties > Linker > Input. Add `ntdll.lib` to the `;` delimited list and rebuild.
