### ISSUE TITLE
Tokio logs to trace with "signal" feature

### ISSUE THREAD

**Issue by and-nissa** [tokio-rs/mio#1578]
**Version**

`cargo tree | grep tokio`

```
└── tokio v1.19.0
    └── tokio-macros v1.8.0 (proc-macro)
```

**Platform**

`Linux <hostname> 5.15.39_1 tokio-rs/tokio#1 SMP Fri May 13 11:39:37 UTC 2022 x86_64 GNU/Linux`

**Description**

Between this version...

```
tokio = { version = "1.18.2", features = ["signal", "rt", "macros"] }
```

...and this version...

```
tokio = { version = "1.19.0", features = ["signal", "rt", "macros"] }
```

...using `log v0.4.17`, the behavior of the sample program below's logging has changed:

```rust
mod logger {
    use log::{LevelFilter, Log, Metadata, Record};

    static LOGGER: Logger = Logger;

    pub struct Logger;

    impl Log for Logger {
        fn enabled(&self, _: &Metadata) -> bool {
            true
        }

        fn log(&self, record: &Record) {
            eprintln!("{}: {}", record.level(), record.args());
        }

        fn flush(&self) {}
    }

    pub fn init() {
        log::set_logger(&LOGGER).map(|()| log::set_max_level(LevelFilter::Trace)).unwrap();
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    logger::init();
}
```

Before, in 1.18.2, it doesn't print anything, but in 1.19.0, it logs this:

```console
$ cargo run
TRACE: deregistering event source from poller

$ cargo run --release
TRACE: deregistering event source from poller
```

This only happens with the "signal" feature enabled.

**Comment by Darksonn** [comment]
Well, I've transferred it to mio's issue tracker. @Thomasdezeeuw can decide whether it is a bug or not.

**Comment by Thomasdezeeuw** [comment]
@and-nissa what is the problem here? More logging output? That line has been in Mio 3 years, the only change it seems is that the signal internals of Tokio are now deregistered in 1.19.

**Comment by and-nissa** [comment]
Okay, thanks for the info, it's fine to close this.
Mainly, I want to make sure that this is not unexepected behavior, or that there wasn't a policy that tokio/deps don't log to the same place an application could be logging to.

**Comment by Thomasdezeeuw** [comment]
My policy, not necessarily that of Tokio or Mio, is that `debug` and `trace` logging in libraries is fine, anything about `info` should be done by the `main` crate. The only exception being `error` if it can't be returned to the user (e.g. failing to close a file on drop).
