### ISSUE TITLE
Why is IoSource not public?

### ISSUE THREAD

**Issue by daniel-brenot-apcapital** [tokio-rs/mio#1583]
Your docs show how IoSource can allow for using something cross platform as a IoSource, yet the module itself is inaccessible. Why not open this module so that other libraries can use it? I'm working on adding async support to zmq sockets, but i need to use IoSource to do so. Am i missing something?

**Comment by Thomasdezeeuw** [comment]
See https://github.com/tokio-rs/mio/issues/1460. You can use `SourceFd` on Unix and you'll need to wrap of the types in the `net` module to support Windows.

**Comment by daniel-brenot-apcapital** [comment]
I only have a file descriptor to work with, even on windows. The net module provides various streams, none of which fit what i need to use to make this library work as far as i can tell.

**Comment by daniel-brenot-apcapital** [comment]
Also according to the docs, IoSource was supposed to bridge the gap for the various Operating systems. This is one of the cases where i need it in order to make the library work

**Comment by Thomasdezeeuw** [comment]
Have you read my comment in https://github.com/tokio-rs/mio/issues/1460#issuecomment-782730946? On Windows `IoSource` doesn't support any more types than Mio already exposes.

**Comment by daniel-brenot-apcapital** [comment]
I don't understand what you mean by that. TcpStream, UdpSocket and TcpListener are each implementations of IoSource, I wanted to add another implementation of it using something other than those three. How is there any other types mio exposes i can use if none of those three can be used.

**Comment by daniel-brenot-apcapital** [comment]
I read what you mentioned about AFD. Does it really only support those three types? ZeroMQ can use tcp as well, but it may use other ways of connecting over the network. If it doesn't, then that's very unfortunate, as i've seen libraries for older versions of mio use a file descriptor for a zeromq socket to wake a task and it seemed to work fine there.

**Comment by Thomasdezeeuw** [comment]
> I read what you mentioned about AFD. Does it really only support those three types?

Yes, it only support TCP, UDP and UDS. I'm afraid that a limitation of AFD, nothing we can do about it.

>  ZeroMQ can use tcp as well, but it may use other ways of connecting over the network. If it doesn't, then that's very unfortunate, as i've seen libraries for older versions of mio use a file descriptor for a zeromq socket to wake a task and it seemed to work fine there.

You can do that with `SourceFd` on Unix. I'm afraid no generic implementation exists for Windows. If you're using a raw fd/socket you can check `SO_DOMAIN` and convert into the correct `mio::net` type based on the value.

**Comment by hawkw** [comment]
@daniel-brenot-apcapital you may also want to refer to https://github.com/tokio-rs/mio/issues/281#issue-107418148

**Comment by daniel-brenot-apcapital** [comment]
I had read the comment

> > I read what you mentioned about AFD. Does it really only support those three types?
> 
> Yes, it only support TCP, UDP and UDS. I'm afraid that a limitation of AFD, nothing we can do about it.
> 
> > ZeroMQ can use tcp as well, but it may use other ways of connecting over the network. If it doesn't, then that's very unfortunate, as i've seen libraries for older versions of mio use a file descriptor for a zeromq socket to wake a task and it seemed to work fine there.
> 
> You can do that with `SourceFd` on Unix. I'm afraid no generic implementation exists for Windows. If you're using a raw fd/socket you can check `SO_DOMAIN` and convert into the correct `mio::net` type based on the value.

This answers my question better. Thank you.
