### ISSUE TITLE
Solution for when not using TcpStream, UdpSocket or TcpListener

### ISSUE THREAD

**Issue by daniel-brenot-apcapital** [tokio-rs/mio#1584]
I'm trying to add async support to a wrapper for a c library that returns file descriptors from the system. This library works on windows and linux, so using SourceFd is out of the question, and it is none of the three types mentioned in the title of this issue, so none of those work.

I asked about using IoSource in another issue, but it was immediately closed so i needed to open a new issue to further expand upon my question.

Is IoSource not cross platform? It seems to work with both raw sockets and file descriptors, so I see no reason why not to have the type public so developers may use it to support network types other than tcp and udp. Am I missing something here?

**Comment by Thomasdezeeuw** [comment]
Really no need to open a new issue, since it's the same as https://github.com/tokio-rs/mio/issues/1583. Please read https://github.com/tokio-rs/mio/issues/1460#issuecomment-782730946.

**Comment by daniel-brenot-apcapital** [comment]
I opened a new issue because you closed the old one without having a conversation about the topic. Please wait for the discussion to be finished before closing an issue, or people will assume you aren't going to respond.

**Comment by Thomasdezeeuw** [comment]
Your initial question (why is IoSource not public?) was answered so I closed the issue. However you can always add comments to a closed issue.

**Comment by daniel-brenot-apcapital** [comment]
Whether you answered the question or not, it's better form in a public space like this to ensure that the person who asked the question is satisfied with the answer. At the very least, waiting until they give some reply. You answered and then immediately closed when I had a follow up question. The issue is resolved now, but I would have appreciated waiting until I responded, or at least a couple hours before closing the issue.

**Comment by Noah-Kennedy** [comment]
@daniel-brenot-apcapital Closing an issue like Thomas did here doesn't mean that the conversation is shut down, you can still ask questions on a closed issue. It just means that this thread doesn't represent a task for contributors and maintainers to take action on. Closing this is a courtesy to those individuals.

Plenty of maintainers still get notifications when someone posts on a closed issue btw, so closing an issue doesn't mean the conversation is lost.
