### ISSUE TITLE
is there a method like events.len() or events.count()

### ISSUE THREAD

**Issue by githik999** [tokio-rs/mio#1587]
there is a method events.is_empty()  but can i get the numbers of the events?

sorry if i have miss something 

i can't find it in the docs

**Comment by githik999** [comment]
[carllerche](https://github.com/carllerche) commented [on Aug 23, 2017](https://github.com/tokio-rs/mio/pull/713#issuecomment-324337893)

Ah, specifically I do not want the exact size to be exposed. This allows the iterator to skip or insert events during iteration.

---------------------------------------
have the circumstances change now  today at 2022?

if not i will just close this issue and count it outside my self

**Comment by Thomasdezeeuw** [comment]
@githik999 you can use [`events.into_iter().count()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.count).

**Comment by githik999** [comment]
@Thomasdezeeuw  thanks! great help
