### ISSUE TITLE
tcp_server example can only receive 4096 bytes

### ISSUE THREAD

**Issue by npuichigo** [tokio-rs/mio#1619]
I use `nc 127.0.0.1 9000` to send as many data as possible, but the tcp_server can only receive 4096 bytes, regardless of the buffer size

**Comment by Thomasdezeeuw** [comment]
Could you provide some more information @npuichigo. Maybe the code your using? Is your buffer larger then 4kb?

**Comment by Darksonn** [comment]
This sounds like the same issue as the one discussed [here](https://users.rust-lang.org/t/reading-more-than-4096-bytes-from-a-unixstream/81493).

**Comment by npuichigo** [comment]
@Darksonn thanks for the information there.
