### ISSUE TITLE
Replace `log` with `tracing`?

### ISSUE THREAD

**Issue by nylonicious** [tokio-rs/mio#1622]
Since `tokio` is slowly adopting `tracing` for logging, it'd be great if `mio` used `tracing` as well. For smaller projects that just depend on `tokio` and `hyper` for example it'd not pull `log` in. 

If replacing `log` would not be a good change maybe putting logging behind feature flag be better?

**Comment by Thomasdezeeuw** [comment]
I think this is going to be a no without further argument in favour of tracing. All message created by the log crate can be caught by the tracing crate, not vice versa, so this would be a breaking change with little to no argument in favour of tracing (at the moment).

**Comment by nylonicious** [comment]
That's understandable, thanks for the answer.
