### ISSUE TITLE
Add .set_quickack() to TcpStream

### ISSUE THREAD

**Issue by serzhiio** [tokio-rs/mio#1628]
I'd suggest to add 
`    pub fn set_quickack(&self, quickack: bool) -> io::Result<()> {
        self.inner.set_quickack(true)
    }`

**Comment by Thomasdezeeuw** [comment]
Mio is following the same API as std lib, for more socket configuration please use the socket2 library.

**Comment by serzhiio** [comment]
My bad, just realized that this is only Nightly feature.
https://doc.rust-lang.org/src/std/os/net/tcp.rs.html#63-65

**Comment by Thomasdezeeuw** [comment]
> My bad, just realized that this is only Nightly feature. https://doc.rust-lang.org/src/std/os/net/tcp.rs.html#63-65

I see it's also an Linux/Android specific feature so I don't will add it to Mio even if it wasn't nightly only. But it's very welcome in socket2 though.
