### ISSUE TITLE
Expose send/recv buffer sizes?

### ISSUE THREAD

**Issue by vis2k** [tokio-rs/mio#1633]
Hi, I am using mio + UDP for a high scale server application.
Is there any way to increase the socket's send / recv buffer sizes (SO_RECVBUF / SO_SNDBUF)?
Regular sockets do allow it: https://docs.rs/socket2/latest/socket2/struct.Socket.html#method.recv_buffer_size

I think that would be extremely useful :)

**Comment by vis2k** [comment]
similar discussion: https://github.com/vectordotdev/vector/issues/5127

**Comment by Thomasdezeeuw** [comment]
Mio follows the std lib API, use socket2 for this.

**Comment by vis2k** [comment]
> Mio follows the std lib API, use socket2 for this.

Thanks for the reply. 
Could you elaborate what this means? Am I supposed to cast mio's socket to 'socket2' somehow and then call the function?

**Comment by Thomasdezeeuw** [comment]
> > Mio follows the std lib API, use socket2 for this.
> 
> Thanks for the reply. Could you elaborate what this means? Am I supposed to cast mio's socket to 'socket2' somehow and then call the function?

Take a look at [`socket::SockRef`](https://docs.rs/socket2/latest/socket2/struct.SockRef.html) I made for this exact use case.

**Comment by vis2k** [comment]
> > > Mio follows the std lib API, use socket2 for this.
> > 
> > 
> > Thanks for the reply. Could you elaborate what this means? Am I supposed to cast mio's socket to 'socket2' somehow and then call the function?
> 
> Take a look at [`socket::SockRef`](https://docs.rs/socket2/latest/socket2/struct.SockRef.html) I made for this exact use case.

thanks. if anyone else has this problem, here's how to do it:
```rust
    let s2 = socket2::SockRef::from(socket); // from mio UdpSocket
    let current = s2.send_buffer_size().unwrap();
    s2.set_send_buffer_size(size).unwrap();
```
