### ISSUE TITLE
Continue or break while would_block error in tcpStream read loop?

### ISSUE THREAD

**Issue by barbedarhl** [tokio-rs/mio#1641]
This is tcp-server example,  would_block maybe occur after OK(n)，and previously read bytes will be dropped due to would_block break. Is it possible to continue? Is would_block final state of the tcpstream read operation?
```rust
loop {
    match connection.read(&mut received_data[bytes_read..]) {
        Ok(0) => {
            // Reading 0 bytes means the other side has closed the
            // connection or is done writing, then so are we.
            connection_closed = true;
            break;
        }
        Ok(n) => {
            bytes_read += n;
            if bytes_read == received_data.len() {
                received_data.resize(received_data.len() + 1024, 0);
            }
        }
        // Would block "errors" are the OS's way of saying that the
        // connection is not actually ready to perform this I/O operation.
        Err(ref err) if would_block(err) => break,
        Err(ref err) if interrupted(err) => continue,
        // Other errors we'll consider fatal.
        Err(err) => return Err(err),
    }
}
```

**Comment by Thomasdezeeuw** [comment]
> This is tcp-server example, would_block maybe occur after OK(n)，and previously read bytes will be dropped due to would_block break. Is it possible to continue? Is would_block final state of the tcpstream read operation?

I'm not entirely sure what you mean with your first question. But to answer the second one, no a `WouldBlock` error is not the final state of a `TcpStream`, it simply means that *currently* all bytes are read. So for example the peer of the connection send an entire request and is now waiting for a response. If a read call returns `Ok(0)` it means all bytes are read and the peer is not going to send more.

**Comment by barbedarhl** [comment]
> 

I have a very simple self-defined protocol just like this:
|magic_code|body_length|body|
Client uses body_length 4bytes to tell the server how many bytes need to read. Some very rarely would_block error occurs while server have not read the entire body bytes, for example, body_length is 4000, but server only read 1500 bytes from tcpStream and meanwhile would_block error returned by tcpStream.read().

Is this supposed that client did not write entire protocol body bytes?

**Comment by Thomasdezeeuw** [comment]
> I have a very simple self-defined protocol just like this: |magic_code|body_length|body| Client uses body_length 4bytes to tell the server how many bytes need to read. Some very rarely would_block error occurs while server have not read the entire body bytes, for example, body_length is 4000, but server only read 1500 bytes from tcpStream and meanwhile would_block error returned by tcpStream.read().
> 
> Is it supposed that client did not write the entire protocol body bytes?

It is always possible that not the entire request can be read in a single `read` call. It may be that the user didn't send the entire request, but it may also be that kernel split up the buffers and only returned one. You should always be ready for short reads and `WouldBlock` "errors", these are always possible. The solution is pretty simple though, put a (non-blocking) loop around the read to ensure your the entire request (do put in a limit! Don't want to read 1TB of data into your memory).
