### ISSUE TITLE
Master doc page out of date?

### ISSUE THREAD

**Issue by atouchet** [tokio-rs/mio#1652]
https://tokio-rs.github.io/mio/doc/mio/

This shows the latest version as being 0.8.0. Is this not being updated?

**Comment by Thomasdezeeuw** [comment]
I don't think so. Are you using it? Or can we remove it from the readme?

**Comment by atouchet** [comment]
I am not using it, I just noticed it when I happened to click the link. I don't know if it should be removed or not.
