### ISSUE TITLE
Exposing `AsRawHandle` on `Registry`

### ISSUE THREAD

**Issue by h33p** [tokio-rs/mio#1669]
It appears that while Unix platforms expose `AsRawFd`, there is no Windows equivalent. There already is `AsRawHandle` implementation [in `CompletionPort`](https://github.com/tokio-rs/mio/blob/master/src/sys/windows/iocp.rs#L141), it just needs to be propagated up the chain.

**Comment by Thomasdezeeuw** [comment]
Do you need this for something specifically? Because as far as I'm aware we currently expose types for all support kinds of fds and operations supported by AFD/IOCP (as Mio uses it).

**Comment by h33p** [comment]
Primarily, I'd want to be able to wait for readiness of the IOCP outside mio.

There's an idea I'm experimenting with at the moment. I have a completion IO lib that should be able to be plugged into different kinds of executors.

You have a future that issues I/O requests, and a "backend" that processes them. You have 3 options for how the backend is implemented:
1. Backend itself polls the future to completion - you get a full async executor here.
2. Backend works on the side as a secondary thread or a blocking task - now you possibly run into thread communication bottlenecks.
3. Backend exposes a handle that can be then polled for readiness by the parent executor.

I don't have hard numbers, but 3 seems like the most effective solution. On Linux, if you have a `io_uring` queue, you can plug its fd in a `epoll` system, or even another `io_uring` queue, and wait for multiple queues simultaneously.

I'm not so knowledgeable in windows side of things, and from what I saw, while you technically can `WaitForSingleObject` on a IOCP handle, [it's undocumented, unsupported, and doesn't have stable behavior](https://stackoverflow.com/questions/39602908/waitforsingleobject-on-a-completion-port), but I think you can wait for it with `GetQueuedCompletionStatus`, without removing events from the queue by passing null `lpOverlapped` (unless I'm misreding the docs). So I thought exposing raw handle to iocp would make sense.

**Comment by h33p** [comment]
Okay, no, I'm reading more into this and this is not what I need, and exposing the handle to iocp is potentially dangerous, because the code assumes a valid pointer is an instance of `Overlapped`. What I think I'd need is ability to set `hEvent` of OVERLAPPED, and basically having such structure set for everything sent to IOCP.

**Comment by notgull** [comment]
It might be worth it to just add an option to wait on a waitable handle to `mio`.

**Comment by Thomasdezeeuw** [comment]
> It might be worth it to just add an option to wait on a waitable handle to `mio`.

I don't remember the details, but if I remember correctly using the handle directly combined with the way Mio uses is quite difficult to use correctly as @h33p also found out, so I rather not add it with a good use case for it.
