### ISSUE TITLE
build failed with wasm-pack

### ISSUE THREAD

**Issue by HomyeeKing** [tokio-rs/mio#1671]
a lot of errors including E0412, E0425, E0432, E0433, E0599.
![image](https://github.com/tokio-rs/mio/assets/49113249/bfd97970-298c-4987-a190-93d7301d3650)

**Comment by Thomasdezeeuw** [comment]
Mio doesn't support WASM.

Also see https://github.com/tokio-rs/mio/issues/1346 and https://github.com/tokio-rs/mio/issues/642.
