### ISSUE TITLE
Decide MSRV for v1

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1732]
Currently I'm bumping it to v1.74 so we can use all the features we want. Once we're close to an actual release we should make it as low as possible which having to change the code (too much).

**Comment by jkarneges** [comment]
Some distro numbers:

* Oldest Ubuntu LTS: [1.70](https://packages.ubuntu.com/focal/rustc)
* Debian stable: [1.63](https://packages.debian.org/stable/rust/rustc)
