### ISSUE TITLE
Use rustix instead of libc

### ISSUE THREAD

**Issue by notgull** [tokio-rs/mio#1735]
[`rustix`](https://github.com/bytecodealliance/rustix) is a system call wrapper that wraps raw system calls on Linux and `libc` on other platforms. It would allow `mio` to refactor out error handling and unsafe syscall handling code from its codebase. More materialistically, `rustix` bypasses `libc` for Linux system calls. In some cases, this can allow system calls to be directly inlined into their calling functions, saving instructions and increasing execution speed.

Its MSRV is 1.63, but as the MSRV [was just bumped to 1.74](https://github.com/tokio-rs/mio/issues/1732) this shouldn't be an issue.

Rel: https://github.com/tokio-rs/mio/issues/1588

**Comment by Darksonn** [comment]
This doesn't seem necessary to me. We generally try pretty hard to not add new dependencies to Tokio, especially ones that are not under the Tokio org.
