### ISSUE TITLE
Document MSRV policy

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1737]
Currently the goal is:
* 1.x will have the same MSRV.
* When bumping the MSRV we bump 1.x to 1.x+1

One thing to consider is dependencies and their MSRV bumps. For I think we should just describe the issue in the policy and see if it becomes a problem and tackle it then (similar to what we did with the `log` crate in v0.8).

Related https://github.com/tokio-rs/mio/issues/1732

**Comment by Darksonn** [comment]
> One thing to consider is dependencies and their MSRV bumps. 

Tokio's current policy here is that for the latest version, we require all dependencies to have a matching MSRV, and we will remove the dependency or bump the MSRV if a dependency increases it past that.

Tokio's current policy for LTS releases is that we try to do the same, but that we don't guarantee it:

> Note that although we try to avoid the situation where a dependency transitively increases the MSRV of Tokio, we do not guarantee that this does not happen. However, every minor release will have some set of versions of dependencies that works with the MSRV of that minor release.
