### ISSUE TITLE
`syscall!` macros hide unsafe code

### ISSUE THREAD

**Issue by djkoloski** [tokio-rs/mio#1753]
While auditing mio for Fuchsia, I usually grep for `unsafe` and audit the unsafe blocks. However, the `syscall!` macros for [unix](https://github.com/tokio-rs/mio/blob/08ee541bf00c2cc81f9acc5486851ca1d59c25a3/src/sys/unix/mod.rs#L5) and [windows](https://github.com/tokio-rs/mio/blob/08ee541bf00c2cc81f9acc5486851ca1d59c25a3/src/sys/windows/mod.rs#L23) include their own `unsafe { .. }` blocks wrapping the underlying unsafe functions. This makes it harder to ensure that every syscall is properly justified. Removing the unsafe blocks from the macro would help solve this problem; whoever uses the macro would need to wrap it in `unsafe { .. }` and provide a safety comment at the usage site.

**Comment by Thomasdezeeuw** [comment]
System calls are inherintly unsafe, I don't think add `unsafe` blocks and comments everywhere is going to help. Furthermore there are plenty for system calls that aren't really unsafe. For example `socket(2)`, it can't do any dangerous. Of course things like `read(2)` and `write(2)` can cause you read/write arbitrary memory, but most of those calls we delegated to std lib.

**Comment by Thomasdezeeuw** [comment]
Closing because I don't think we need to do anything further here.
