### ISSUE TITLE
Walker failure on Linux

### ISSUE THREAD

**Issue by lbl8603** [tokio-rs/mio#1764]
```
// mio = {version ="0.8.10",features=["os-poll","net"]}
use mio::{net::TcpListener, Events, Interest, Poll, Registry, Token, Waker};

const SERVER: Token = Token(0);
const NOTIFY: Token = Token(1);
fn main() {
    let mut tcp_listener = TcpListener::bind("0.0.0.0:0".parse().unwrap()).unwrap();
    let mut poll = Poll::new().unwrap();
    poll.registry()
        .register(&mut tcp_listener, SERVER, Interest::READABLE).unwrap();
    let stop = Waker::new(poll.registry(), NOTIFY).unwrap();
    std::thread::spawn(move||{
        std::thread::sleep(std::time::Duration::from_secs(1));
        stop.wake().unwrap();
    });
    let mut events = Events::with_capacity(32);
    println!("poll");
    poll.poll(&mut events, None).unwrap();
    println!("events={:?}",events);
}
```
The program can exit on Windows, but not on Linux

uname -a 
Linux DESKTOP-CJIIOBE 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Thomasdezeeuw** [comment]
@lbl8603 did you mean to close this issue?

**Comment by lbl8603** [comment]
Using Walker across threads requires Arc wrapping

**Comment by Thomasdezeeuw** [comment]
> Using Walker across threads requires Arc wrapping

No, you can send a `mio::Waker` without an `Arc` across a thread. But if you want to share it with multiple threads then an `Arc` is an easy solution. But you can use any shared data structure really.

**Comment by lbl8603** [comment]
Need to retain the Walker reference until the poll thread is awakened.Otherwise, the question I raised will arise

**Comment by lbl8603** [comment]
https://docs.rs/mio/0.8.11/mio/struct.Waker.html#examples

**Comment by Thomasdezeeuw** [comment]
> Need to retain the Walker reference until the poll thread is awakened.Otherwise, the question I raised will arise

That's documented: https://docs.rs/mio/0.8.11/mio/struct.Waker.html#notes.
