### ISSUE TITLE
Crash at  GetQueuedCompletionStatusEx in dll

### ISSUE THREAD

**Issue by terakilobyte** [tokio-rs/mio#1769]
We're developing an ODBC Driver that wraps our Rust Driver. So far, everything works most of the time, but we're seeing crashes from [this function]( https://github.com/tokio-rs/mio/blob/master/src/sys/windows/iocp.rs#L88-L116). This seems to happen when our driver dll is loaded/unloaded very quickly by the OS, or after repeatedly loading and unloading.

Unfortunately the dump files are too big to attach to the issue.

**Comment by Thomasdezeeuw** [comment]
Can you provide some more details here? When you say crash, due to what? A segfault, explicit abort, something else? Really any error message, logs or code to reproduce would be nice.

**Comment by terakilobyte** [comment]
Thanks for the response. Sorry for the light description, as I said, the dump file is too big to attach.

The specific error is `Exception thrown at 0x000000000144DC04 in odbcsql.exe: 0xC0000005: Access violation executing location 0x000000000144DC04.` odbcsql is a small c++ app that exercises the driver through the odbc manager by repeatedly loading and unloading it via allocating env and dbc handles, connecting (which triggers our underlying driver to asynchronously connect to the database), and then disconnecting and freeing the handles.


The error points to:
```
pub fn get_many<'a>(
        &self,
        list: &'a mut [CompletionStatus],
        timeout: Option<Duration>,
    ) -> io::Result<&'a mut [CompletionStatus]> {
        debug_assert_eq!(
            mem::size_of::<CompletionStatus>(),
            mem::size_of::<OVERLAPPED_ENTRY>()
        );
        let mut removed = 0;
        let timeout = duration_millis(timeout);
        let len = cmp::min(list.len(), <u32>::max_value() as usize) as u32;
        let ret = unsafe {
            GetQueuedCompletionStatusEx( // error in windbg points to this call
                self.handle.raw(),
                list.as_ptr() as *mut _,
                len,
                &mut removed,
                timeout,
                0,
            )
        };

        if ret == 0 {
            Err(io::Error::last_os_error()) // error in visual studio points to this call
        } else {
            Ok(&mut list[..removed as usize])
        }
    }
```

**Comment by Thomasdezeeuw** [comment]
I'm no Windows expert, `Access violation`, according to the internet, is effectively using memory you can't access. Is the handle or `list` somehow invalid? I would expect Windows to return an error though, not crash. Any chance we can get something of a backtrace? I'm really struggling to help here.

**Comment by terakilobyte** [comment]
I apologize, I thought I had closed this issue last night but never hit comment!

It turns out this is *not* an issue with mio, or tokio. I was able to reproduce the issue exactly and resolve it as well. Turns out, our dependency initialized a tokio runtime via `lazy_static`, and when the dll unloads, this causes issues.
