### ISSUE TITLE
TCP listener via wasm

### ISSUE THREAD

**Issue by maxwellflitton** [tokio-rs/mio#1779]
When I try and compile the TCP example in the readme to `wasm32` if get the following:

```
let mut server = TcpListener::bind(addr)?;
                            ^^^^ function or associated item not found in `TcpListener`
```
and 

```
let mut client = TcpStream::connect(addr)?;
                           ^^^^^^^ function or associated item not found in `TcpStream`
```

A normal cargo build works as I have the `"net"` feature. Are there any code examples of getting TCP working with `wasmtime`?

**Comment by Thomasdezeeuw** [comment]
Wasm doesn't support creation of sockets, Mio can't change that. However your wasm runtime might be able to create them for you, see https://github.com/tokio-rs/mio/blob/master/examples/tcp_listenfd_server.rs.
