### ISSUE TITLE
Compiling mio in AIX fails

### ISSUE THREAD

**Issue by ayappanec** [tokio-rs/mio#1782]
Compiling mio in AIX fails with the below error., 
`rustc --crate-name mio --edition=2018 /.cargo/registry/src/index.crates.io-d11c229612889eed/mio-0.8.11/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="net"' --cfg 'feature="os-ext"' --cfg 'feature="os-poll"' -C metadata=6daf56d29685c1b2 -C extra-filename=-6daf56d29685c1b2 --out-dir /tmp/pip-install-2doeq8db/tokenizers_a6dcd574fc864cb793f0985f2a16d7f5/target/release/deps -C strip=debuginfo -L dependency=/tmp/pip-install-2doeq8db/tokenizers_a6dcd574fc864cb793f0985f2a16d7f5/target/release/deps --extern libc=/tmp/pip-install-2doeq8db/tokenizers_a6dcd574fc864cb793f0985f2a16d7f5/target/release/deps/liblibc-3a5102201a3aa852.rmeta --cap-lints allow -C link-arg=-bbigtoc -L/opt/freeware/lib -D_ALL_SOURCE -lpython3.9
`
 ```
 error[E0432]: unresolved imports `self::selector::event`, `self::selector::Event`, `self::selector::Events`, `self::selector::Selector`
    --> /.cargo/registry/src/index.crates.io-d11c229612889eed/mio-0.8.11/src/sys/unix/mod.rs:18:37
     |
  18 |     pub(crate) use self::selector::{event, Event, Events, Selector};
     |                                     ^^^^^  ^^^^^  ^^^^^^  ^^^^^^^^ no `Selector` in `sys::unix::selector`
     |                                     |      |      |
     |                                     |      |      no `Events` in `sys::unix::selector`
     |                                     |      no `Event` in `sys::unix::selector`
     |                                     no `event` in `sys::unix::selector`
     |
     = help: consider importing this module instead:
             crate::event
  note: found an item that was configured out
    --> /.cargo/registry/src/index.crates.io-d11c229612889eed/mio-0.8.11/src/sys/unix/selector/mod.rs:21:30
     |
  21 | pub(crate) use self::epoll::{event, Event, Events, Selector};
     |                              ^^^^^
  note: found an item that was configured out
    --> /.cargo/registry/src/index.crates.io-d11c229612889eed/mio-0.8.11/src/sys/unix/selector/mod.rs:35:29
     |
  35 | pub(crate) use self::poll::{event, Event, Events, Selector};
     |                             ^^^^^
  note: found an item that was configured out
    --> /.cargo/registry/src/index.crates.io-d11c229612889eed/mio-0.8.11/src/sys/unix/selector/mod.rs:70:31
     |
  70 | pub(crate) use self::kqueue::{event, Event, Events, Selector};
     |                               ^^^^^
     = help: consider importing this struct through its public re-export instead:
             crate::event::Event
```

**Comment by Thomasdezeeuw** [comment]
AIX is not supported.

**Comment by Thomasdezeeuw** [comment]
See https://github.com/tokio-rs/mio?tab=readme-ov-file#platforms for the supported platforms.

**Comment by ayappanec** [comment]
Noted. 
AIX has pollset which is kind of similar to epoll in Linux.  I will check what it takes to make it use by mio.

**Comment by ecnelises** [comment]
I had initial patch for pollset: https://github.com/tokio-rs/mio/pull/1620 . But AIX pollset handle does not DUPFD (`fcntl(ps, F_DUPFD_CLOEXEC, 3)`), which is quite a fundamental issue.

**Comment by Thomasdezeeuw** [comment]
A pr to add support for AIX would be considered, but I'm closing this for now since there seems to be no active progress on it.
