### ISSUE TITLE
README mentions a v1 that doesn't exist

### ISSUE THREAD

**Issue by bew** [tokio-rs/mio#1792]
Hello!

While trying to use `mio`, using `mio = "1"` in dependencies fails saying that there is no v1 🤔
Similarly there is a link for the docs of a v1 leading a 404 page.

**Comment by Thomasdezeeuw** [comment]
Mio v0.8 is currently the most recent release, the `master` branch contains the code for v1, which is currently not released yet. Take a look the `v0.8.x` if you want to look at the v0.8 code.

**Comment by bew** [comment]
Ah, didn't occur to me ><, thank you 👍

**Comment by Thomasdezeeuw** [comment]
Resolved btw as v1 has just been released.

**Comment by bew** [comment]
👍 I see the tag exists, but the latest github release is still v0.8, will you do a GH v1 release?

**Comment by Thomasdezeeuw** [comment]
I stopped doing GitHub releases. The changelog has the relevant changes.
