### ISSUE TITLE
mio does not build for aarch64-apple-visionos

### ISSUE THREAD

**Issue by coolbluewater** [tokio-rs/mio#1805]
mio does not build for the newly added Rust target `aarch64-apple-visionos`.

For the exact build error, please see https://github.com/tokio-rs/tokio/issues/6627.

**Comment by Thomasdezeeuw** [comment]
See https://github.com/tokio-rs/mio/pull/1795, it was just merged :)

**Comment by coolbluewater** [comment]
@Thomasdezeeuw, could you please release so that downstream (tokio) can pick this up?

**Comment by Thomasdezeeuw** [comment]
No yet, it will make it's way into v1, which we're working on.

**Comment by coolbluewater** [comment]
What is the ETA on this? If it is too far, is it possible to backport this build fix into a release?

**Comment by Thomasdezeeuw** [comment]
No ETA, it's done when it's done.

**Comment by coolbluewater** [comment]
This is blocking visionos development with rust. It needs to be backported and released.
Which branch should a PR be for? 0.8.x?

**Comment by Thomasdezeeuw** [comment]
Just released v1 with support for visionOS.

**Comment by coolbluewater** [comment]
Appreciate it, thanks!
