### ISSUE TITLE
Why Wine 6.11+ support was dropped?

### ISSUE THREAD

**Issue by oblique** [tokio-rs/mio#1814]
I started reading #1444 after I saw that Wine is unsupported, then I found out that Wine 6.11 had a I fix for this and I was ready to open a PR for the readme. Then I saw #1505, which was reverted in #1596.

What was the reason on removing something that works from the supported list? And what is needed to add it back?

**Comment by oblique** [comment]
Just tested Wine 9 and it works.

**Comment by Thomasdezeeuw** [comment]
People claimed Wine worked, we put put "we support Wine" in the readme. Then others claimed it didn't work, in a less then pleasant way, so we removed it. At this point, I want to see CI support (e.g. see https://github.com/tokio-rs/mio/pull/1637) before we add anything.

**Comment by Thomasdezeeuw** [comment]
If we ever want to claim we support Wine I first want CI support. Since that doesn't seem to be happening I'm going to close this for now, it can be reopened if someone is willing to put in the effort to finish #1637.
