### ISSUE TITLE
how to manage blocking writes?

### ISSUE THREAD

**Issue by ortuman** [tokio-rs/mio#1825]
👋  hello!

first of all, I want to clarify that I am new to the topic of async I/O, and I have a few questions about it. 

in the documentation for the `TcpStream::write` method ([ref](https://doc.rust-lang.org/nightly/std/io/trait.Write.html#tymethod.write)) the following is specified:

```
If this method consumed n > 0 bytes of buf it must return Ok(n). If the return value is Ok(n) then n must satisfy n <= buf.len().
```

If `n < buf.len()`, then I understand we are dealing with a partial write scenario. this raises the following question for me: should I expect that after this condition happens a _write ready_ event will subsequently be notified via poller?

and regarding:

```
a write which would otherwise block can be indicated through an Err variant.
```

Two possible ways to handle such a scenario come to mind:

1. save the buffer you want to write to attempt writing again once notified.
2. sleep for `n` ms (running on a thread pool) and try again.

which of these two options would make more sense (or have fewer drawbacks)?

thank you for your time, and congratulations on your work. 🙇

**Comment by Thomasdezeeuw** [comment]
> If `n < buf.len()`, then I understand we are dealing with a partial write scenario. this raises the following question for me: should I expect that after this condition happens a _write ready_ event will subsequently be notified via poller?

No, see https://docs.rs/mio/latest/mio/struct.Poll.html#draining-readiness.

> and regarding:
> 
> ```
> a write which would otherwise block can be indicated through an Err variant.
> ```
> 
> Two possible ways to handle such a scenario come to mind:
> 
>     1. save the buffer you want to write to attempt writing again once notified.
> 
>     2. sleep for `n` ms (running on a thread pool) and try again.
>
> which of these two options would make more sense (or have fewer drawbacks)?

Option 1 is the right one. This can be achieved, for example, by using [`Future`s](https://doc.rust-lang.org/std/future/trait.Future.html) or [async functions](https://doc.rust-lang.org/std/keyword.async.html) (and see the async book https://rust-lang.github.io/async-book/).


Don't do 2, than use blocking I/O on a thread pool, it will be more efficient.

**Comment by ortuman** [comment]
Thank you for the clarification @Thomasdezeeuw
