### ISSUE TITLE
Is it possible to add support for HaikuOS ?

### ISSUE THREAD

**Issue by ds2k5** [tokio-rs/mio#1832]
Hi,
is it possible to add support for HaikuOS ?

https://www.haiku-os.org/

Thanks

**Comment by Thomasdezeeuw** [comment]
Haiku should build, at least we do in our CI: https://github.com/tokio-rs/mio/blob/master/.github/workflows/ci.yml#L170. Have you tried it?

**Comment by ds2k5** [comment]
I had a tryed with tokio and had a build issue
will try soon.... an report

```

[dependencies]
chrono = "0.4.38"
current_platform = "0.2.0"
gettext-ng = "0.4.1"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde_json = "1.0.120"
sys-locale = "0.3.1"

```

**Comment by Thomasdezeeuw** [comment]
Closing based on lack of activity.
