### ISSUE TITLE
non-blocking epoll feature request

### ISSUE THREAD

**Issue by rgeary1** [tokio-rs/mio#1835]
For low latency networking, I want to spin-loop the epoll_wait.  The current design doesn't allow for this.  Perhaps extending the API with `poll.poll_nonblocking` would allow this to be implemented for the OSs which suppor it & without disrupting the existing API.

**Comment by Thomasdezeeuw** [comment]
I don't know what you mean with spin-looping `epoll_wait`. Calling `Poll::poll` without a timeout will wait until there is an event. But it will most likely deschedule the thread. I suppose you can call with a zero duration timeout. This can already be done with the current API: `Poll::poll(&mut events, some(Duration::ZERO))`.
