### ISSUE TITLE
Mio documentation fails to build due to wasm targets

### ISSUE THREAD

**Issue by Darksonn** [tokio-rs/mio#1845]
The [documentation on docs.rs][1] is [failing to build][2] with this error:
```text
error: Error loading target specification: Could not find specification for target "wasm32-wasi". Run `rustc --print target-list` for a list of built-in targets
```

[1]: https://docs.rs/crate/mio/1.0.3
[2]: https://docs.rs/crate/mio/1.0.3/builds/1568586

**Comment by Thomasdezeeuw** [comment]
`wasm32-wasi` is gone in the latest rustc, it's `wasm32-wasi-p1` I think

**Comment by joshka** [comment]
Can this be released?

**Comment by Thomasdezeeuw** [comment]
> Can this be released?

Preparing a new release: #1881.
