### ISSUE TITLE
v1.0.3 docs not building on docs.rs

### ISSUE THREAD

**Issue by jofas** [tokio-rs/mio#1849]
Docs.rs failed building version `1.0.3`  of mio: https://docs.rs/crate/mio/1.0.3 last time I checked (14th of December 2024). Looking at the [build logs](https://docs.rs/crate/mio/1.0.3/builds) revealed that for some reason `--target wasm32-wasi` is passed to `rustc`. But `wasm32-wasi` was [removed from nightly](https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html#timeline) on the 17th of October 2024. I haven't yet investigated where this argument comes from, to me it looks like docs.rs is trying to build some procedural macro for the deprecated/renamed `wasm32-wasi` target. If needed I can investigate further, but I wanted to raise the issue first in case someone already knows how to fix this.

**Comment by Darksonn** [comment]
This is #1845. We already fixed it, but I guess we should make another release to fix the docs.

**Comment by jofas** [comment]
Oops, only checked for open issues, my bad.
