### ISSUE TITLE
Build error with missing import `crate::sys::IoSourceState`

### ISSUE THREAD

**Issue by jaques-sam** [tokio-rs/mio#1850]
The error is well known and was already reported in 2021, I'm still encountering it with all latest versions (rust 1.83):
```bash
❯ c tree -p mio -i
mio v1.0.3
└── tokio v1.42.0
    ├── mysql_async v0.34.2
    │   └── prono v0.1.0 (/home/sam/Repos/own/prono)
    ├── prono v0.1.0 (/home/sam/Repos/own/prono)
    └── tokio-util v0.7.13
        └── mysql_async v0.34.2 (*)
```

```rust
error[E0432]: unresolved import `crate::sys::IoSourceState`
  --> /home/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/io_source.rs:14:5
   |
14 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`

error[E0432]: unresolved import `crate::sys::tcp`
  --> /home/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-1.0.3/src/net/tcp/listener.rs:19:17
   |
19 | use crate::sys::tcp::{bind, listen, new_for_addr};
   |                 ^^^ could not find `tcp` in `sys`
```

Can you please tell me how to get rid of this annoying error and why this isn't an open issue?
Thanks!

**Comment by jaques-sam** [comment]
So I already found the possible cause, sorry but this wasn't very clear from the build error :-(

When enabling Tokio, I should only enable those features: 
    sync
    macros
    io-util
    rt
    time

**Comment by dsx1986** [comment]
similar issue here, why this is the cause? @jaques-sam

**Comment by jaques-sam** [comment]
A very annoying which doesn't really tell us the reason...
See more here https://stackoverflow.com/a/77402099/2522849

**Comment by Darksonn** [comment]
It's because you're trying to use Tokio on wasm in an unsupported configuration.
