### ISSUE TITLE
Supporting Windows Job Objects

### ISSUE THREAD

**Issue by alexcrichton** [tokio-rs/mio#526]
We've recently added support to handle custom `HANDLE` objects with IOCP on Windows. This relies, however, on all completion notifications coming back with a mio-specific `Overlapped` type to ensure that dispatch happens appropriately.

Job Objects on Windows support IOCP where they can send notifications to a port. There's two major differences, however, from how today's I/O objects interact with IOCP:

* Association with a port is done through a custom job object API. This means that we'll have to expose the raw IOCP handle.
* IOCP notifications do not have an associated `OVERLAPPED` pointer specified by the user. Instead each type of notification has a particular `OVERLAPPED` value which may be some extra data payload.

The former is pretty easy to solve but the latter is much more difficult as it's a big architectural change to mio. It basically means that the only thing we have to dispatch on is a token, not an overlapped pointer like we did before. This means that we'd need to have some sort of token-based dispatch ahead of the overlapped-based dispatch. I'm unsure on how to do this in a performant fashion, however, so I'm opening an issue!

**Comment by dtacalau** [comment]
@Thomasdezeeuw please assign this issue to me, will start working on it.

**Comment by Thomasdezeeuw** [comment]
This is not going to block a v1.0 release.

**Comment by Thomasdezeeuw** [comment]
This has been open for four years without a solution, I think we have to say that using the current AFD based implementation we can't support this. If there is a reasonable solution to support more Window specific API please open a new issue
