### ISSUE TITLE
Poll.deregister() has no effect on Windows

### ISSUE THREAD

**Issue by rom1v** [tokio-rs/mio#633]
In an application, I sometimes need to deregister a socket, and register it later. In that case, the second `register()` fails on Windows.

I reproduced the problem in the following sample:

```rust
extern crate mio;
use std::net::{Ipv4Addr, SocketAddr};
use mio::{Ready, Poll, PollOpt, Token};

fn main() {
    let addr = SocketAddr::new(Ipv4Addr::new(127, 0, 0, 1).into(), 1234);
    let stream = mio::tcp::TcpStream::connect(&addr).unwrap();

    let poll = Poll::new().unwrap();

    poll.register(&stream, Token(0), Ready::readable(), PollOpt::level()).unwrap();
    poll.deregister(&stream).unwrap();
    poll.register(&stream, Token(0), Ready::readable(), PollOpt::level()).unwrap();

    println!("It works!");
}
```

It works on Linux, but fails on Windows:

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 87, message: "The parameter is incorrect." } }', src\libcore\result.rs:859

Interestingly, if we replace the last call to `register()` by `reregister()`, then it fails on Linux (as expected), but it works on Windows:

```rust
    poll.register(&stream, Token(0), Ready::readable(), PollOpt::level()).unwrap();
    poll.deregister(&stream).unwrap();
    poll.reregister(&stream, Token(0), Ready::readable(), PollOpt::level()).unwrap();
```

In fact, on Windows, it behaves exactly as if we didn't call `deregister()` at all:

```rust
    poll.register(&stream, Token(0), Ready::readable(), PollOpt::level()).unwrap();
    // poll.deregister(&stream).unwrap(); // ignored on Windows
    poll.register(&stream, Token(0), Ready::readable(), PollOpt::level()).unwrap();
```

**Comment by alexcrichton** [comment]
Yes htis is expected on Windows where `deregister` isn't supported on Windows, but it's supported on Linux.

**Comment by rom1v** [comment]
Hmm, so we cannot deregister? What's the expected usage on Windows, then? (we can't register new handles indefinitely without deregistering them)

**Comment by alexcrichton** [comment]
On Windows once you associate a handle with an IOCP object you can't undo that (AFAIK), so whenever you register an object it's permanently associated with that event loop.

**Comment by rom1v** [comment]
OK, thanks for the explanation. :+1:

I don't know Windows API, but I found this answer: https://stackoverflow.com/a/35373536/1987178

What do you think?

IMO we need a thin wrapper that exposes `deregister()` on Windows in some way.

**Comment by alexcrichton** [comment]
Sounds like a possibility yeah!

**Comment by In-line** [comment]
Maybe we can use `select call?

**Comment by carllerche** [comment]
@In-line we cannot use select on windows

**Comment by carllerche** [comment]
If this is still an issue, it probably can be fixed by tracking the necessary state on the windows side of things.

**Comment by SergejJurecko** [comment]
Yes it still an issue. 

This project has it implemented and it is a pretty simple solution: https://github.com/mitsuhiko/rust-listenfd/blob/89a37b36b749536b9cc079be2e1ac25f36b74b52/src/windows.rs#L56

I've tried and putting this in windows deregister call works and registering socket again later also works. I can create a PR if it is desired to implement it this way?

**Comment by Thomasdezeeuw** [comment]
@SergejJurecko a Windows rewrite is in the works (#1034), any chance you can try that?

**Comment by Thomasdezeeuw** [comment]
In Mio v0.7 registering after deregister is invalid, however *re*registering after deregistering is valid for which I added a test in #1043.

**Comment by Thomasdezeeuw** [comment]
I was incorrect in my previous comment, in Mio v0.7 *re*registering after deregister is invalid, however registering after deregistering is valid.
