### ISSUE TITLE
SocketAddr argument to UdpSocket methods

### ISSUE THREAD

**Issue by dtolnay** [tokio-rs/mio#667]
```rust
fn bind(addr: &SocketAddr) -> Result<UdpSocket>;
fn connect(&self, addr: SocketAddr) -> Result<()>;
```

One of these takes a &SocketAddr, the other takes SocketAddr by value. If possible, they should be consistent.

**Comment by bobbo** [comment]
I'd like to take a look at doing this.

`UdpSocket::connect()`, `UdpSocket::send_to()` and `TcpStream::connect()` take `SocketAddr` by ref, so that seems the most consistent way to go.

**Comment by asayers** [comment]
Or better yet, generalise `addr` to `ToSocketAddrs` like the equivalent libstd functions do. This way, it wouldn't even be a breaking change.
