### ISSUE TITLE
Consider getting rid of with-deprecated flag

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#710]
Aka, always include deprecated features. It's not really a safe flag to use in general, so it might be good to get rid of it.

**Comment by ahmedcharles** [comment]
Why isn't it safe to use? I just submitted a PR which ensure that the tests pass without that feature.

**Comment by carllerche** [comment]
Using it will break backwards compatibility... it's rarely what you want IMO and you definitely don't want to accidentally release a crate that doesn't depend on deprecated features.

Thoughts @alexcrichton?

**Comment by ahmedcharles** [comment]
If you have crate A with deprecated features, B without deprecated features and C, which uses A and B, aren't there two versions of mio that get used or only one? And if only one, which one?

**Comment by alexcrichton** [comment]
The risk here is that if I publish a crate to crates.io that disables default features of mio (disables this feature) then we'll break that crate as APIs are deprecated. That breakage isn't intentional!

I think we shouldn't remove it from the manifest, but we should remove all interpretation of the feature from the source.

**Comment by ahmedcharles** [comment]
After talking on IRC, it seems like the only issue is that when new items are added to the "with-deprecated" feature, it will break crates compiled without default features. That seems like the obvious/desired functionality, assuming the person building without default features actually knew that meant not getting deprecated functionality (i.e. a documentation issue).

For users of mio, the obvious non-breaking deprecation strategy is `#[deny(deprecated)]` (though, ironically, that also breaks their build on new deprecations), but they could simply `#[warn(deprecated)]` and just have warnings.

The primary benefit of using with-deprecated is the ability to test the crate without deprecated functionality while letting users continue to use that functionality by default. And given that `#[deny(deprecated)]` and `--no-default-features` have the same breakage implications, I don't see why removing the feature would be beneficial, given it's testing benefits.

Where would be the best place to document the intention behind with-deprecated, assuming you agree with my conclusion?

**Comment by alexcrichton** [comment]
I could personally go either way, I wouldn't advocate its removal but I also wouldn't advocate keeping it. If we just want to comment what's going on I'd probably to it in Cargo.toml next to the feature definition.

**Comment by Thomasdezeeuw** [comment]
The deprecated feature is gone.
