### ISSUE TITLE
mio::net::UdpSocket::connect() fails on windows with error 10014 (invalid pointer)

### ISSUE THREAD

**Issue by zetok** [tokio-rs/mio#721]
mio: 0.6.10
I also tried with latest git of mio and that too didn't work.

Fails with: https://ci.appveyor.com/project/zetok/tox/build/%2322
Error description on https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx

Location in test in which error happens: https://github.com/zetok/tox/blob/5fb8be384deb9b3e30c1c8fb18ed8ae4688be3cd/src/lib.rs#L76,L77

Edit: it works on linux

**Comment by alexcrichton** [comment]
Hm this wouldn't happen to be an ipv4/ipv6 mismatch would it? Where maybe the socket is bound to an ipv6 address and you're connecting to an ipv4?

**Comment by zetok** [comment]
Socket is bound to `::` and the connection is made to an IPv4 address, but I thought that it's supposed to work for both IPv4 and IPv6? At least it does work on Linux..

If it's not supposed to work like that, or it's platform-dependent thing, it would be good to document that somewhere.

**Comment by Thomasdezeeuw** [comment]
@zetok any chance you can try the new Windows implementation (#1034)? To see if this issue still exists?

**Comment by Thomasdezeeuw** [comment]
Closing this as solved after the Window rewrite.

PS. I don't think connection from an IPv4 to IPv6 works generally speaking.
