### ISSUE TITLE
Explain Tcp Error Event in doc

### ISSUE THREAD

**Issue by frehberg** [tokio-rs/mio#728]
in src/poll.rs TcpStream Error events are described a bit vague.

TCP-Error events are not errors as such, but  Out-Of-Band (OOB) signals from peer. 

An OOB-signal is like a marker in the TCP-stream and must be read from socket before continuing with usual payload.

Checking if the Marker has been reached:
 ioctl (fd, SIOCATMARK, &atmark);

Reading the marker
recv(fd, buffer, 1 /*just a single octet*/, MSG_OOB );

Afterwards, it is possible to continue reading 
(see https://github.com/frehberg/betcp/blob/master/src/rttcp.c)

In contrast, if the stream is closed by peer suddenly, this is indicated by a read-event and recv-function is  returning with number of bytes 0.

The documentation should be enhanced regarding the Tcp-Error event.

**Comment by Thomasdezeeuw** [comment]
@frehberg are there any concrete suggestions you have for the documentation? Since Mio mainly relays signals/events provided by the OS I don't know how much we should document it as it might change as we add other OSes. Currently only readable and writable indicators are cross-platform.

**Comment by frehberg** [comment]
That is too long ago, I have got to see how the docs are looking today, 

Just, TCP-Out-Of-Band  is part of the TCP-standard, that every OS implements. I did not check how the API of Rust/mio is looking today, but in 2017 I had the feeling that the API of Rust/mio did not incorporate this feature, neither did the Docs explain what an POLLERR event really means (it is not a communication error!!) 
Please give me some time to resync to this task ;)

The TCP-OOB feature is well documented here: http://www.masterraghu.com/subjects/np/introduction/unix_network_programming_v1.3/ch24lev1sec2.html

**Comment by Thomasdezeeuw** [comment]
#1037 drops most of the documentation about the non-cross-platforms indicators and instead refers to the OS specific documentation. That would (sort of) solve this.

**Comment by Thomasdezeeuw** [comment]
As #1037 is merged I'm going to close this. @frehberg if you want to add to the documentation it's always welcome.
