### ISSUE TITLE
Abstract API for  datagram/stream oriented transports

### ISSUE THREAD

**Issue by frehberg** [tokio-rs/mio#729]
API of Mio and Rust should support/differentiate two types/traits of protocols, datagram-oriented and stream-oriented. The API should abstract and get rid of names referring to  UDP or TCP.
UDP is just an incarnation of a datagram oriented protocol
TCP is just an incarnation of a stream oriented protocol.

An abstract API for datagram-oriented traffic and stream-oriented traffic would ease the integration of other protocols/transports such as CAN, SCTP, etc.

**Comment by carllerche** [comment]
Is this issue asking for an actual trait? Mio is trying to stick as close as possible to `std` for the socket API. As such, these kinds of ideas would need to be submitted to `std` for evaluation and mio would follow if accepted.

**Comment by Thomasdezeeuw** [comment]
I think this is out of scope for Mio, maybe it's better suited for something like Tokio.
