### ISSUE TITLE
mio fails to run on Windows XP

### ISSUE THREAD

**Issue by gstar4** [tokio-rs/mio#735]
I am trying to create a simple HTTP client that runs on all versions of Windows XP and newer.

Windows XP is currently officially [supported as a tier 3 platform in Rust](https://forge.rust-lang.org/platform-support.html).

The sample code I am trying to compile is:

```rust
extern crate reqwest; // version 0.7.3 specified in Cargo.toml

fn main() {
    reqwest::get("https://www.rust-lang.org")
}
```

I am following the following steps to build a portable Windows XP and newer compatible Rust binary. I am building from a Windows 10 x64 host.

Set `RUSTFLAGS` environment variable to 

```
-C target-feature=+crt-static -C link-arg=/SUBSYSTEM:CONSOLE,5.01
```

Build with 32-bit toolchain

```bash
$ rustup toolchain install stable-i686-pc-windows-msvc

$ cargo +stable-i686-pc-windows-msvc build --release
```

The resulting binary is linked to

```
secur32.dll
crypt32.dll
advapi32.dll
ws2_32.dll
kernel32.dll
```

and is properly listed with NT 5.1 as the operating system in the PE header.

When run on Windows XP SP3 32-bit an error is shown:

```
The procedure entry point SetFileCompletionNotificationModes could not be located in the dynamic link 
library KERNEL32.dll.
```

That function is being called by mio: 

- [ ] `SetFileCompletionNotificationModes` (NT 5.2+)

https://github.com/carllerche/mio/blob/8078b9034dfbe4e93277877a34ea803b55c7e3a9/src/sys/windows/mod.rs#L181

- [ ] `CancelIoEx` (NT 6.0+)

https://github.com/carllerche/mio/blob/8078b9034dfbe4e93277877a34ea803b55c7e3a9/src/sys/windows/mod.rs#L166

Following these same steps, a "Hello, World!" (without `reqwest`/`mio`) executable does execute properly on Windows XP SP3.

Originally posted on https://github.com/rust-lang/rust/issues/44873

**Comment by carllerche** [comment]
Thanks for the report, fixing this would require avoiding this fn. do you have thoughts on how?

**Comment by gstar4** [comment]
A first step might be to answer the question: "What is the total set of Windows system functions that `mio` depends on that are incompatible with Windows XP?" This would help scope how much of an effort getting full Windows XP support would be. It's probably better to answer that question before working on a fix in this one area, as after fixing that could just lead to another incompatible call.

It also might help answer the question of how costly it will be for `mio` to support Windows XP, and whether instead the documentation should just be updated to reflect that it doesn't support XP.

@retep998 Do you know of a way I could try to help answer this question? Is there a list of kernel functions that have been added post-XP that we could search against?

**Comment by cywec809** [comment]
Is it possible to add something like `#[cfg(feature = "winxp-compatible")]` that behaves as if 24b88f2cbff0aa5acb5ca2448e899d8b4aa3c44b and 88435998b3da09d1b8f656a25f70191335c0cde7 are reverted? Given that a lot of libs depend on mio and would be blocked by this on XP.

**Comment by carllerche** [comment]
Hasn't windows XP reached EOL 4 years ago? https://www.microsoft.com/en-us/windowsforbusiness/end-of-xp-support

**Comment by cywec809** [comment]
> Hasn't windows XP reached EOL 4 years ago? https://www.microsoft.com/en-us/windowsforbusiness/end-of-xp-support

Yes, but as gstar4 said, Windows XP is an [official tier 3 platform in Rust](https://forge.rust-lang.org/platform-support.html) and some people still use it. For example, you can test your code in Windows XP VM and it runs way faster than Win10.

Dependency walker gives only one more unsatisfied symbol: GetQueuedCompletionStatusEx ([source](https://github.com/alexcrichton/miow/blob/8cde1f3e3fe75962c9d456748eb9f4cc663705c9/src/iocp.rs#L156)). I think `get_many` can be simulated with multiple calls to `get` in the compatible mode.

**Comment by Thomasdezeeuw** [comment]
Windows XP support has ended 5 years ago, I don't think we want to support it either, so I'm closing this.
