### ISSUE TITLE
Expose peek and peek_from

### ISSUE THREAD

**Issue by asayers** [tokio-rs/mio#749]
I was comparing mio's API to libstd, and while most of the omissions make sense, I couldn't figure out why `peek` and `peek_from` are absent in mio. Is there are reason I'm missing?

EDIT: One reason: you'd have to drop support for 1.14 <= rust < 1.18

**Comment by carllerche** [comment]
What is this referring to? Could you link to the docs in std?

**Comment by asayers** [comment]
I'm referring to:

* `TcpStream::`[`peek`]
* `UdpSocket::{`[`peek`][udp-peek]`,`[`peek_from`]`}`

They've been in libstd since rust 1.18. They just pass the MSG_PEEK flag when calling `recv()`/`recvfrom()`. AFAIK `sock.peek(...) != Ok(0)` is the best way to check that a connection is still alive; it's probably useful for other things too.

[`peek`]: https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.peek
[udp-peek]: https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.peek
[`peek_from`]: https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.peek_from

**Comment by carllerche** [comment]
We can probably bump to a min Rust of 1.18 soon.

**Comment by asayers** [comment]
Looks like this issue was half-resolved by ed3d66af5b71989e28e322dd9abbc7b29ae4b9aa.

**Comment by Thomasdezeeuw** [comment]
Fixed by #1052.
