### ISSUE TITLE
Update `Events` and `poll` API

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#758]
This is a follow up to #713.

* The `Events` struct should gain an `is_empty()` function as a replacement for `len`.
* `Poll::poll` should not return `usize`, instead it should return `bool` representing if a timeout occurred.

**Comment by frehberg** [comment]
As for the API of data structure sys::Events, I am missing a "clear" function, so that user code can reset (for sure) an instance of sys::Events before reusing the data-structure for another  Poll:poll().

**Comment by carllerche** [comment]
A clear function would be good.

**Comment by Thomasdezeeuw** [comment]
#1023 adds `ExactSizeIterator` for `events::Iter`. On master `clear` and `is_empty` are already methods on `Events`. So closing this.

Also see #931.
