### ISSUE TITLE
Consider Separating Registration Data from Signal Data

### ISSUE THREAD

**Issue by cramertj** [tokio-rs/mio#759]
Currently, both incoming registrations and outgoing signals are handled through the `Ready` type. However, both Fuchsia and Windows provide outgoing signal information that is a superset of the signal-registration information. By forcing them to go through one type, you lose the extra signal data.

This would obviously be a breaking change. However, with some care, I believe it could be a non-breaking change to tokio-core by providing a way to convert from the old `Ready` type into a new `DesiredSignals` type, and from the new `Signals` type into the old `Ready` type.

An alternative would be to keep the single `Ready` type, and provide fake versions of the extra data provided by in the `Signals` type that wouldn't otherwise be present in the `DesiredSignals` type.

**Comment by carllerche** [comment]
If the goal is to expose additional platform specific outbound data, it seems to me like it would be sufficient to make `struct Event` be defined as `sys::Event`. Then any platform could provide additional information as well as expose it with an extension trait (like `FushiaEvent`) or something.

If this is sufficient, it seems like it is not a breaking change.

**Comment by cramertj** [comment]
That sounds fine to me, provided we can extend `tokio-core` to store an atomic (somehow?) `sys::Event` in the IoToken instead of an `AtomicUsize`.

**Comment by carllerche** [comment]
The behavior of the tokio reactor requires being able to make atomic ops on that cell. What would you suggest instead of atomic ops?

**Comment by cramertj** [comment]
They will need to be atomic still. I just don't know how best to structure that in a cross-platform way. Presumably mio would have to provide an atomic type that represented a collection of signals/packets, and there would have to be a way of unloading those signals/packets when they were processed.

**Comment by carllerche** [comment]
Right now, the largest atomic type provided by rust is `AtomicUsize`. I'm not sure what the actual proposal is.

**Comment by cramertj** [comment]
Well, for Fuchsia specifically, the signals type would be a `Mutex<SmallVec<PacketContents>>`.

**Comment by frehberg** [comment]
If you start to re-design the API, please keep in mind, also  TCP-level provides so called Out-of-Bound (OOB) signalling (the famous error-event): the sender may send a byte value as OOB which is delivered to recipient with priority encoded in TCP-header and must  be forwarded by hubs (must not be dropped). A new signalling feature in mio should be able to cover the TCP-level signalling as well.

**Comment by carllerche** [comment]
@frehberg in theory, it would be supported if it can be exposed via `Readiness`, but my guess is that it isn't portable, so it would need to be exposed in a similar way as UnixReady.

**Comment by Thomasdezeeuw** [comment]
With #983 you can access to the underlying platform specific event, would that solve this @cramertj?

**Comment by cramertj** [comment]
@Thomasdezeeuw It looks like that change puts registration data into `Ready` but keeps outgoing signal information in the `Event` type (without exposing it as a `Ready` afaict). If the intention is to plumb the `Event` through to Tokio in the way that `Ready` used to be plumbed through, then that would solve the situation. However, I don't see how that would be possible, given that we still don't have arbitrary-sized atomics, and likely don't want to force `Mutex<Event>` to be used on every platform.

**Comment by carllerche** [comment]
There is no more `usize` requirement anymore?

**Comment by carllerche** [comment]
If you mean `PollEvented` has a usize requirement, then yes. That would not work. However, `Registration` is basically a stream of events, so you could get that data there. `PollEvented` is a layer on top of `Registration`.

**Comment by carllerche** [comment]
@cramertj are you saying that you would want a `Mutex<Event>` on fuschia? It seems like you would want to avoid that for types that don't need the mutex (TCP types i would assume).

**Comment by carllerche** [comment]
For more context: I'm expecting to plumb more platform specific logic into Tokio.

**Comment by cramertj** [comment]
> It seems like you would want to avoid that for types that don't need the mutex (TCP types i would assume).

The issue here is that on Fuchsia, it's possible for actual data to be delivered as part of an event coming off of a port, rather than just a notification. In those cases, we'd need to be able to store that data and deliver it across the `PollEvented` (or similar) boundary. I don't have a particularly strong opinion about the mechanism over which this happens, but it needs to be possible in order to make Fuchsia's asynchronous objects all usable with Tokio.

**Comment by Thomasdezeeuw** [comment]
The current status on master is that `Event` no longer returns readiness (`Ready`), but has a bunch of methods along the line of `is_writable`, and is no longer limited to the `Ready` type. It's also now just a wrapper around the system event.

Exposing addition (platform specific) details is still something we might want and is being tracked in #990, which can be done after a v0.7. As such I'm going to close this as half solved and the other half tracked in #990. @cramertj if you disagree please reopen.
