### ISSUE TITLE
windows: dropping Poll while reads are pending leaks streams

### ISSUE THREAD

**Issue by seanmonstar** [tokio-rs/mio#776]
If a socket has a pending read request, and then the socket and the corresponding `Poll` are dropped, the internal `TcpStream` is never actually dropped. This is because the `sys::windows::Selector` does not get polled again to trigger the canceled callback.

Test case that fails on Windows, passes on Unix:

```rust
#[test]
fn drop_cancels_interest_and_shuts_down() {
    use env_logger;
    let _ = env_logger::init();
    let l = net::TcpListener::bind("127.0.0.1:0").unwrap();
    let addr = l.local_addr().unwrap();

    let t = thread::spawn(move || {
        let mut s = l.accept().expect("accept").0;
        s.set_read_timeout(Some(Duration::from_secs(5))).expect("set_read_timeout");
        s.read(&mut [0; 16]).expect("read");
    });

    let poll = Poll::new().unwrap();
    let mut s = TcpStream::connect(&addr).unwrap();

    poll.register(&s, Token(1), Ready::readable() | Ready::writable(), PollOpt::edge()).unwrap();
    let mut events = Events::with_capacity(16);
    'outer: loop {
        poll.poll(&mut events, None).unwrap();
        for event in &events {
            if event.token() == Token(1) {
                // connected
                break 'outer;
            }
        }
    }

    let mut b = [0; 1024];
    match s.read(&mut b) {
        Ok(_) => panic!("unexpected ok"),
        Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => (),
        Err(e) => panic!("unexpected error: {:?}", e),
    }

    drop(s);
    t.join().unwrap();
}
```

------

I tried fixing this by having a check in `sys::windows::TcpStream::drop` that decrements the ref count an additional time if `cancel` returns success, but that only works in this specific case: if the `Poll` isn't actually dropped, the canceled status will trigger `read_done` after the drop.

With an additional pointer, the `FromRawArc` could drop the inner pointer and set it to 0, and then `read_done` and `write_done` could check for a null pointer before continuing.

Another alternative is that `sys::windows::Selector` could keep a list of all associated handles, and close all of them on `drop`.

**Comment by carllerche** [comment]
Hmm, do you have any thoughts off the bat @alexcrichton. This seems like it could be tricky to fix well.

**Comment by alexcrichton** [comment]
@seanmonstar can you clarify the title vs the example here? The title indicates that `Poll` is being dropped while the example is just not spinning in `Poll`?

I believe that after a `CancelIoEx` we don't have any choice but to wait for the completion to actually make its way into the selector. We could tweak this perhaps if when `TcpStream` is dropped the `Poll` is dropped, but that's slightly racy and also isn't reflecting the example here.

There's already a ton of tests I think you can write which succeed on Unix and fail on Windows, so I wouldn't say that's necessarily indicative of a bug. Was this coming up in practice though? Is it difficult to work around externally?

**Comment by pavel-mukhanov** [comment]
Any updates on this issue? We experiencing the same problem with TcpStream on windows.

**Comment by carllerche** [comment]
Unfortunately not. Nobody has scheduled time to focus on this bug. Perhaps you? :)

**Comment by woodgear** [comment]
still hopeless?

**Comment by DoumanAsh** [comment]
@carllerche Just curious about leaking stream https://github.com/carllerche/mio/blob/master/src/sys/windows/tcp.rs#L403

While I understand that it prevents cancellation of IO, but why it is necessary to prevent cancellation? If stream would be dropped, doesn't it mean all related ops should be cancelled?

cc @PerfectLaugh

**Comment by faern** [comment]
What is the status of this? This is really a problem in practice if you are using a library that in turn uses sockets and your app uses the library for a while and then want to turn off what that library exposes, but don't terminate your application process.

Is it deemed fixable? So that someone who have some time on their hands can work on it? If so, is there a plan for how to approach it?
