### ISSUE TITLE
Change `TcpListener` and `UdpSocket` methods to own `SocketAddr`

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#789]
Change `TcpListener` and `UdpSocket` methods to accept `SocketAddr` rather then `&SocketAddr`, since `SocketAddr` is `Copy`. Would make it slightly more ergonomic to use.

**Comment by carllerche** [comment]
I don't have a huge opinion here.

That said, if this change happens, it should be coordinated with Tokio & co. which also uses `&SocketAddr`.

I'm not sure if it would be worth making such a change.

/cc @alexcrichton

**Comment by Thomasdezeeuw** [comment]
This happened on master already.
