### ISSUE TITLE
poll occasionally yields event for oneshot token despite not being reregistered

### ISSUE THREAD

**Issue by jonhoo** [tokio-rs/mio#808]
I've been building [`mio-pool`](https://github.com/jonhoo/mio-pool), which is essentially a thin wrapper around mio for having a pool of threads all poll on a single `mio::Poll` with `oneshot`, have them handle the data available on the corresponding connection, and then re-registering it.

When a connection is removed, its token is not re-registered, and the underlying `TcpStream` is eventually dropped. However, I observe that I occasionally still receive an event for the disconnected stream a little bit later (maybe when the `TcpStream` is in fact dropped, though I'm not entirely sure about that part). This seems counter-intuitive to me, as `oneshot` should presumably guarantee that this doesn't happen.

Specifically, I observe that the (commented) `unreachable!` on [this line](https://github.com/jonhoo/mio-pool/blob/4f417290a73de66db05d39c71dae521265bf4d33/src/worker.rs#L152) triggers when running the `many_workers` test. I have heard reports that it happens even more frequently on macOS, but I observe it fairly reliably on Linux too.

**Comment by dimbleby** [comment]
You're registering with `PollOpt::level() | PollOpt::oneshot()`, whereas the code seems only to pay attention to `oneshot` in association with `edge` - see [here](https://github.com/carllerche/mio/blob/3fe5e3749268f245c1d7caffd4e55e7835d0c79b/src/poll.rs#L2148-L2152).

The docs sort of talk about this, perhaps without being completely explicit.  If this is indeed the solution, I imagine that a pull request clearing things up so that this issue could have been avoided would be welcome...

**Comment by jonhoo** [comment]
@dimbleby I'm not entirely sure what you are proposing? `level` + `oneshot` should be a legal combination, and often makes just as much sense than `edge` + `oneshot`, if not more, when you have a pool of threads all managing some set of connections. If this mode is indeed not supposed to be supported, I'd argue an error should be returned from `register`/`reregister` when the two flags are both set at the same time.

**Comment by carllerche** [comment]
`level` + `oneshot` should probably be supported... Could you provide some failing tests illustrating how a custom `Registration` value doesn't behave correctly?

**Comment by jonhoo** [comment]
I wasn't using any custom `Registration` values when I observed this. This was back when mio-pool was based on mio, which would be jonhoo/mio-pool@85b6041c5a4f0c1a753ac55b11fe53b11ca3a9a5. `cargo t many_workers` triggers the highlighted `unreachable!`, which shouldn't happen with oneshot + level.

**Comment by Thomasdezeeuw** [comment]
On master we only support edge triggers, thus this no longer applies.
