### ISSUE TITLE
dlsym crashes in Android API < 21

### ISSUE THREAD

**Issue by kokje** [tokio-rs/mio#820]
Hi,

A bug in kernel VDSO lookup causes dlsym to crash with SIGFPE 
https://github.com/carllerche/mio/blob/db2a5e8ac136791a1c7b66a7d118ac4876c9c119/src/sys/unix/dlsym.rs#L43
https://android-review.googlesource.com/c/platform/bionic/+/69033

epoll_create1 was not implemented in bionic until API 21
https://android.googlesource.com/platform/bionic/+/master/libc/libc.map.txt#308

A possible workaround could be to use syscall directly?

**Comment by carllerche** [comment]
Well, the issue is that `epoll_create1` is superior due to `EPOLL_CLOEXEC`. So it is best to use it when possible.

Do you have thoughts on how to conditionally use `epoll_create1` without a `dlsym` check?

**Comment by kokje** [comment]
I think making a direct syscall is a good option. On failure it should return a -1 with the associate errno value
ex: syscall(__NR_epoll_create1, EPOLL_CLOEXEC)
using https://github.com/rust-lang/libc/blob/bbda50d20937e570df5ec857eea0e2a098e76b2d/src/unix/notbsd/android/mod.rs#L1066

There are a couple of other ways discussed here: https://github.com/android-ndk/ndk/issues/302

**Comment by maltzj** [comment]
Poking this as a concerned Android dev. What are your feelings on using a syscall?

**Comment by carllerche** [comment]
@maltzj If this is the accepted strategy for android, it should be fine.

**Comment by Thomasdezeeuw** [comment]
Android API level < 21 has less then 10% according to https://developer.android.com/about/dashboards, do we still want to support it?

If so, this is the solution by libuv: https://github.com/libuv/libuv/blob/d7f0055b8014196b3c3a3a4eaf86e6ea81745ff0/src/unix/linux-core.c#L89-L103.

**Comment by carllerche** [comment]
I also think we could probably just copy what libuv does for initialization here.

**Comment by Thomasdezeeuw** [comment]
Pr #1005 switches to using `epoll_create1` also removing `dlsym`, so I don't think this is an issue anymore. If still is still an issue on the master branch, feel free to reopen.
