### ISSUE TITLE
TCP_KEEPINTVL / TCP_KEEPCNT  api missing

### ISSUE THREAD

**Issue by aep** [tokio-rs/mio#838]
mio::net::TcpStream::set_keepalive only lets you set TCP_KEEPIDLE, which isn't particularly useful.

resorting to nix::setsockopt over raw_fd works of course, but i suspect people will be confused, since the behavior when not setting TCP_KEEPINTVL is non-obvious, unless you know posix internals.

related https://github.com/tokio-rs/tokio-core/issues/323

**Comment by carllerche** [comment]
Generally speaking, Mio tries to stick with a TCP API that mirrors `std`. Perhaps this issue should be filed on the rust-lang repo and as the API changes there, mio will follow.

**Comment by Thomasdezeeuw** [comment]
I agree with @carllerche and think we should stick to mirroring the API in the standard library, closing this. @aep I don't think getting this into the standard library will be that hard, `UdpSocket::peer_addr` also recently landed https://github.com/rust-lang/rust/issues/59127.
