### ISSUE TITLE
Consider adding pcap as a platform (selector).

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#839]
This could be potentially be added as a feature flag when building Mio.

I haven't fully considered the implications yet and it has been a while since I looked into pcap, but this issue can represent the investigation / discussion.

cc @stephanbuys

**Comment by carllerche** [comment]
@stephanbuys my understanding is that `libpcap` has a similar model except that there is no waiting (`epoll_wait`). If so, why do you think it wouldn't fit with `mio`?

**Comment by stephanbuys** [comment]
@carllerche please see @mrmonday's breakdown - much better guidance than I could give. https://github.com/rust-lang-nursery/net-wg/issues/15#issuecomment-408609340

**Comment by Thomasdezeeuw** [comment]
@carllerche is this still something you want to consider in the scope of Mio?

**Comment by carllerche** [comment]
Yes and no... I think we should make sure there is a plan to be able to do so in the future, but we are not blocking on it.

I need to write up my thoughts on the matter.

**Comment by Thomasdezeeuw** [comment]
@carllerche you still want to do this?

**Comment by carllerche** [comment]
Low priority at this point. I'm fine saying no.

**Comment by Thomasdezeeuw** [comment]
Then I'm closing this for now and we can open it again once someone is interested in it.
