### ISSUE TITLE
Switch from net2 to socket2

### ISSUE THREAD

**Issue by bluejekyll** [tokio-rs/mio#841]
Any thoughts on migrating from net2 to socket2 instead?

https://docs.rs/socket2/0.3.5/socket2/

socket2 seems to be getting more attention now than net2, and may be the path forward.

**Comment by carllerche** [comment]
Currently, the strategy is to do all configuration up front, then pass the configured `UdpSocket` -> mio / tokio.

You can perform the conversion w/ https://github.com/tokio-rs/tokio/blob/master/tokio-udp/src/socket.rs#L39

**Comment by bluejekyll** [comment]
yes, that's what we were and are doing, but isn't Tokio moving towards not having explicit handles? That interface requires a handle... I'm a little confused on the current state of default Core/Handle's etc. I need to read up more on that, clearly.

**Comment by carllerche** [comment]
Yeah, you would pass in `Handle::default` (though the semantics of that are *currently* a bit wrong...)

**Comment by Thomasdezeeuw** [comment]
Is this something we still want to do? Since we use very little of net2 we can also just do the raw calls ourselves remove the need for the net2 crate completely.

**Comment by carllerche** [comment]
I kind of like just doing the raw calls ourselves...
