### ISSUE TITLE
custom readiness queue misses events

### ISSUE THREAD

**Issue by Hexilee** [tokio-rs/mio#892]
OS & toolchain : both of `macOS-10.14-nightly-x86_64-apple-darwin` and `Ubuntu-16.04.2-nightly-x86_64-unknown-linux-gnu`.

I write a demo about async-fs and here is the [code](https://github.com/Hexilee/mio-demo/blob/miss-event/src/fs_mio.rs).

The problem is, when I execute `cargo test -- --nocapture`, I can see [poll](https://github.com/Hexilee/mio-demo/blob/miss-event/src/fs_mio.rs#L74) always gets timeout and goes to dead-loop, even when I register custom registration with `PollOpt::level()`

However, when I reregister it by uncomments this [line](https://github.com/Hexilee/mio-demo/blob/miss-event/src/fs_mio.rs#L99), it will never miss events.

**Comment by Thomasdezeeuw** [comment]
Custom readiness queue has been removed.
