### ISSUE TITLE
Compat layer from mio 0.6 -> 0.7

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#902]
This issue is opened to track discussion.

The main reason mio has not issued a breaking change is due to the difficulty of migrating downstream crates. mio APIs are part of the public API for a number of downstream crates, the largest being [tokio](http://github.com/tokio-rs/tokio).

In order to make the transition from 0.6 -> 0.7 smoother, there should be a compatibility strategy so that downstream crates are able to internally switch to 0.7 without issuing a breaking change.

For Tokio, this means a way to register 0.6 [`PollEvented`] values with 0.7 mio. There should be a strategy by which to do this if, once 0.7 is released, 0.6 mio is updated to be a shim around 0.7.

**Comment by PerfectLaugh** [comment]
I have tried to make one. https://github.com/PerfectLaugh/mio-compat
But due to unsupported level trigger and oneshot mode, it will throw error when PollOpt is level or oneshot.

**Comment by carllerche** [comment]
Thanks for the attempt. You are correct that this may be more trouble than it is worth. I will close this now. 

Tokio can switch to mio 0.7 at the same time to avoid the split.
