### ISSUE TITLE
Mio 0.7  types

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#904]
For Mio 0.7 we should determine what types should remain in the Mio crate and what types should move to other crates, for example [mio-extras](https://crates.io/crates/mio-extras) or [mio-more](https://crates.io/crates/mio-more).

To start the discussion, here are my thoughts. From the `event` module `Event`, `Events` and `Evented` should stay, that removes `Iter` (#901 proposes to implement `Iterator` on `&mut Events`). The `net` and `unix` modules should stay as they are.

From the root of the crate @carllerche suggested to remove `Registration` and `SetReadiness`, as that functionality can be provided by a third party crate, and I agree. This means that we don't have to maintain a complex MPSC queue.

That leaves `Poll`, `PollOpt`, `Ready` and `Token` (and `Events` again) in the root of the crate, all of which are required types I think.

**Comment by ahmedcharles** [comment]
Seems reasonable.

**Comment by carllerche** [comment]
@Thomasdezeeuw Also, in the 0.7 branch, `Poll` is split into `Poll` and `Register`.

**Comment by Thomasdezeeuw** [comment]
@carllerche I hadn't  yet looked through the 0.7 branch. But looking at it now, `Poll` and `Register` both are essentially `Arc<Inner>`, where `struct Inner { sys::Selector, ReadinessQueue }`. But if we go through with dropping `Registration` then the readiness queue will be dropped as well (right?). That means that `Poll` and `Register` (at least on unix) become `Arc<RawFd>`, which to me seems a bit wasteful.

I don't know if it is possible but maybe we can keep `Poll` as is (meaning just a wrapper around `Selector`) and then add a `Register` type that `dup`licates the kqueue/epoll file descriptor and it can only register `Evented` handles. I don't know if `dup` works on a kqueue/epoll file descriptor, or about Windows.

**Comment by Thomasdezeeuw** [comment]
The work is mostly done for this, closing in favour of #931 and #1025.

**Comment by 00imvj00** [comment]
Please maintain one lib for all mio related things. Adding 3, 4 dependencies just for one lib will be hard and confusing for new people. 

Maybe we can split into separate modules and arrange it better?

**Comment by Thomasdezeeuw** [comment]
@00imvj00 what do you mean? Most types removed in 0.7 were already deprecated, the only types removed in addition were `Registration` and `SetReadiness`, but those were implemented fully in user space and didn't really below in Mio (as they have little to do with polling the system for readiness events).

**Comment by 00imvj00** [comment]
Sorry, I misunderstood this
```For Mio 0.7 we should determine what types should remain in the Mio crate and what types should move to other crates, for example mio-extras or mio-more.```.

**Comment by Thomasdezeeuw** [comment]
OK, for clarity; the types in Mio 0.7-alpha1 will also (probably) be the types in Mio 1.0. I can't give a 100% guarantee, but I don't expect a lot of changes to the types.

**Comment by 00imvj00** [comment]
understood. One question, @Thomasdezeeuw with new types, instead of `Poll`, we can use `Registry` to register and re-register IO handlers. Is `Registry` Reference(&Registry) safe to pass across thread?

**Comment by Thomasdezeeuw** [comment]
Yes, both `Poll` and `Registry` implement [`Send`](https://doc.rust-lang.org/std/marker/trait.Send.html) and thus can be send across thread bounds. Furthermore both implement [`Sync`](https://doc.rust-lang.org/std/marker/trait.Sync.html) can safely be used (i.e. methods called) across thread bounds.

**Comment by 00imvj00** [comment]
@Thomasdezeeuw thanks. :)
