### ISSUE TITLE
Split `Ready` into `Ready` and `Interests`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#908]
Split Ready into [Ready](https://docs.rs/mio-st/0.2.0/mio_st/event/struct.Ready.html) and [Interests](https://docs.rs/mio-st/0.2.0/mio_st/poll/struct.Interests.html). Interests is used in registering (Evented) and can only be readable and/or writable, but never be empty. Ready is only used as output in Event and can also be error or hup.

From #901.

**Comment by FXTi** [comment]
How should `Interests` work with `UnixReady`?
Just provide method to convert `Ready` to `UnixReady` as what `Ready` do?

**Comment by Thomasdezeeuw** [comment]
Hup and error readiness are really output only and are set by default. So that leaves priority, that could also become a unix only variant of `Interests` just like hup is on `Ready`.
