### ISSUE TITLE
Support for Universal Windows Platform?

### ISSUE THREAD

**Issue by seamlik** [tokio-rs/mio#912]
I see that this project supports Windows, but does it mean UWP as well? If not, will we have it in the future?

With UWP support, Rust could even run in HoloLens or Xbox.

I can find nothing related to UWP in the Windows support. But I'm also not familiar with Windows stuff, so maybe I missed something.

**Comment by carllerche** [comment]
What is universal windows platform? I am not familiar w/ it.

**Comment by SergejJurecko** [comment]
mio works fine in desktop UWP apps. ARM is another story.

**Comment by jdm** [comment]
@SergejJurecko Do you have any more specific details about the support on ARM windows?

**Comment by SergejJurecko** [comment]
No I have not tried it actually. Even for desktop you have to compile with release and not have too many dependencies because you never know what parts of winapi-rs they will pull in to mess you up. 

Also keep in mind it might all work locally and be rejected once you try to publish to windows store..

**Comment by Thomasdezeeuw** [comment]
Since the interest in this seems to have died down I'm closing this, but not rejecting this.

**Comment by SergejJurecko** [comment]
0.7 implementation will not be UWP compatible. Functions in afd.rs  are not allowed in UWP.

**Comment by carllerche** [comment]
In general, we try to avoid "feature" issues that have no path to implementation.

If someone wishes to champion UWP, they can open a new issue w/ an implementation proposal followed by a PR.

**Comment by seamlik** [comment]
Rust can't even target UWP... Though it's [being worked on](https://github.com/rust-lang/rust/pull/60260).

So as a downstream user I might say nothing in Rust supports UWP. After UWP support is merged, I might be able to try investigating this.
