### ISSUE TITLE
Windows UDP sends aren't pipelined

### ISSUE THREAD

**Issue by Ralith** [tokio-rs/mio#913]
https://github.com/carllerche/mio/blob/master/src/sys/windows/udp.rs#L105 marks the socket as unwritable until the send completes at https://github.com/carllerche/mio/blob/master/src/sys/windows/udp.rs#L394. This makes very inefficient use of the kernel's UDP send buffer, severely reducing throughput. Instead, the socket should only be marked as unwritable once the buffer is full. It's not totally clear how this should be accomplished, but there are at least two possibilities:

- Configure the socket not to generate a completion notification for operations that complete immediately, using `SetQueuedCompletionNotificationModes`. Then only unregister write readiness when `WSASendMsg` returns `WSA_IO_PENDING` instead of `0`. However, [some reports](https://bugs.chromium.org/p/chromium/issues/detail?id=442392) suggest that `WSA_IO_PENDING` can be returned prematurely.
- Use traditional non-blocking sends until a send would block, and only then queue an overlapped send

**Comment by carllerche** [comment]
Yes, the windows system should probably be rewritten. Unfortunately, this is probably not going to happen unless someone volunteers to take it on.

**Comment by Thomasdezeeuw** [comment]
@Ralith can you confirm this issue is solved on current master? Your first link now points to a call to  `broadcast`.

**Comment by carllerche** [comment]
Original link: https://github.com/tokio-rs/mio/blob/v0.6.x/src/sys/windows/udp.rs#L105

I'm going to guess that the answer is yes as we no longer do any double buffering.

**Comment by Thomasdezeeuw** [comment]
Then I'm going to close this as solved.
