### ISSUE TITLE
Timer created after poll won't fire

### ISSUE THREAD

**Issue by pusateri** [tokio-rs/mio#926]
Sample code:

https://gist.github.com/pusateri/58ea591219ce2a90166daee811c3dbbb

When a timer is created inside the poll loop and registered, it never fires. It has to be created before the poll loop is entered. This is difficult when you don't know how many timers you will need.

In my real application, I need to create a timer per cache entry but can't create timers ahead of time because I don't know how many cache entries there are so I want to create the timer when I create the cache entry.

**Comment by Thomasdezeeuw** [comment]
As `Timer` was just removed from master (e739c8a8a76a62e1939e24a0de6204d1720ee9a7), I'm going to close this. You can use [mio-more](https://crates.io/crates/mio-more) or [mio-extras](https://crates.io/crates/mio-extras), although I don't know if that code doesn't have the same problem.

**Comment by pusateri** [comment]
Using mio-extras as you can see from the example. It's not clear that this is a timer problem.

**Comment by pusateri** [comment]
I can try to replicate with sockets.

**Comment by Thomasdezeeuw** [comment]
If you can replicate it with socket with only (not deprecated) mio API that would be created, I'll reopen it for now.

**Comment by Thomasdezeeuw** [comment]
@pusateri looking at the code again; is possible that it won't trigger because the timer is dropped?

**Comment by pusateri** [comment]
Maybe so. I'll try that next. I was able to reproduce it with two sockets but it could be the same problem with the socket being dropped.

```
use mio::{Events, Ready, Poll, PollOpt, Token};
use mio::net::UdpSocket;
use std::net::{SocketAddr, Ipv4Addr};

fn main() {
    const SOCKET1_TOKEN: Token = Token(1);
    const SOCKET2_TOKEN: Token = Token(2);
    let poll = Poll::new().expect("Poll new failed");
    let sa1 = SocketAddr::new(Ipv4Addr::new(127,0,0,1).into(), 8001);
    let socket1 = UdpSocket::bind(&sa1).unwrap();
    let mut events = Events::with_capacity(1024);

    poll.register(&socket1, SOCKET1_TOKEN, Ready::readable(), PollOpt::edge()).expect("poll.register socket1 failed");
    loop {
        poll.poll(&mut events, None).expect("poll.poll failed");
        for event in events.iter() {
            println!("event");
            if event.token() == SOCKET1_TOKEN {
            	println!("socket1 event: {:?}", event);
                let sa2 = SocketAddr::new(Ipv4Addr::new(127,0,0,1).into(), 8002);
    			let socket2 = UdpSocket::bind(&sa2).unwrap();
                poll.register(&socket2, SOCKET2_TOKEN, Ready::readable(), PollOpt::edge()).expect("poll.register socket2 failed");
            } else {
                println!("socket2 event: {:?}", event);
            }
        }
    }
}
```

**Comment by Thomasdezeeuw** [comment]
On platforms with epoll (Linux) and kqueue (MacOS, FreeBSD, NetBSD and OpenBSD) it will deregister the socket when the file descriptor is closed (dropped). * So it would make sense that you don't receive any events for it (otherwise you'll receive events for a socket that is already closed and thus can't deregister anymore).

If you keep `socket2` around in the next iteration of the loop does the problem go away?

* There are situation in which this is not true, but those do not apply to this example.

**Comment by pusateri** [comment]
Yes, it works if socket2 isn't dropped. I'm closing this. Thanks for figuring it out.

**Comment by pusateri** [comment]
This works:
```
use mio::{Events, Ready, Poll, PollOpt, Token};
use mio::net::UdpSocket;
use std::net::{SocketAddr, Ipv4Addr};

fn main() {
    const SOCKET1_TOKEN: Token = Token(1);
    const SOCKET2_TOKEN: Token = Token(2);

    let poll = Poll::new().expect("Poll new failed");
    let sa1 = SocketAddr::new(Ipv4Addr::new(127,0,0,1).into(), 8001);
    let socket1 = UdpSocket::bind(&sa1).unwrap();
    let sa2 = SocketAddr::new(Ipv4Addr::new(127,0,0,1).into(), 8002);
    let socket2 = UdpSocket::bind(&sa2).unwrap();
    let mut events = Events::with_capacity(1024);

    poll.register(&socket1, SOCKET1_TOKEN, Ready::readable(), PollOpt::edge()).expect("poll.register socket1 failed");
    loop {
        poll.poll(&mut events, None).expect("poll.poll failed");
        for event in events.iter() {
            println!("event");
            if event.token() == SOCKET1_TOKEN {
            	println!("socket1 event: {:?}", event);
                
                poll.register(&socket2, SOCKET2_TOKEN, Ready::readable(), PollOpt::edge()).expect("poll.register socket2 failed");
            } else {
                println!("socket2 event: {:?}", event);
            }
        }
    }
}
```

**Comment by Thomasdezeeuw** [comment]
Good to see we've found the problem.
