### ISSUE TITLE
Tweak Poll API

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#931]
Currently, Mio's Poll API looks like:

```rust
let mut events = Events::with_capacity(1024);
let mut poll = Poll::new().unwrap();

loop {
    poll.poll(&mut events).unwrap();

   for event in &events { ... }
}
```

The problem is that each OS selector has internal tokens it uses to maintain its own state. Currently, it is only the awakener token, however in 0.7 we will reserve additional token space for OS selector implementations (see https://github.com/tokio-rs/mio/issues/788).

In the epoll implementation, the list of events is scanned before returning from `select` ([code](https://github.com/tokio-rs/mio/blob/ebd086e4c4a4a4eb35e2e0b493e889d7d50c9767/src/sys/unix/epoll.rs#L80-L85)).

If an internal token is returned from OS, the selector implementation needs the opportunity to take an action and the token itself should not be returned to the user. To satisfy this requirement, I suggest updating the poll API to something like:

```rust
// In Mio
struct Events<'a> {
    // contains the array for OS events. Real name TBD
    storage: &'a mut Storage,
    poll: &'a mut Poll,
    curr: usize,
}

impl Iterator for Events<'_> {
    // ...
}

let mut storage = Storage::with_capacity(1024);
let mut poll = Poll::new().unwrap();

loop {
    let events = poll.poll(&mut storage).unwrap();

   for event in &events { ... }
}
```

In the above example, internal tokens are forwarded to the selector lazily for processing (as the iterator traverses them). On drop, if all the events were not checked, the remaining are searched for any internal tokens.

cc/ @Thomasdezeeuw @asomers @stjepang

**Comment by stjepang** [comment]
I wonder if it's worthwhile keeping `Events::with_capacity(n)` configurable at all.

What if we only exposed constructor `Events::new()` that uses a reasonable capacity? Are there use cases where the user can *really* choose a better capacity than 1024 or whatever we set as the default?

In that case, we could have `Poll::poll()` looking as follows:

```rust
impl Poll {
    fn poll(&mut self) -> Result<Events<'_>>;
}

struct Events<'a> { ... }

impl Iterator for Events<'_> {
    // ...
}
```

**Comment by carllerche** [comment]
IMO the bigger concern is that the event storage is now coupled with the `Poll` instance. I'm not sure how big a problem that is in practice though.

**Comment by stjepang** [comment]
To go a bit further, does it even make sense to have fixed-size buffers for event storage?

What if we made the buffer size proportional to the number of registered IO handles (perhaps with a fixed upper bound)? That way we could choose the optimal size during runtime and never worry whether we allocated too much or too little storage.

**Comment by carllerche** [comment]
For Mio, I don't think it makes sense to set defaults for these things. Instead, Mio should provide access to the system APIs in a portable way.

Usually an app will have one place they impl Poll. Also, it would be possible to impl a layer on top of Poll & events that binds them together, but not the reverse.

**Comment by stjepang** [comment]
Just to write down another idea - get rid of `Events` and `Iter` and change the signature of `poll()` to:

```rust
impl Poll {
    fn poll(&self, events: &mut Vec<Events>, timeout: Option<Duration>);
}
```

Function `poll()` appends new events to this `Vec`, then iterates over the pushed events to process internal ones, while removing them with `swap_remove()`.

The benefit of this approach is leaving a lot of choice to the user while also simplifying the API. The user can dynamically resize the `Vec` if they wish, or don't even need to empty the `Vec` before calling `poll()`.

**Comment by Thomasdezeeuw** [comment]
If we're writing down ideas; in mio_st I've changed events to be a trait (and renamed it to `event::Sink`):

```rust
/// An event sink to which events can be added.
pub trait Sink {
    /// Capacity left in the event sink.
    ///
    /// This must return the available capacity left, **not total capacity**.
    ///
    /// # Notes
    ///
    /// If this returns [`Capacity::Limited`] and the capacity left is incorrect
    /// it may cause missing events.
    fn capacity_left(&self) -> Capacity;

    /// Add a single event.
    fn add(&mut self, event: Event);

    /// Extend with multiple events.
    fn extend<I>(&mut self, events: I)
        where I: Iterator<Item = Event>,
    {
        for event in events {
            self.add(event);
        }
    }
}

/// The capacity left in the [event sink].
///
/// If the event source can grow it should use `Growable`. If there is some kind
/// of capacity limit `Limited` should be used.
///
/// [event sink]: Sink
#[derive(Copy, Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
pub enum Capacity {
    /// The capacity is limited.
    Limited(usize),
    /// The events sink capacity is growable.
    ///
    /// This is for example returned in the event sink implementation for
    /// vectors.
    Growable,
}
```

**Comment by carllerche** [comment]
@Thomasdezeeuw If I understand correctly, this API would require the selector implementation (e.g. epoll), to store its own buffer internally, read into it, iterate & move the events into the provided generic buffer?

What would be the advantage of doing this vs. requiring the user to pass in a fixed type that the underlying selector can put events directly into?

**Comment by Thomasdezeeuw** [comment]
@carllerche In most cases you need to iterate over all system events at least once to convert them to a mio `Event`, converting epoll/kqueue readiness to mio `Ready`. When you use a vector to store those events the user needs to iterate over them again in the event loop. However when you have some kind of scheduler you might not want to process each event in the order they are added, e.g. high priority processes should run first. For example in Heph I schedule each process based on the received events and then run the processes in priority order. With the current design I would need to iterate over the system events converting them to mio `Event`s, then iterator over the vector to schedule each process and then run processes. With a `Events` trait those two iterations can happen in a single iteration.

**Comment by carllerche** [comment]
@Thomasdezeeuw 

I see what you are saying now. I did not consider implementing `Sink` as the event loop dispatcher.

> When you use a vector to store those events the user needs to iterate over them again in the event loop.

There **must** be a vector + iteration at some point. This is required by the OS APIs. I think we can agree that the goal should be to limit to 1 iteration.

> With the current design I would need to iterate over the system events converting them to mio Events, then iterator over the vector to schedule each process and then run processes. 

With the proposed API of having `Poll::poll` return an iterator, it *should* be possible to only have 1 iteration of the event set. I **believe** that returning an iterator would be equivalent performance wise to your proposed trait based API, but without requiring an extra trait.

After thinking a bit, I am starting to warm up with @stjepang's simplified API. This would require `Poll` to store a vec internally, but I can't think of a case where this would be a problem. There also are forward compatible strategies to re-introduce an external "storage" struct.

@Thomasdezeeuw Do you agree that returning an iterator would be equivalent both performance & flexibility wise to taking a struct? I would even think it would be *more* flexible to return an iterator as it would allow the caller to control the details around the loop (pausing, inject other logic, ...) easier.

**Comment by Thomasdezeeuw** [comment]
@carllerche Returning an iterator sounds good.

**Comment by Thomasdezeeuw** [comment]
A lot has changed our `Event` and `Events` in Mio v0.7, for example both are now platform dependent and no longer require any conversion or scanning after poll. Are there any other changes we want to make to the API for v0.7?

**Comment by carllerche** [comment]
I think it is fine to close this issue now :+1:
