### ISSUE TITLE
Make `Option<Interests>` the same size as `Interests`

### ISSUE THREAD

**Issue by FXTi** [tokio-rs/mio#934]
In mio-st I've made this `NonZeroU8` to make `Option<Interests>` the same size as `Interests`. But that can come later (in a future pr).

_Originally posted by @Thomasdezeeuw in https://github.com/tokio-rs/mio/pull/925_

* Remove `Interests::both`
* Add `Interests::read_write()`

**Comment by Thomasdezeeuw** [comment]
Also also decide on `Interests::both()` vs. `Interests::all()` and whether or not such a method should exist at all.

**Comment by carllerche** [comment]
I'm wondering if we should **not** have `all()` or `both()`. It is unclear to me if `Interests::all()` would pull in operating specific interests or only pull in portable interests.

I'm OK w/ requiring the user to specify both read & write interests explicitly. Alternatively, we could have` `Interests::read_write()`

**Comment by stjepang** [comment]
I agree with @carllerche. Perhaps for completeness we should also have `Interests::none()`.

**Comment by Thomasdezeeuw** [comment]
> I agree with @carllerche. Perhaps for completeness we should also have `Interests::none()`.

The point of `Interests` was to not have empty interests as it doesn't make a lot of sense. I see no point in registering with empty interests, thus I suggested `Interests` as a non-empty `Ready`.

@carllerche I'm also against a `Interests::all/both()` in mio_st it's a private convenience method.

**Comment by FXTi** [comment]
@carllerche @Thomasdezeeuw I agree.

So let's remove `Interests::both` and add `Interests::read_write` for convenience?

**Comment by carllerche** [comment]
@FXTi for now, we can just remove `both` for now. Lets not add a new API yet.

**Comment by FXTi** [comment]
Shall we add `ops::SubAssign` for `Option<Interests>`?
```rust
                if let Some(x) = self.interests.as_mut() {
                    *x -= Interests::readable();
                }
```

Here, if `self.interests` is just `READABLE`, then the result should be `None`, but not `Option<Interests(0)>` .

To do this, may be in this way?

```rust
self.interests -= Some(Interests::readable());
```

**Comment by carllerche** [comment]
@FXTi Ah, you are correct, `sub` is a bad idea here.

**Comment by FXTi** [comment]
@carllerche I thought two branches for just removing `Interests::readable()` are too much to write.

```rust
if self.interests == Some(Interests::readable()) {
    self.interests = None;
} else if let Some(x) = self.interests.as_mut() {
    *x -= Interests::readable();
}
```
And this is much more clear.
```rust
self.interests -= Some(Interests::readable());
```

**Comment by Thomasdezeeuw** [comment]
After merging merging #940 I think this can be closed.

The only thing I just though was the Sub(Assign) implementation should never result in empty interests. So how should we deal with the following case:

```rust
let interests = Interests::readable();
let empty = interests - Interests::readable(); // Invalid.
```

Empty is an invalid state, especially now when we're using `NonZeroU8`.

**Comment by carllerche** [comment]
@Thomasdezeeuw do we need a sub impl? I would be inclined to just remove it.

**Comment by FXTi** [comment]
@Thomasdezeeuw 
```rust
fn sub(self, other: Self) -> Self {
        Interests(self.0 & !other.0)
        Interests(NonZeroU8::new(self.0.get() & !other.0.get()).unwrap())
    }
```
The `unwrap()` is left here to throw the exception for the `Empty` situation, we can stop the thread and print more infos.

@carllerche I also doubt if we need a sub impl.

**Comment by Thomasdezeeuw** [comment]
I don't think we need a sub impl, but they are used in the test cases. I'm fine with removing it.

**Comment by FXTi** [comment]
Emmm... For an existing `Interests`, it needs to add / sub it when someone want to change it.`Or` is add and `Sub` is sub here. 

So Is there a chance to bypass all situations that you have to reduce some part of `Interests` and make another call to `register`?

If the answer is no, I guess we still have to offer a way to do the `sub` work.
@carllerche

**Comment by Thomasdezeeuw** [comment]
Since I don't think the API is used in production should just remove the sub implementation and look at it again once people request it? Because I don't think a lot of people change the interests after registering the first time, outside of testing. I could however be wrong of course.

**Comment by FXTi** [comment]
In `poll.rs: 911`:   
```rust
 /// `interest: Ready`: Specifies which operations `Poll` should monitor for
```

should be changed to 

```rust
 /// `interest: Interests`: Specifies which operations `Poll` should monitor for
```
