### ISSUE TITLE
Switch to winapi 0.3

### ISSUE THREAD

**Issue by nox** [tokio-rs/mio#953]
This has been stalled since forever now, and this actually is starting to hinder development of Servo, we are now in the process of forking both mio and iovec because of this. This certainly isn't good for the Rust ecosystem that mio is still stuck in the past.

Can we fix this huge problem before 2020?

https://github.com/servo/servo/pull/23449

**Comment by Thomasdezeeuw** [comment]
I don't have Windows so I can't really help here, but there is #956.

Would you like to see that in a 0.6.x release, or in 0.7 (of which the release date isn't clear and will be a bit in the future)?

**Comment by nox** [comment]
We needed that in 2018, so I don't really care in which version it happens, we just need it happening.

**Comment by chandde** [comment]
When will a new release be tagged, to have winapi 0.3.7 and iovec 0.1.2? we're also waiting for this..

**Comment by carllerche** [comment]
The winapi crate will be bumped with mio 0.7. This version will be released in coordination with the rest of the Tokio stack after `async / await` arrives on the stable Rust channel.

As part of this, winapi will no longer be included in the public API of any crate, so this issue will not happen again.

Until then, if including both winapi 0.2 and 0.3 in an application is not acceptable, patching the dependencies yourself is recommended (see [here](https://github.com/servo/servo/pull/23449)).

**Comment by nox** [comment]
Any ETA? It's been 2 years.

**Comment by Thomasdezeeuw** [comment]
Well it's already on master, but I don't think we have an ETA for 0.7.

**Comment by carllerche** [comment]
@nox there is no ETA. It will be done when it is done. I would appreciate it if you dropped the subject now.
