### ISSUE TITLE
CHANGELOG is out of date

### ISSUE THREAD

**Issue by benesch** [tokio-rs/mio#955]
Looks like the changelog is missing entries for the two latest versions (6.17 and 6.18) of mio. Perhaps the section marked "unreleased" just needs to be updated appropriately?

**Comment by carllerche** [comment]
Those would be here: https://github.com/tokio-rs/mio/blob/v0.6.x/CHANGELOG.md (on the v0.6.x branch) which hasnt' been merged into master yet. That file should also be bundled with the crate release.

**Comment by benesch** [comment]
D’oh, thanks!
