### ISSUE TITLE
Support vectored I/O 0.7

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#957]
Tracking issue: https://github.com/rust-lang/rust/issues/58452, stable in Rust 1.36.

New method: https://doc.rust-lang.org/nightly/std/io/trait.Write.html#method.write_vectored, using https://doc.rust-lang.org/nightly/std/io/struct.IoSlice.html.

We can replace the iovec crate with `IoSlice`.

(mio_st issue: https://github.com/Thomasdezeeuw/mio-st/issues/99)

**Comment by carllerche** [comment]
👍

**Comment by Thomasdezeeuw** [comment]
Closed by #1016.
