### ISSUE TITLE
WouldBlock vs Ok(0) for TcpStream

### ISSUE THREAD

**Issue by polybuildr** [tokio-rs/mio#967]
Currently, the [0.6.19](https://docs.rs/mio/0.6.19/mio/struct.Poll.html) docs say:

> With edge-triggered events, operations must be performed on the Evented type until WouldBlock is returned.

However, what about the case of `TcpStream::read` or `TcpStream::write` returning `Ok(0)`? I may have done something wrong or triggered undefined behaviour somehow, but I currently have a setup where read and write sometimes return `Ok(0)` seemingly infinite times. In this case, I can't read until WouldBlock because this never seems to happen in those cases.

Have I done something wrong and could you guess what it might be? I can also supply the server and client code, but it's not pretty... Or is this something missing from the docs?

**Comment by Thomasdezeeuw** [comment]
Reading `Ok(0)` means EOF, so there is no more data available. I don't know of any conditions when the `TcpStream` would return `Ok(0)` when writing.

**Comment by polybuildr** [comment]
@Thomasdezeeuw, is that strictly necessarily?

From the [Read trait docs](https://doc.rust-lang.org/std/io/trait.Read.html#required-methods)

> If n is 0, then it can indicate one of two scenarios:
>
>  - This reader has reached its "end of file" and will likely no longer be able to produce bytes. Note that this does not mean that the reader will always no longer be able to produce bytes.
>  - The buffer specified was 0 bytes in length.

I feel like the key thing to note here is "this does not mean that the reader will always no longer be able to produce bytes". Considering that this is non-blocking I/O, I wondered if this could mean that there's no data to return right now, but there might be data to return later - effectively a WouldBlock.

**Comment by sfackler** [comment]
No, that is not how the operating system indicates that state.

**Comment by polybuildr** [comment]
@sfackler, sorry - which comment you were replying to?

**Comment by sfackler** [comment]
> Considering that this is non-blocking I/O, I wondered if this could mean that there's no data to return right now, but there might be data to return later - effectively a WouldBlock.

**Comment by polybuildr** [comment]
@sfackler: I see. In that case, when I get an `Ok(0)` for a `TcpStream::read`, if that implies EOF, does that mean the connection has closed from the other side?

**Comment by sfackler** [comment]
You may still be able to write to the other side, but there's no more data to read from it.

**Comment by polybuildr** [comment]
I see. TCP half-closed connection then?

That seems odd because I thought I hadn't closed the connection from the other end - will double check that.

In any case, that still means the documentation needs to be updated, right?

> With edge-triggered events, operations must be performed on the Evented type until WouldBlock is returned.

should be changed to

"With edge-triggered events, operations must be performed on the Evented type until WouldBlock is returned or an EOF is encountered" or something of the sort?

**Comment by Thomasdezeeuw** [comment]
Well the point the documentation is trying to make is that you need to drain the OS buffer of the TcpStream because an event has been generated for it, only then will another event (when more data is ready) be generated. But I suppose you're right that it's currently not clear enough.

**Comment by polybuildr** [comment]
Yeah, you're right - reading between the lines, the 0 bytes state is not ambiguous. But yes, I think it could benefit from a clarification.

All the more so because I also looked at the example TCP server in the tests and it doesn't account for 0 bytes read either (though in that specific case it probably doesn't need to care):
https://github.com/tokio-rs/mio/blob/master/test/test_echo_server.rs#L77
