### ISSUE TITLE
Awakener design

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#968]
This the issue to discuss the design of the `Awakener`. The `Awakener` allows for cross-thread waking of `Poller`.

**Comment by carllerche** [comment]
My current thinking is to structure it so it can implement `Park` / `Unpark` from Tokio (which will be extracted into a separate crate as it is generally useful).

https://github.com/tokio-rs/tokio/blob/8d0f102de83f8aa59661b9d1839ecc57e50873a7/tokio-executor/src/park.rs#L58-L128

So, `Poll` would implement park, and it would be able to return an "unparker" that is `Sync + Send + 'static`. We can tweak the specifics. Maybe we want to include Clone on there...

**Comment by Thomasdezeeuw** [comment]
For Gaea (previously mio-st) I use the following design ([docs.rs](https://docs.rs/gaea/0.3.0/gaea/os/struct.Awakener.html)):

```rust
struct Awakener { /* ... */ }

impl Awakener {
    /// Create a new `Awakener`.
    /// 
    /// `Poller` will get events with the provided `id` when `wake` is called.
    pub fn new(os_queue: &mut OsQueue, id: event::Id) -> io::Result<Awakener> {
        // ...
    }

    /// Attempts to clone the `Awakener`.
    pub fn try_clone(&self) -> io::Result<Awakener> {
        // ...
    }

    /// Wake up the [`Poller`] associated with this `Awakener`.
    pub fn wake(&self) -> io::Result<()> {
        // ...
}
```

**Comment by Thomasdezeeuw** [comment]
After discussing with @carllerche, we've decided to use a design like mentioned in https://github.com/tokio-rs/mio/issues/968#issuecomment-499987787, but without the `try_clone` method.

**Comment by Thomasdezeeuw** [comment]
Done in #969.
