### ISSUE TITLE
Consider renaming `Interests` -> `Interest`

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#993]
I'm not 100% sure about this. I believe naming the type `Interest` would be more correct, but I could be wrong.

**Comment by Thomasdezeeuw** [comment]
I depends on how you read it I guess. I've always read it to be a set of interest*s*. But I don't a have strong opinion either way.

**Comment by carllerche** [comment]
I'm leaning towards renaming it as I feel like plural struct names aren't great (hard to differentiate `Event` vs. `Events` when reading). So, `Interests` should either be `Interest` (which I think works) or `InterestSet`. I prefer `Interest`.

Incidentally, I want to rename `Events` too :)

**Comment by Thomasdezeeuw** [comment]
I'm fine with the change to `Interest`. As for renaming `Events`, what do you suggest (also see #931)?

**Comment by carllerche** [comment]
What about `EventSet`?

**Comment by Thomasdezeeuw** [comment]
I'm good with that. Do want to name it `EventSet` or move it into the `event` module and name it `Set`, so we get `event::Set`?

**Comment by carllerche** [comment]
It should be in the `events` module... `events::Set` is a bit weird IMO... i don't hate `events::EventSet`, but I'm also open to other name options.

**Comment by Thomasdezeeuw** [comment]
I was thinking about this a bit more and maybe `Interests` should be merged with the previous `PollOpt` type, also see #1049. This way we can also make the layout platform dependent, like what we did with `Event`, so we don't have to do any conversions there.

**Comment by carllerche** [comment]
@Thomasdezeeuw this makes sense now that `Interests` is split out from `Ready`.
