### ISSUE TITLE
Remove `usize` conversions from `Token`.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#996]
At the very least `From<usize>` should be removed given #788. We could use a `TryFrom` since that is stable now.

**Comment by stevenroose** [comment]
I'd also appreciate a better conversion towards the inner usize. Currently I'm doing `usize::from(token)`.

**Comment by Thomasdezeeuw** [comment]
@stevenroose what is wrong with `token.0`? The inner `usize` is public.

**Comment by stevenroose** [comment]
Oh, I didn't notice that. That's not very commit. But yeah now that you say so, I do use the `Token(x)` constructor. Cool, thanks.

**Comment by Thomasdezeeuw** [comment]
@carllerche I'm OK with removing this conversion. But I do want to keep the field public, even if we go through with #788. I have quite a bit of code that converts to and from `Token` and I don't really want to deal with an `Result`/`Option` there, even if it would call `unreachable!` or something.

**Comment by carllerche** [comment]
@Thomasdezeeuw if bits are reserved, it is safe to go from `Token` -> `usize`, but not from `usize` -> `Token` as if you set the reserved bit, it isn't a "valid" token (imo).

That said, I think it is fine to panic in that case instead of dealign w/ result / option.
